crdschurch/crds-net

README.md
This commit adds setup documentation for both Mac and Windows
environments, taking a person from not having Ruby installed on their
machine to building and running the preview server in Jekyll.
=> Add Setup Documentation

_config.yml
Add support for hierarchical slugs. This PR updates the project so that any page with a slug containing a slash will be respected during the build... for example:
https://5b27c49ab13fb17d7cd284f5--crds-net.netlify.com/purus-cursus-tristique/something
=> US13860 Pages

_config.yml, _redirects, netlify.toml
This commit sets up proxying calls using the _redirects file, instead of
the previously used netlify.toml file.
=> US13848 Setup Project

stream.html, tmp/purgecss.js
Switching iframe `src` from prod to int seems to allow giving to work correctly.
=> US14437: Give Widget

.gitignore
this file can be used to load dynamic environment variables for windows machines that only exist in the PowerShell context currently loaded instead of loading system wide environment variables
Windows Users: create the loadenv.ps1 and then create a line for each needed environment variable as follows
`$env:NAME_OF_VARIABLE = "value_of_variable"`
Note: You must load the file before you run the serve command or the contentful command. use `.\loadenv.ps1`
=> Added loadenv.ps1 to gitignore file

_includes/_location-card.html
added 'markdownify' to the location address so it properly adheres tomarkdown carraige return (two spaces)
=> Fix for locations cards address not being properly formatted

Gemfile, Gemfile.lock, _config.yml, netlify.toml
What this does:
- updates us to jekyll-contentful 1.1.0
- uses new exclusions via config file
- grabs the 4 most recently (by `published_at`) messages and series
=> US15275: Update Jekyll Contentful

lib/crds/redirect_writer.rb, redirects.csv, spec/unit/redirect_writer_spec.rb
**tldr;**  
When adding redirect rules into `redirects.csv` you can now define a 4th column for 'context' that determines which branches the rules will be deployed. If that column doesn't exist for a given row, the rule will be deployed everywhere. 
---
This PR adds contexts to `redirects.csv` so you can target different environments with your rules. This allows us to include certain redirects/proxies in INT (during feature development) while excluding them from PROD. 
This concept of "context" is largely driven by Netlify's idea of [deployment-context](https://www.netlify.com/docs/continuous-deployment/#deploy-contexts) albeit with some nuance not worth explaining here. For practical purposes, we can use this new feature by defining the target branch(es) as our context, for example... …
=> US15273 Redirect Contexts

cypress/kickOffCypress.sh
- Fixed Travis config so tests will run against Netlify's preview url on a new PR, and against the live site once the PR is merged. Currently it will not run against Prod, either preview or live site.
- Make it easier to 'turn on' testing in production
=> shenney/CYP - Smarter Travis configs

cypress/kickOffCypress.sh
- Only run tests after code is merged into int or demo, not as a PR check, so we don't block merges because of bugs in the test, not the new code
=> shenney/CYP - Run tests after merge, not as PR check

_pages/baptism.html, _pages/leader-update.html, _pages/student-ministry.html
includes: 
- reformatting HTML
- removing all refs to `sitetree` which is an SS convention.
This looks a lot bigger than it actually is because of HTML reformatting.
=> DE6168: Remove Sitetree links

_assets/stylesheets/pages/_forms.scss
- explicitly set uppercase text on FRED forms
- used `!important` to override the inline style bundle that we get from FORMIO
=> DE6176: Control Labels

_includes/_head.html, _includes/_monetate-body.html, _includes/_monetate-head.html, _layouts/default.html, index.html
Allows Monetate editors to target just the homepage
adds monetate pagetype code to head and body on homepage only
For the `monetateQ` and `trackData` method, it is important they are implemented as follows:
`monetateQ`: Implement this method at the top of the page template, just below the Monetate tag in the `<header>` of your site, to ensure the object is initialized when calling further API methods.
`trackData`: Implement this method at the bottom of the page template after all the content has been loaded.
The Monetate tag is currently being implemented through GTM
No corresponding PRs
Unfortunately, Monetate is tied to the URL, so you can't test this through the deploy preview.
On int and local builds, you can tell the Monetate API calls are working correctly by using the Monetate …
=> US15900 Add Monetate Page Type to CRDS.net homepage

.travis.yml, cypress/kickOffCypress.sh
PLEASE tell me before you merge this - I need to set the configuration in Travis.
- Changed caching instructions for travis-ci
Travis says you need to enable their "build pushed branches" option for caching to work, but we don't want to do this for various reasons. To allow caching on their side without actually running builds when we don't want them to, I've configured Travis not to build any branches. We explicitly kick off Travis builds when we want them so I'm hoping the "ignore branches" config will only apply for automatic builds, and we'll still be running tests when we do now. Unfortunately, there's no way to test this theory until this PR is merged. 😄 If it doesn't work, I'll undo the config and we'll just not be able to use the cache.
=> [CYP] feature/US15755 - Travis Caching

index.html
This will be hotfixed with AG's homepage changes to show a jumbotron when there is a livestream
=> DE6239 removed problematic javascript inclusion

_plugins/filters/html_and_meta_util_filter.rb
This just fixes another issue I found and it unrelated to this cards story. There are two fixes for this defect elsewhere:
1. A page pushed directly to crds-net-shared that is already deployed to production (https://www.crossroads.net/studentministry/)
2. Updating imgix-optimizer in #539.
=> DE6277 - Promo Cards

redirects.csv, spec/fixtures/redirects.csv
Maestro is bad
Netlify is good
*Add link to crdschurch/crds-net/US15701-Remove-Maestro
Make sure all previously rendered pages by Maestro are still working appropriately
=> US15701 - removing maestro redirect

_includes/_head.html
demo and int can be crawled and indexed by Google
added logic so that if we are no in production we will tell google not to index, relies on JEKYLL_ENV
=> DE6316 disable int and demo being searchable on Google

_includes/_head.html
prerender.io is waiting for page to load completely before capturing meta data, allowing third-party apps to interfere unintentionally with meta data
added variable prerender looks for so that it immediately captures meta data before any js is loaded
=> US16238 meta data issues

.travis.yml, cypress/Contentful/ContentfulApi.js, cypress/README.md, cypress/fixtures/test_users.js, cypress/integration/infrastructure/redirect_regression_spec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js, cypress/kickOffCypress.sh
*I can't set up environment variables. (Not all variables to authenticate a user were passed to Travis.)*
*A redirect-related test was failing because Contentful limits their responses to 100 entries.*
*Corkboard tests were failing because the page took too long to load.*
*A redirect test was failing because a modal was added to Camps.*
*Set up environment variables until I finally get it right. (Sent all the environment variables to Travis).*
*Upped the response limit to 1000 (max possible) for that request.*
*Increased timeout when navigating to Corkboard to 10s.*
*Changed the redirect test to start from Giving. The test covers the same scenario with less effort.*
*User password will be pulled from Travis, not Netlify, since Netlify isn't running the tests.*
*Improved the Readme to …
=> [CYP] Fixes test failures and corrects Travis configuration

.env-sample, 404.html, redirects.csv
Our new search isn't able to be search via query params (for now).
Remove search input on 404 in favor of a button that links to search
N/A
Is there a button there? Does it link me to search?
=> USXXXX: Remove Search From 404

cypress/integration/external_repo_media/current_series_page_spec.js, cypress/integration/sharedHeader/profile_dropdown_link_authspec.js, cypress/integration/sharedHeader/support/my_profile_menu.js
*Changed the way a certain jumbotron image is being verified to wait until it's fully loaded before verifying.*
*Attempted to fix an intermittent issue where a My Profile menu dropdown link couldn't be found before it was clicked.*
=> [CYP] Handle some slow loading elements better

_layouts/default.html, bin/health-check.sh, index.html, netlify.toml
Intermittent build failures sometimes result in a zero-length index.html file. 
This PR adds a new bash script to the end of our build command that looks for the presence of a string in `_site/index.html` and if it is not present, throws a non-zero exit code which will cause the build to fail. 
The first build on this PR was designed to fail. You can review [the log output](https://app.netlify.com/sites/int-crds-net/deploys/5c74365a04672f00086c6d6f) but it basically reports this... 
```1:40:40 PM: <\!-- we are crossroads. --> not found in ./_site/index.html```
This messaged was logged (and the build failed) due to the trailing period which does not exist in `_site/index.html`. The subsequent build corrects the string we're looking for, thus the build should pass.
=> US16586 Health Check

cypress/Contentful/ContentfulApi.js, cypress/Contentful/Models/SeriesModel.js, cypress/integration/homepage/home_page_latest_message_spec.js
If the current series does not have a message, automated tests will calculate the current message's slug incorrectly.
Store the series for the current message separately from the current series. The fix here is the quick & dirty version, a smarter fix will be implemented in US16618.
=> [CYP] - Series for current message fix

cypress/integration/404/404_spec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js, cypress/integration/sharedHeader/profile_dropdown_link_authspec.js, cypress/integration/sharedHeader/sign_in_and_out_authspec.js
*We didn't have automated tests to make sure the search button on the 404 page loaded /search.*
*There is a known authentication issue (DE6458) that will cause some of our tests to hang.*
*Added a test to click the search button on the 404 page and confirm /search loads.*
*Tests affected by the authentication issue have been skipped until that defect is fixed.*
=> [CYP] - 404 button to /search & auth issue skips

_assets/javascripts/lib/data-tracker.js
Refactor data-tracker so its instantiated one-time, everywhere. 
This will allow us to use the `data-track-click` and `data-track-submit` attributes all over the place without having to instantiate the DataTracker object in a bunch of different places. 
I tried to design this update so that it can only ever be instantiated once. Subsequent script invocations will just return the previously existing instance. 
Let me know if you have any questions.
=> US15395 Giving Analytics

netlify.toml
logging on Netlify is not great right now
Nullify logging on contentful for the time being as it's the highest logging task during the build. Also the most well understood.
=> push jekyll contentful output to dev/null to improve netlify logging

cypress/Contentful/ContentfulApi.js, cypress/Contentful/ContentfulElementValidator.js, cypress/Contentful/Fields/ImageField.js, cypress/Contentful/Models/MessageModel.js, cypress/Contentful/Models/PromoModel.js, cypress/Contentful/Models/SeriesModel.js, cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/live/live_latest_message_spec.js, cypress/integration/locations/locations_search_spec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js
- Fixed the logic for finding the series that the current message belongs to. The same logic can also be used to find the series for any message, which was not possible before.
- Handles the scenario when an image asset is unpublished, but not removed from the Series/Message/whatever in Contentful.
- Removed debug log statements
- Turning on /location search tests - defect has been fixed
- Attempted to gracefully handle the /corkboard cross-origin errors that randomly happen. Unfortunately I couldn't reproduce them so the two blocks catching the 'uncaught:exception' are untested, but don't impact the passing test. Will continue to monitor this problem and update the fix.
=> [CYP] - Correct current message/series relationship & other bug fixes

_assets/javascripts/config.js, _assets/javascripts/lib/environment.js, _layouts/default.html
This PR adds support for environmentally specific hrefs. 
Now, you can specify a `data-href-int="..."` or `data-href-demo="..."` attributes on any `<a>` tag. When run in the INT or DEMO environment, the link's `href` will be swapped out for the corresponding value, client-side. 
Here's an example... 
```
<a href="/production" data-href-int="/int" data-href-demo="/demo">Link</a>
```
Let me know if you have any questions. Thanks!
=> DE6358 Environments

cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.js, package-lock.json, package.json
- Updating the plugin crds-cypress-tools to use ES6 syntax revealed that Cypress does not handle ES6 packages well (or that I can't write js, which may be more likely). 
- Added a preprocessor step that does some browserify and babel magic on just that package and makes it work.
- Updated Cypress to most recent version
- This preprocessor step is a really hacky workaround that probably won't work if we need to add more plugins. I'm trying to understand how Nodejs and Cypress's process things better so we can build a better package and let us remove this preprocessor workaround.
=> [CYP] - Added preprocessor to handle cypress-tools update

_assets/stylesheets/components/_cards.scss
Following a recent update, the topic cards on the homepage of cr.net are no longer clickable.
Add z-index to the element containing the content so it shows up above the overlay.
=> DE6601 Topics

_assets/stylesheets/components/_cards.scss
Following a recent update, the topic cards on the homepage of cr.net are no longer clickable.
Add z-index to the element containing the content so it shows up above the overlay.
=> [hotfix] Topic Cards Aren't Clickable (release)

_assets/stylesheets/components/_cards.scss
Following a recent update, the topic cards on the homepage of cr.net are no longer clickable.
Add z-index to the element containing the content so it shows up above the overlay.
=> [hotfix] Topic Cards Aren't Clickable (master)

_assets/javascripts/components/images.js
On rare occasion, ImgixOptimizer will fail to process images which results in a bunch of fuzzy low-res artwork that never clears up. This could be a race-condition thing or a bug in the ImgixOptimizer or Imgix.js libraries. 
Check every 250ms that imgix has been initialized and if so, trigger a resize event on the window object which causes Imgix to reevaluate the images on the page.
=> DE6590 Imgix

_assets/javascripts/components/images.js
On rare occasion, ImgixOptimizer will fail to process images which results in a bunch of fuzzy low-res artwork that never clears up. This could be a race-condition thing or a bug in the ImgixOptimizer or Imgix.js libraries. 
Check every 250ms that imgix has been initialized and if so, trigger a resize event on the window object which causes Imgix to reevaluate the images on the page.
=> [hotfix] DE6590 Imgix (master)

_assets/javascripts/components/images.js
On rare occasion, ImgixOptimizer will fail to process images which results in a bunch of fuzzy low-res artwork that never clears up. This could be a race-condition thing or a bug in the ImgixOptimizer or Imgix.js libraries. 
Check every 250ms that imgix has been initialized and if so, trigger a resize event on the window object which causes Imgix to reevaluate the images on the page.
=> [hotfix] DE6590 Imgix (release)

cypress/Contentful/ImageDisplayValidator.js, cypress/Contentful/QueryManagers/MessageQueryManager.js, cypress/Contentful/QueryManagers/PromoQueryManager.js, cypress/Contentful/QueryManagers/SeriesQueryManager.js
- Contentful queries were using incompatible date formats when running on Travis.
- Jumbotron image validation logic was converted incorrectly for image not published/missing scenario.
- Converted dates to UTC before formatting
- Fixed jumbotron image logic
=> [CYP] Fixed time zones in queries

_includes/media/_overlay-card.html
Only call `get_doc` for featured items if url property is not already there.
These guys are not pointing to the correct URLs, but there are redirects in place that make it work. However, it is using the paths that come from Jekyll, so I feel like it is a reasonable approach (for now).
=> DE6603 - Featured Media Links

index.html
It was wrong 50% of the weekend because it pulls the current message
title from what is published. And since we don’t publish the new
message til Sunday, it was showing the incorrect message on Saturday
and Sunday morning (during those streams)
=> hotfix - remove live stream title

index.html
* Require small changes to home page
* Change “recent articles” -> “recent”
* “latest articles” -> “latest” when no recent articles defined
* Close gap between latest podcast episodes and explore our topics
https://rally1.rallydev.com/#/41662702253d/detail/userstory/295417595880
View homepage at various widths
=> US16851 - Home page improvements

.travis.yml
- We're out of recordings on Cypress's dashboard so tests are failing. This changes the whole run configuration to a variable instead of just the token, which should allow us to turn off recordings if needed.
=> [CYP] Report to dashboard now an envvar

.travis.yml
Trying to pass in a full CLI command as a Travis envvar didn't work. Here's the lazy way of avoiding the Cypress dashboard that will require manually adding the command back.
=> [CYP] Removed running on dashboard

_assets/stylesheets/pages/_community-store.scss
Mobile devices can scroll right and expose a few extra pixels to the right of the fluid containers on the page. 
This PR removes a little extra margin to the left of the carousel component.
=> DE67245 Horizontal Scroll

_assets/stylesheets/pages/_app.scss
The stylesheet for /app currently uses global style overrides which will impact other pages in crds-net.
Create a namespace class in order to scope these style overrides to only /app.
=> give /app namespace class

_plugins/hooks/sitemap.rb
pages which are excluded from search are showing up in the sitemap.xml
added hook to exclude pages from sitemap when search_excluded is true
=> DE6830 sitemap exclusions

liveStreamTests/cypress/integration/live_stream_message_spec.js
- Confirms latest message published anytime Saturday, not just after 7:15 (Contentful defaults to midnight, not now)
=> [Hotfix][CYP] Fixes live stream test timestamp

.eslintrc.json, Gemfile.lock, _includes/_footer.html, cypress/integration/homepage/home_page_current_series_spec.js, index.html, package-lock.json, package.json
- "Watch the latest message" link on the homepage broke when Shared Header 2.0 was deployed
- Changed the href source to  not use media snippets
- Updated automated tests
=> DE6922 - Watch latest service button href not from media snippets anymore

cypress/integration/live/live_jumbotron_spec.js, cypress/support/RouteValidator.js
- Exact start times for live stream cannot be spoofed accurately when running on Travis
- Test around streaming states - "offstream", "upcoming" and "live" instead of exact times.
=> [CYP] Fixed Live jumbotron tests

cypress/integration/homepage/home_page_happenings_spec.js, cypress/integration/locations/locations_search_spec.js, package-lock.json, package.json
- The /locations search tests are pretty flaky due to persistent load order issues
- Added a function that'll try to trigger the errors and reload the page if they're caught. Recursion ftw.
=> [CYP] DE?? - Make /locations search less flaky

_assets/javascripts/components/bitmovin.js
Events were not working for live streaming. Due to adding the "if a player pauses disable all future events."
Only cancel events if a pause is caused by the UI. If the player loads and the browser blocks playback this should not count as a "pause" event. If the playback finished, this should also not count as a "paused" event. 
See rally story for testing scenarios.
=> fixing stream events

_config.yml, _plugins/generators/onsite_groups_generator.rb, onsite-groups.html
This hot fix PR reverts b03a948e279dc0b6adab793a27627cf684bba7e1 that was introduced into `release` and `master` last week to prevent OSG pages from displaying in the demo or production environments. 
The intention here is to ensure no conflicts are introduced via future deploys to these two environments.
=> [hotfix] Reverts #1132

onsite-groups.html
Onsite group categories were showing up even if there were no groups
Add a zero state for onsite group categories
The Recovery category is no longer on the page.
https://deploy-preview-1135--int-crds-net.netlify.com/groups/onsite
Previous screenshot: The Recovery category is showing and has no groups
=> de7141 onsite groups zero state

_config.yml
This PR updates crossroads.net to exclude pages that are part of a collection in Contentful. Collections contain pages that are specific to crdsmusic.com & briantome.com. 
crdschurch/crds-music#74
crdschurch/crds-contentful-migrations#157
crdschurch/briantome#64
=> US17535 Pages

README.md, _config.yml
Content with a future published_at date is being shown on the homepage
properly configure collections to append the file with the date so that it becomes excluded
=> De7119 future was now

liveStreamTests/cypress/integration/live_stream_message_spec.js
- Sunday 5AM live stream ready check ran but didn't Slack results because that part was skipped. Oops.
=> [CYP][Hotfix] Unskipped the part that slacks results

logged-in-homepage.html
overlay-card wasn't being used on that section which has the logic for handling a podcast episode
=> updated logged in homepage to use the overlay card

_layouts/onsite-group-detail.html, _layouts/onsite-group-location.html, _plugins/generators/onsite_groups_generator.rb
Onsite group locations and meeting group pages should be linked together.
[Original Task](https://rally1.rallydev.com/#/38108142417d/custom/292180449324?qdp=%2Fdetail%2Fdefect%2F348354355704)
- The titles for the meetings on a location page have been linked to the meetings group page.
- The location names on each meeting page have been linked to the corresponding location
- Verify that the meeting groups have their related locations linked. [Click here for the list](https://deploy-preview-1216--int-crds-net.netlify.com/groups/onsite) **Top of page**
- Verify that the meetings on the locations are linked to the individual page. [Click here for the list]
- **Note:** There are some meetings that are not related to a group primarily Lipsum/Test types. They will not receive a link unless they …
=> DE7300 Link meetings and locations

_layouts/location.html
Decorating sign-up for all locations is over and needs to be removed.
Removed content block for a sign-up link for all locations
hotfix/remove-location-decorating-signup
Locally tested
=> Remove decorating signup

_layouts/location.html
Need to hide Xmas red container and/or content blocks if no content is available to show the user.
If & or conditionals added to automatically hide content if empty.
feature/special-service-times-for-holidays
Local development testing. Ex. /downtown should should not show any Xmas block content.
=> Conditionals to hide Xmas block if empty

_layouts/onsite-group-detail.html, _layouts/onsite-group-location.html
The Onsite Group meetings descriptions Markdown is not being converted to HTML. This happens on both the Group Location page and the Group Details page. 
Added `markdownify` to the `meeting.description`s in both `onsite-group-location.html` and `onsite-group-detail.html` to convert the Markdown to HTML
- [Location](https://deploy-preview-1262--int-crds-net.netlify.com/groups/oakley/)
- [Details](https://deploy-preview-1262--int-crds-net.netlify.com/groups/connection/adoptive-and-foster-care-for-moms)
=> DE7379 [osg] markdown not rendering for group meetings

_layouts/onsite-group-detail.html
When no date is entered into the start field for a Group Meeting, do not display "Start" on the front end, Also sometimes this random letter S appears at the bottom of the header
=> DE7474-OSG

.travis.yml, bin/kickOffCypress.sh
- Removed key leak when kicking off build in Travis
- Configured Cypress to run on it's built-in Electron browser instead of Chrome (because of issues running Chrome 80 on an old version of Cypress)
=> defect/US19010 - Fix Travis ci leak for Cypress tests

_plugins/filters/onsite_groups_filters.rb, onsite-groups.html
- Converts the Onsite Groups landing page to 3 columns
- Truncate group description to  275 characters ~5 lines
- [Story](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fuserstory%2F370828226740)
- [Design](https://projects.invisionapp.com/share/TVSEW6P3MDK#/screens)
[Preview](https://deploy-preview-1360--int-crds-net.netlify.com/groups/onsite)
=> US19036 [OSG] Landing: Refactor to 3 Column Layout

netlify.toml
Ensure production proxies to crds-angular are served via the enterprise CDN
=> Enterprise CDN Support

_layouts/onsite-group-location.html, lib/crds/onsite_groups.rb, spec/fixtures/collections/_onsite_groups/adoption-and-foster-family-resources.md, spec/unit/onsite_groups_spec.rb
This PR ensures that meetings which have no association to a group do not display on the front-end.
=> Onsite Groups

bin/build-command.sh
We start out with 4354 references to ctfassets and decided to update the build script with sed to change assets and images after the site is built. After running the sed command we are left with 3686 references to ctfassets, that is 571 downloads and 3110 videos. We are not changing assets because they are mostly PDFs and it changes the content type to an image when being hosted from Imgix so It does not get treated as an PDF(when clicked on, it won’t show print or download option like you would normally see from a PDF). We are also not changing videos because some of these videos are entire sermons so the file size is going to be very big and imgix will not be able to handle that.
The sed script is only changing images because there are PDFs associated to assets
=> US19168 Ctfassets

redirects.csv
On April 7th, there is an update to how Netlify handles redirects. Redirects will no longer be assumed to be forced so we need to add "!" to make all redirect forced in every project.
add "!" to redirects
=> DE7599 Netlify Redirects Development

redirects.csv
On April 7th, there is an update to how Netlify handles redirects. Redirects will no longer be assumed to be forced so we need to add "!" to make all redirect forced in every project.
add "!" to redirects
=> DE7599 Netlify Redirects Master

_assets/javascripts/components/jumbotron-video.js
For all new visits to the `/online-easter-service/` page in a new tab, the "Watch the trailer button does not work" until you refresh the page.
This PR wraps the Jumbotron in` $(document).ready` so it waits until the DOM is loaded to try to initialize the jumbotron videos
=> Fixes the jumbotron not opening on easter page

_assets/stylesheets/_fonts.scss, _assets/stylesheets/components/_tabs.scss
Change colors as needed for the Giving page
[Rally Story](https://rally1.rallydev.com/#/38108142417d/detail/userstory/392171744224)
Changed the active tab color to orange and changed the blue buttons to orange
Also added the updated fonts file and updated crds-styles
I have made a separate Giving page for rebrand in contentful [here](https://rebrand.crossroads.net/giving-rebrand/) and this where you will see the buttons changed from blue to orange
=> US19556 Giving

_assets/stylesheets/pages/_go-trips.scss
Update reachout/go page for rebrand
[Design here](https://www.dropbox.com/s/h9fmgeoq9fxwbgm/rebrand_crossroads_net_reachout_go___2_.jpg?dl=0)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/394024759516?fdp=true)
Page is updated in contentful.
Deleted style where it was hardcoding the btn color on the trips header to be old blue
[Crds-Styles](https://github.com/crdschurch/crds-styles/pull/433)
=> US19581 Reachout Go

_includes/_location-card.html, _includes/_locations-search.html
Update location page to look like [this design](https://www.dropbox.com/s/rybty40zpfwkafn/Screenshot_2020-05-20_13_31_05.jpg?dl=0)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/393997554808?fdp=true)
Had to make changes in crds-styles to update `btn-link` to be dark orange and crds-components had to update the crds-button to have orange as an option
Spoke to Rob about button color for the search button on location page and decided to make it a blue button
[Crds-Styles](https://github.com/crdschurch/crds-styles/pull/427)
[Crds-Components](https://github.com/crdschurch/crds-components/pull/586)
Changes will not come into effect until the two PRs are merged
=> US19577 Update Location Styles

_includes/groups/_meeting-details.html
Change button color for onsite group details page to match rebrand criteria (orange button/ blue text) 
[Rally](https://rally1.rallydev.com/#/66096747656ud/detail/userstory/393973364824?fdp=true)
[CRDS-Styles](https://github.com/crdschurch/crds-styles/pull/432)
Created orange button with blue text and implemented style to on-site groups details page. 
Run crds-net locally, and navigate to any on-site groups details page. 
Example url - /groups/onsite/COME-AS-YOU-ARE-FLORENCE-2019/columbus/
=> US19575/ Rebrand meeting details button

_includes/home/_current-series.html, rebrand-logged-out-home.html
View all button should go to the url of the displayed series
'Ways to Watch' should be a promo from Monetate (this will be handled by AG or Jake)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/395254534424?fdp=true)
Add Current series to Rebrand Logged Out Homepage and add crds-button to access all messages in a series 
[Preview](https://deploy-preview-1529--int-crds-net.netlify.app/rebrand-logged-out-home)
=> US19622 Current Series

_includes/home/_current-series.html
In the "Current Series" section on the logged-out home page. This PR changes header to "Current Teaching Series" and btn label to "Watch the current teaching series"
- [Preview](https://deploy-preview-1546--int-crds-net.netlify.app/rebrand-logged-out-home)
- [Rally Story](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F397667357108)
=> DE7777 [rebrand] homepage - current series - update copy

_layouts/location.html
1. On location detail, make the "About this location" text align horizontally with the horizontal rule above the social media links:
2. When clicking on the anchor links for either "See what's happening" or "Community care" at the top of the page, the anchor stops flush with the section header and the nav. It's a little too tight, needs some breathing room:
[Preview](https://deploy-preview-1543--int-crds-net.netlify.app/oakley)
=> DE7776 Location Detail

_assets/stylesheets/_utilities.scss, _assets/stylesheets/components/_jumbotron.scss, _includes/about/_faqs.html, _includes/about/_leadership.html, about.html
Compose About page based off [design](https://invis.io/5TWTAP2G7SH#/421584693_About_Us_-_Final_-2-)
- Uses the new portrait card expanded component
- FAQs at bottom should all act as anchor links
- You will also need to get all the links to their social handles
- 30 Day Trial CTA btns link to /30daytrial/sign-up (page does not exist on INT, only on prod)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/397742052760?fdp=true)
[Preview](https://deploy-preview-1564--int-crds-net.netlify.app/about)
On the jumbotron, the background gradient overlay color is being fixed in US19707
This PR adds bg-overlay on the portrait card images and adds a gray background for staff without an image (i.e. Darin Yates)
[Crds-Components](https://github.com/crdschurch/crds-components/pull/661)
=> US19688 about

netlify.toml
This PR updates the route for the legacy proxy in the DEMO environment. This update won't do anything until merged into `release`.
=> DE7796 Demo Legacy

_layouts/location.html
On location detail pages, a few things need to be finished or updated (see design for reference):
1. Update the image to match the design on the Community Care promo
2. Add the "We'd love to connect with you" jumbotron at the bottom of the page. Should initiate the chat widget when clicked (see US19710)
3. Move Community Care promo below Kids & Students and above Go Deeper
4. Use blue outline btns on the Kids & Students section  
5. Make all inputs on the subscribe form the same width
6. Background color on the Kids & Students section is too dark. 
7. Change btn labels on Community Care promo to "Request care" and "View all services"
8. Card style on Go Deeper section needs updated to no longer use the indented card style:
9. Alignment of social btns on mobile is off (screenshot) …
=> US19711 Location Detail

_includes/media/_media-card.html, _includes/media/_overlay-card.html, index.html
AG has asked that we apply the beige color overlay to certain images within the media project. Specifically:
- Jumbotrons on article detail pages
- Related article thumbnails at the bottom of article detail pages
- All media cards on /media/articles
- All cards /media/videos
- Media Landing page: all media cards for content types ARTICLE and VIDEO (non-message) only
- Homepage Logged In: all media cards for content types ARTICLE and VIDEO (non-message) only\
- Homepage Logged Out: ll media cards for content types ARTICLE and VIDEO (non-message) only -- note this should only impact the three media cards towards the bottom third of the page. 
[Crds-Media](https://github.com/crdschurch/crds-media/pull/938)
[Crds-Components](https://github.com/crdschurch/crds-components/pull/670)
=> US19649 media image updates

_includes/home/_jumbotron.html, _includes/home/_you-are-needed.html, index.html
homepage logged out feedback from Vivienne per her runthru w/ AG
1. Flip these two cards
2. In the paragraph of text in the jumbotron, link the words "spiritual outfitter" to /spiritual-outfitters
3. Remove the orange subheader here. Change "Articles, Podcasts and more" to read "OUR BEST CONTENT" instead
4. Change copy on the "Guide Others" card in the "YOU ARE NEEDED" section as follows:
header: GO BE THE CHURCH
descrip text: We are God's Plan A. There is no Plan B. See how you can make an impact in your neighborhood and around the world.
(link remains the same)
5. Change copy on the "Explore Giving" card in the "YOU ARE NEEDED" section as follows:
header: GIVE TODAY
descrip text: You'll never have to wonder if your life matters.
(link remains the same) …
=> DE7823 Homepage

_includes/_location-card.html
Community Pastors section was too dark, and text was dark. 
[Rally ](https://rally1.rallydev.com/#/66096747656ud/detail/defect/399691515592?fdp=true)
Lightened up gray background and changed `<p>` text to white. 
Before: 
After:
=> DE7835/Community Pastor section on locations page

_includes/_head.html
Adds cache buster `?v=2` to favicon URLs to bust the cache.
**Note:** This may be hard to test on a deploy preview due to it being related (I believe) to having the favicon cached
- [crds-media](https://github.com/crdschurch/crds-media/pull/948)
- [Preview](https://deploy-preview-1621--int-crds-net.netlify.app/)
=> DE7850: [Rebrand] Old favicon shows while page is loading

_includes/home/_current-series.html, _includes/home/_kids-club-jumbotron.html, _includes/home/_latest-message.html, index.html
1. Update the Kids Club logo 
2. Update the image for the Crds app callout to show updated screenshots of app UI
3. Update link for Facebook ("kickstart your morning at 8:30am") to point to https://www.facebook.com/crsrdschurch/ (they changed the URL)
4. In the "articles, podcasts, and more" section, any chance we can omit messages from this since we're already showcasing most recent message so prominently on the page? If it's a heavy lift, just skip. it's a nice to have.
5. Change "Latest Weekly Teaching" subheader to "Latest Crossroads Weekend"
6. Change header on "Get Equipped" to "Get Equipped: Watch the Weekend"
7. Change "Current Teaching Series" header to "Current Series"
[Rally Defect](https://rally1.rallydev.com/#/detail/defect/399895452332?fdp=true) …
=> DE7844 Homepage Edits

_includes/_the-basics.html
Portrait cards are inaccurately spaced on mobile. 
[Rally](https://rally1.rallydev.com/#/66096747656ud/detail/defect/399926726576?fdp=true)
Removes hard-coded `&nbsp;` and adds a max-width to `portrait-card-title` in contentful on affected pages.
=> DE7849/removes hard-coded space in title

_assets/stylesheets/components/_jumbotron.scss, _includes/home/_jumbotron.html, index.html
1. Update the video that displays when you click the play btn in the jumbotron on the logged out homepage - https://youtu.be/jTtFrLl17aM ✓
1. Update the background video in the homepage jumbotron (https://videos.ctfassets.net/y3a9myzsdjan/61UX4j16LJ4i6Hul1obi2Z/02c4498b9d0c1ef87fb7767fbfcaed54/spiritual-outfitters-loop.mp4) ✓
1. We do not have the asset for this one.
1. Also removes a few left over `class=""` attributes
[Preview](https://deploy-preview-1630--int-crds-net.netlify.app/)
=> US19751: [rebrand] Update all the videos [LAUNCH CRITICAL]

index.html
**Note:** Related **crds-data** PR below should both be merged before reviewing.
This PR removes the "Your adventure starts here. Start your 30 day trial!" so it can be replaced with the current "Buildings are currently closed." message
[Rally Story](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fuserstory%2F400139649124)
[Preview](https://deploy-preview-1633--int-crds-net.netlify.app/)
- [crds-data](https://github.com/crdschurch/crds-data/pull/48)
=> US19788: [rebrand] modify header alert msg to show on all pgs

_includes/_location-card.html
"Other Ways to Watch" link is being managed in Contentful and we have a static link in the location card template. This is causing duplication.
Remove static link for "Other Ways to Watch" in the location card template.
Local
=> HOTFIX: Removing other ways to watch link

_includes/_location-card.html
Not everyone's pastor photo was cropped at 1:1 aspect ratio.
Use imgix to auto-crop and set 1:1 aspect ratio.
Local
=> HOTFIX: Fixing pastor image aspect ratio

_layouts/location.html
Removes `upcase` filter to allow the location title to be as entered in Contentful to solve the capitalization issue on all location pages found in the screenshot below.
[Rally Story](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F400331166752)
=> DE7883: [rebrand] capitalize city names on location detail pages

_includes/about/_faqs.html, _layouts/location.html
1. /groups - clicking on those anchor links scrolls to the section, but little bit below where it supposed to scroll, cutting the header a little
2. /about  - FAQ
3. location detail page (exmp - https://www.crossroads.net/columbus) - anchor links on jumbo of each location 
1. [Preview](https://int.crossroads.net/groups/)(changed in contentful)
2. [Preview](https://deploy-preview-1648--int-crds-net.netlify.app/about)
3. [Preview](https://deploy-preview-1648--int-crds-net.netlify.app/oakley)
=> DE7887 FAQ Scroll

README.md, bin/local-build-command.sh, docker/development/Dockerfile, docker/development/README.md, docker/development/docker-compose.yml
- Windows cannot correctly build & serve crds-net locally so it's not possible to fully test changes
- Generally environment setup can be a pain, so contributors with minor/infrequent changes may be discouraged from testing changes locally before committing
- Use Docker containers to provide an easy to run build & serve environment that'll behave the same across any OS
Could someone with a Mac follow the readme to build & run the Docker container and confirm the following:
- Once the server is running in the container you access the site from "localhost:4000"
- While the server is running you can make changes to the site (like html or css, not Contentful content) and the site will automatically rebuild and serve the changes without needing to restart the container
Could someone (also with …
=> feature/Dockerize crds-net build & serve environment

_includes/home/_jumbotron.html
In Chrome on iOS the [App Banner](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) for the Crossroads app does not load on the home page.
This was related to the `data-optimize-bg-img` on the video Jumbotron. The Imgix Optimizer uses the parent elements position at the end which set the `<body />` to `position: static` breaking the app banner in Chrome. Moving the jumbotron one element deeper resolves the issue.
**Important:** This must be tested on a real device simulators will not work.
[Preview](https://deploy-preview-1682--int-crds-net.netlify.app/)
[Rally](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F400204708412)
=> DE7872: [rebrand] header doesn't reposition if smart app notification is dismissed on mobile

_includes/home/_our-best-content.html
1. I was told that we display only 3 featured best content items, but I am seeing as many as it's contentful - 6:
2. I should be able to change the order of the items in contentful, and front end should pick up the changed order, but it does not. See image above.
3. All links in that section taking me to oops pages, because they are not pointing to the right place. For example:
clicking/hovering on/around "handling depression..." article points to https://int.crossroads.net/handling-depression-how-to-keep-getting-up instead of https://int.crossroads.net/media/articles/handling-depression-how-to-keep-getting-up 
[Preview](https://deploy-preview-1686--int-crds-net.netlify.app/)
=> DE7909 our best content section

_assets/stylesheets/pages/_kids-club.scss
An `overflow-y: scroll` on `kc-body` was causing a double scrollbar on Chrome using Windows 10. 
[Rally](https://rally1.rallydev.com/#/66096747656ud/custom/24109743995?detail=%2Fdefect%2F403385612096&fdp=true)
Changed `overflow-x:` and `overflow-y:` to `auto` and repositioned images. 
Cannot duplicate on Mac, can only duplicate using BrowserStack.
=> Resolves double scroll and repositions parralax images

_plugins/netlify-plugin-contentful-redirects/index.js, _plugins/netlify-plugin-contentful-redirects/manifest.yml, bin/build-command.sh, bin/contentful-redirects, lib/crds/redirects.rb, netlify.toml, package-lock.json, package.json
Replace netlify-redirector w/ netlify-plugin-redirects
Netlify is reporting invalid redirects for any rules where the source & destination are identical. Further, our redirectURL params need to be escaped because the forward slash is also throwing errors (according to Dennis @ Netlify).
Replace our current redirect script with a [new Netlify build plugin](https://github.com/ample/netlify-plugin-redirects) that does all the things. 
<br>
[<img width="1619" alt="Deploy_details___int-crds-net_and_Deploy_details___int-crds-net" src="https://user-images.githubusercontent.com/50378/88594510-4e110500-d02f-11ea-9f08-66938659dc71.png">](https://app.netlify.com/sites/int-crds-net/deploys/5f1f454d57a3aa0008a31543)
=> DE7889 Invalid Redirects Plugin

_plugins/netlify-plugin-health-check/index.js, _plugins/netlify-plugin-health-check/manifest.yml, bin/build-command.sh, bin/health-check.sh, netlify.toml, package-lock.json, package.json
Last night we had a deployment succeed with a zero-length `_redirects` file which broke a bunch of stuff in production. While this is the first time we've seen this issue and it hasn't occurred since, we'd like to build greater confidence prior to deployment and ensure this doesn't happen again. 
This PR does a few things to address this issue...
1. Refactors the existing health-check script we were using to check the length of `index.html`
2. Updates the plugin responsible for generating `_redirects` so it runs immediately following the primary build command
3. Moves the health-check from the primary build command to a plugin so it runs during the `onPostBuild` event 
You should now see the following output in the build logs, which indicates the presence of critical strings in the …
=> Redirects Health Check

_plugins/netlify-plugin-health-check/index.js, _plugins/netlify-plugin-health-check/manifest.yml, bin/build-command.sh, bin/health-check.sh, netlify.toml, package-lock.json, package.json
Last night we had a deployment succeed with a zero-length `_redirects` file which broke a bunch of stuff in production. While this is the first time we've seen this issue and it hasn't occurred since, we'd like to build greater confidence prior to deployment and ensure this doesn't happen again. 
This PR does a few things to address this issue...
1. Refactors the existing health-check script we were using to check the length of `index.html`
2. Updates the plugin responsible for generating `_redirects` so it runs immediately following the primary build command
3. Moves the health-check from the primary build command to a plugin so it runs during the `onPostBuild` event 
You should now see the following output in the build logs, which indicates the presence of critical strings in the …
=> [hotfix] Redirects Health Check

_layouts/location.html
Removes the facebook watch with us button on location pages
[Preview](https://deploy-preview-1815--int-crds-net.netlify.app/oakley)
=> USXXXXX Remove FB Watch with us btn

redirects.csv
This PR moves the 302s for [forms.crossroads.net](https://forms.crossroads.net) to the top of the `_redirects` file so they are evaluated first. 
This resolves a defect where some users who have an errant `nf_jwt` cookie scoped to `forms.crossroads.net` are being served a personalized homepage (thanks to line 1 of `_redirects`) instead of being redirected. The defect was due to the order in which the redirects were being evaluated by the CDN. 
Let me know if you have any questions.
=> [Hotfix] Update redirects.csv 🔥

redirects.csv
There are some links for online groups in the wild that are directing users to 404s. 
Redirect users to correct path.
=> DE8070 Online Groups

redirects.csv
There are some links for online groups in the wild that are directing users to 404s. 
Redirect users to correct path. 
See #1893
=> [hotfix/release] DE8070 Online Groups

_includes/groups/_meeting-details.html
Fix learn more link
On the updated /groups/onsite/LOCATION pages (ex https://www.crossroads.net/groups/onsite/mason/), the "learn more" and "register" links below each group meeting instance should go to two different places. 
The "learn more" link should go to the meeting detail page (ex https://www.crossroads.net/groups/onsite/fathers/mason/)
The "register" link should go to the registration link defined in the meeting detail in contentful (ex https://www.crossroads.net/sign-up/fathers-pm-mason/) 
=> DE8105 Onsite Group Links

_assets/stylesheets/pages/_onsite-group.scss, _includes/groups/_osg-tabs.html, _layouts/location.html, _layouts/onsite-groups/index.html, _layouts/onsite-groups/location-index.html, _plugins/generators/onsite_groups_generator.rb
On the Onsite Groups landing, please add a tab on the far right (next to the category tabs) that displays the grid of locations that current live at the bottom of the page.
[Design](https://invis.io/6BZOS8ZSE2Y#/441609702_03-01d-Site-Based-Groups-Location)
[Preview](https://deploy-preview-1989--int-crds-net.netlify.app/groups/locations/)
=> US20479 Location Tab

redirects.csv
*Prod /signin page was directed to the Okta signin page (which we don't want yet).*
*Correct /signin page redirect.*
*Once merged, check /signin page in Prod is redirecting to MP siginin page (check that the /oktasignin and /signin page are different)*
=> Reverted /signin to MP signin page

_assets/stylesheets/pages/_superbowl.scss
Too much padding on roster text on mobile
Make padding only show on larger screen sizes
Pull screen from mobile to large to see change
=> remove excessive padding on mobile rosters

_assets/javascripts/components/resi-player.js
Change Resi live stream times for Super Bowl and updated sunday services
From Rally:
(Saturday) Feb 6 - 5pm service time:
stream go live 4:50pm - run untl 6:20pm
(Sunday) Feb 7 - 8:30, 10:30, and 12:30 service times: 
stream go live 8:20am - run until 9:50am
stream go live 10:20am - run until 11:50am
stream go live 12:20pm - run until 1:50pm
=> US20587 Resi Super Bowl Master

_assets/javascripts/components/resi-player.js
Starting Feb 14th, Oakley is adding a service time, so the times are changing for the foreseeable future. They will be 8:30a, 10a, & 11:45a.
I'd like to make the live times:
stream go live 8:25am - run until 9:40am
stream go live 9:55am - run until 11:10am
stream go live 11:40pm - run until 12:55pm
=> US20588 Change Resi Live Stream Times

404.html
Update link to use /help as the root instead of just appending help relative to the path.
Navigate to crossroads.net/oops and click on "help section" link - you will be redirected to https://www.crossroads.net/oops/help, instead of https://www.crossroads.net/help/
Fixed link to be /help instead of help.
Go to https://www.crossroads.net/oops click on the help section link.  It should take you to https://www.crossroads.net/help/
=> Fix oops 404 page help section link.

_includes/groups/_meeting-details-card.html
When editing an Onsite Group Meeting, if the "Room" field is left null, the display on the front end defaults to "online via Zoom." This is not correct behavior. The "online via Zoom" should not display - if the field is left null, nothing should show on the front end.
=> DE8154 Onsite Groups have incorrect default when a meeting room is not selection 

_plugins/filters/onsite_groups_filters.rb, _plugins/generators/onsite_groups_generator.rb, lib/crds/onsite_groups.rb
Stakeholders would like to add multiple locations a single group meeting instance. 
This PR updates the OSG logic to support both single location & multiple locations. The reason I'm handling it in this manner is so we can migrate content from the single-select field over to the multi-select field after we deploy the Contentful migrations to production. After we migrate the data, we should go back and remove the single-select specific logic. 
crdschurch/crds-contentful-migrations#260
[Deployment Preview](https://6040f5176d42c32c19fbddf9--int-crds-net.netlify.app/groups/healing/)
Aside from manual QA at the above URL, the best way I've found to test these updates is to build the project and count the number of files in the `_site/groups` directory. 
```bash
$ find ./_site/groups -type f  | …
```
=> US20708 Onsite Groups

_plugins/filters/onsite_groups_filters.rb, _plugins/generators/onsite_groups_generator.rb, lib/crds/onsite_groups.rb
Stakeholders would like to add multiple locations a single group meeting instance. 
This PR updates the OSG logic to support both single location & multiple locations. The reason I'm handling it in this manner is so we can migrate content from the single-select field over to the multi-select field after we deploy the Contentful migrations to production. After we migrate the data, we should go back and remove the single-select specific logic. 
crdschurch/crds-contentful-migrations#260
[Deployment Preview](https://6040f5176d42c32c19fbddf9--int-crds-net.netlify.app/groups/healing/)
Aside from manual QA at the above URL, the best way I've found to test these updates is to build the project and count the number of files in the `_site/groups` directory. 
```bash
$ find ./_site/groups -type f  | …
```
=> US20708 osg into release

_includes/groups/_meeting-details-card.html, _layouts/onsite-groups/detail.html
When looking at the detail page at the Group-level, for groups with multiple locations, the layout is broken.
Example of how you can find it in the wild:
1. Go to /groups/locations 
2. Click on Uptown
3. If you click on "Learn More" for any of the site-based groups (which are assigned to a single location), you'll see the CORRECT group detail. If you click on "Learn More" next to Grief support in the Healing Groups section, you'll see a busted layout. This group has multiple locations assigned to it. 
[Broken in Prod](https://www.crossroads.net/groups/site-based/alpha) --> [Fixed Preview](https://deploy-preview-2089--crds-net.netlify.app/groups/site-based/alpha)
=> DE8198 fix group detail into dev

_assets/stylesheets/_fonts.scss, redirects.csv
Traffic pointed at `/articles` was 302 redirecting to `/media/articles`. The organization
wanted those redirects has 301 redirects.
The `redirects.csv` file has been updated to redirect all traffic coming
in at `/articles` as a 301 to `/media/articles`.
There is no corresponding branch associated with this work.
To test, open your inspect tools, go to the network tab, then navigate to an article (e.g. int.crossroads.net/articles/10-minutes-to-more-hope-advent-week-1). You should see 2 requests for 10-minutes-to-more-hope-advent-week-1. The first should resolve as a 301 redirect, _not a 302 redirect_. The second request should resolve to /media/articles/10-minutes-to-more-hope-advent-week-1 as a 200.
=> Feature/US20639 Update media 302 redirects

Gemfile, Gemfile.lock
Currently the website title is not structured the way the insights team would prefer. For some articles, the title is missing "| Crossroads Media" after the name of the article.
Adjustments were made to the `jekyll-crds` library and a bugfix version was released. This pull request updates the `Gemfile` to point to the most recent bugfix version (2.3.2)
There is a corresponding branch on the `crds-media` project:
https://github.com/crdschurch/crds-media/pull/1147
Previously the `/media/articles/asian-stereotypes-silence-is-complicity` article was not rendering the title correctly. Now you should be able to go to https://int.crossroads.net/media/articles/asian-stereotypes-silence-is-complicity, hover over the browser tab and see a title format of "Article Title | Crossroads Media"
=> feature/US20909 Fix Site Title

_includes/_meta-tags.html
Because of the new Google and Apple privacy things, FB is making us verify our URL.
It is asking to include the meta tag to the homepage. 
`<meta name="facebook-domain-verification" content="n8c17x6iuikwwrvdt4f80xwr72ql8t" />`
[Asana](https://app.asana.com/0/1198951831278010/1200235128591069)
=> Adds updated facebook meta tag

_layouts/established.html
[Established] subnav - we have to fix the design. it's too close to the jumbotron as well. 
[Asana](https://app.asana.com/0/1199580851373247/1200290763427499)
##Solution 
Added `soft-top` and `push-top` to create space between the jumbotron and `crds-tabs` component.
=> Adds padding-top and margin-top to crds-tabs component

_assets/javascripts/components/resi-player.js
May 22/23 weekend is our 25th Anniversary celebration and we're adding a service on Saturday in order to make room for people that weekend. Just want to get it on your radar. I also would like to extend our end time an additional 5 minutes on this weekend (just in case). 
Here's the schedule:
May 22:
5pm service
stream go live at 4:55pm - run until 6:15pm
May 23:
Normal service times, but I'd like to add 5 minutes on the end for run times...
stream go live 8:25am - run until 9:45am
stream go live 9:55am - run until 11:15am
stream go live 11:40pm - run until 1:00pm
The following weekend, we'll resume back to only Sunday streaming times. Thanks all, and let me know if you have any questions. 
https://deploy-preview-2246--crds-net.netlify.app/oakley
=> US21034 Resi Times

_includes/_head.html
Removes Osano from `/atriumevents` pages.
[US21035](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fuserstory%2F602981034164)
[Preview Link](https://us21035-int--int-crds-net.netlify.app/atriumevents/?site=east%20side)
=> US21035 Osano Remove Cookies Ask From /atriumevents Pages

_includes/home/_jumbotron.html
Grid overlay showing default image. (You will only see this issue when the video is not on the page yet)
Change class from `grid-overlay` to `grid-overlay-light` because the light image does not have this issue
=> Fix HP grid overlay image issue

_assets/stylesheets/components/_jumbotron.scss
[Rally Task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fuserstory%2F492688786312)
Set jumbotron video containers to `display: none` below `$screen-xs` (480px).
On homepage
=>  Hide Jumbotron Videos on Mobile

_includes/_head.html, netlify.toml
Our previous implementation of gtag.js was resulting in double reporting to google analytics
This code removes the code that renamed all the references to `ga()` to `gtag()`.
No corresponding branches.
This will be done manually by inspecting realtime traffic to our google analytics instance.
=> Remove onPostBuild hook to rename ga references

_assets/javascripts/components/jumbotron-video.js, _assets/stylesheets/components/_jumbotron.scss, _includes/home/_jumbotron.html
PR #2329 hides the video container on mobile but does not prevent video from loading in background. It also hide the inline-video and controls after user clicks the in-jumbotron play button.
- Remove `close-video` and `inline-video-player` from `display: none` list
- Handle video loading in javascript:
- the video `src=""` attribute is now `data-src=""` by default and won't load the background video
- An event listener tracks the 480px media query
- When the page is above 480px, `data-source=""` changes to `src=""` and the video loads
- `src=""` changes back to `data-src=""` when the page crosses below 480px and the video unloads
PR #2329 which was previously merged into `development`.
Test the home page below and above 480px wide. 
- Starting below 480px, the source file …
=> US20611 Hide Jumbotron Videos on Mobile - pt 2

_assets/stylesheets/components/_jumbotron.scss
[Rally Task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fdefect%2F603091758495)
This bug appears on both mobile ask desktop. On desktop, the top of the video is cut off by the navigation as well.
Add top margin to `.close-video` and `.inline-video-player` to compensate for existing `top: -1.5rem` value on jumbotron container. (Removing the negative positioning value on the  jumbotron impacts other content, not just the inline video, so I left that value as-is.)
Location: Jumbotron on the home page 
Click on the play button inside the jumbotron to view the inline video player. The nav bar no longer covers:
- The close button on mobile
- The close button and top of video on desktop
The breakpoint between mobile and desktop values is at `$screen-sm` (768px).
=> DE8434 Jumbotron Video Close Button Spacing

_layouts/author.html
Currently some authors' bios are not displaying correctly.
By assigning the author to the page variable in the author.html layout, author information is now displaying correctly for previously broken author profiles without negatively affecting previously working author pages.
No corresponding branches
Do a spot check of various authors, ensuring you also view the page for author Allie Janszen.
=> Fix author bio and image

_layouts/established.html, _layouts/frontier.html
"If there is a featured promo only show 5 and then View More to expand others"
previously I had hard coded locations with monetate content to auto display all happenings. However they will not be using monetate content on the locations pages in the future, so this is now keying off of a "hasPromo" prop and is now dynamic
[Asana Task](https://rally1.rallydev.com/#/66096747656d/dashboard?detail=%2Fuserstory%2F600916034915)
=> Testing Bugfix - Defect/us21210 view all happenings

_layouts/established.html, _layouts/frontier.html
Images for the Ministry Leader Image on location pages was broken.
I removed the extra url parameters and removed the data-optimize-imgix attributes from the constructed url.
Visit /georgetown and /eastside and confirm that the youth ministry leader image is visible.
=> Remove imgix optimizer attributes

_layouts/author.html
Under the messages tab on an author's page, the titles were the same for all messages.
I changed `video.title` to `message.title` in the author.html layout. 
Visit any author's page, click the "messages" tab, and confirm that all the messages don't have the same title.
=> Change video.title to message.title

_includes/groups/_meeting-details.html, _layouts/onsite-groups/location.html
[Rally Task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fdefect%2F508478843188)
I updated the "Title" and "Learn More" links to use `page.location.slug` instead of the `meeting.location.slug`. 
Right now each meeting includes a `locations` array with all possible locations for a meeting. The `meeting.location` object is assigned to the first alphabetically instead of matching the page it was called from. (See screenshot below, rendered on the "Dayton" page.) I'm not sure if this is something that needs to be fixed.
`Meetings` data is being assigned here:
https://github.com/crdschurch/crds-net/blob/5de7a8eee8572f5240b90ce839bbd8d4b0b91ad3/_plugins/generators/onsite_groups_generator.rb#L38
Links are updated in each location's page inside `/groups/locations/`. …
=> Fix group meeting links on meetings that have multiple locations

_assets/javascripts/components/flickity-display.js, _assets/javascripts/config.js, _assets/stylesheets/components/_flickity-display.scss, _assets/stylesheets/components/_modules.scss
[Rally task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fdefect%2F489063345032)
- Hide Flickity cells until javascript is done loading to prevent them from initially displaying vertically 
- Set cursor to `auto` instead of `grab` on Flickity viewport 
- These changes impact all `.card-deck.carousel` and `.carousel-cell` classes on the site. (Container classes for Flickity carousel.)
/live 
See the grid/carousel under the "happening at crossroads" header. On page refresh, the cells should not load vertically and are hidden until the grid is ready. On hover, the cursor is either the `default` cursor or `pointer` on links.
=> Update Flickity Carousel on /live

_assets/javascripts/components/pagination.js, _includes/_pagination.html
Pagination input field allowed negative values on /media/articles
Add an event listener and checks on keystrokes to prevent the input of anything other than positive numbers in the pagination input field.
No corresponding branch
Navigate to https://6148bc3e9fd22934197af791--crds-net.netlify.app/media/articles/ to see a deploy preview. Try typing letters and characters that aren't numbers in the input field to confirm that they do not appear. Click the up and down arrows in the input field to confirm that you can't navigate to negative numbers.
=> Add check for keys that should be blocked for pagination input

netlify.toml, redirects.csv
online registrants are being redirected to crds-net and not church online after account activation.
redirect based on cookie presence  will allow for said users to be properly redirected.
/auth-redirect branch see also [this pr](https://github.com/crdschurch/crds-online/pull/342) and t[his pr](https://github.com/crdschurch/crds-components/pull/1450)
Testing will require a user to register on Church Online, activate their email and see if redirection is to Church Online Sign in vs. crds-net signin
=> add redirect for online registrants

media/index.html
Newsletter sign up not longer wanted on media index page
Removed _includes file that placed the signup on the media index page
No corresponding branches
Go to /media and confirm the newsletter signup component is no longer present on the right side of the page.
=> Remove hubspot newsletter signup on media index

_includes/_pagination.html
Pagination on Humans of Crossroads was broken. Each time the "Load More" button was clicked, the same set of articles was loading.
A portion of code was accidentally bypassed that provided the requisite `ul.pagination` element when a previous pagination feature was merged. This code restores the presence of the `ul.pagination` element when `n_of_total_pagination` is not getting used.
There are no corresponding branches with this work.
Navigate to /media/articles and confirm pagination is working there.
Navigate to /media/humans-of-crossroads and confirm pagination is working there
Navigate to any other locations you are aware of pagination being present and confirm it is working correctly.
=> Remove else clause to give access to ul.pagination element in all pagination clauses

_layouts/article.html, _layouts/collection.html, _layouts/episode.html, _layouts/humans-of-crossroads.html, _layouts/message.html, _layouts/podcast.html
[US21920](https://rally1.rallydev.com/#/?detail=/userstory/618238142281&fdp=true): [Segment] Review Content Groupings for Topics & Types
Add correct attributes for GA content groupings to media layout pages
=> US21920 Content Grouping

_assets/stylesheets/pages/_articles.scss
[DE8778](https://rally1.rallydev.com/#/?detail=/defect/618250903277&fdp=true): Social icons are overlaying the hero image
[Deploy Preview](https://61a918e3210814717c044c61--int-crds-net.netlify.app/media/articles/two-soldiers-down)
=> DE8778 Article Social Icons

_layouts/collection.html
On shows with trailer - when I X out of the modal, the video sound still plays
[DE8872](https://rally1.rallydev.com/#/?detail=/defect/626546433481&fdp=true): Video sound plays after the modal is closed
=> DE8872 video on modal close

README.md, bin/build-command.sh, bin/logzio.sh
This PR removes Logzio references to prevent continued shipping of logs
to the Logzio service.
=> US21913 Remove logzio from crds-net

_assets/javascripts/components/resi-player.js
On Feb 10, 2022 we adjusted the service times defined in the `_assets/javascripts/components/resi-player.js` file to support service times for the Super Bowl of Preaching. Now that the Super Bowl of Preaching is over, this PR reverts those changes.
=> US22165 Revert service times to pre-SBOP

_assets/stylesheets/pages/_video.scss
On video pages with the meter modal, the content will display on the page before the page fully loads.
[Asana Task](https://app.asana.com/0/1201454665996628/1201755178268983)
Hide the content until the modal is hydrated.
[Preview](https://deploy-preview-2550--int-crds-net.netlify.app/media/videos/3-35-stitches)
=> Meter modal glitch

redirects.csv
Redirects need to be handled when coming from `crds-online` for the unified platform.
- Added a redirect rule for `CRDS_ONLINE_DOMAIN` which currently uses the `crds-online` deploy preview
- Logged-in users will be redirected to `/online`
- Logged-out users will be redirected to `/online/getstarted` (functionality may not work until after merge)
[Deploy Preview](https://deploy-preview-2551--int-crds-net.netlify.app/online)
Online PR: [https://github.com/crdschurch/crds-online/pull/552](https://github.com/crdschurch/crds-online/pull/552)
=> Modify user landing page based on auth

redirects.csv
The current `Continue as guest` button on the logged-out homepage will not redirect properly based on the new landing page auth system.
Add a cookie-based redirect for `/online`
=> Add cookie redirect for /online guests

redirects.csv
https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fdefect%2F624270329681&fdp=true
Problem:
The current redirect from https://www.crossroads.net/live/stream is improperly delayed, and Crds data team is still seeing user behavior traffic on old pages from that section.
Request:
Instantly redirect all user traffic from www.crossroads.net/live and /live/* to https://online.crossroads.net
Acceptance Criteria:
Given I am a website visitor
When I navigate to https://www.crossroads.net/live or https://www.crossroads.net/live/stream
Then I will immediately see https://online.crossroads.net load
A wildcard was not redirecting routes under /live/
updated redirects.csv to include a wildcard redirect for /live/*
visit /live/stream on testing site
=> add wildcard redirect for /live/

redirects.csv
Online church catch all redirect currently going to a page named with a test url, the redirect needs lil update.
=> update catch all redirect for online church urls.

_assets/javascripts/components/resi-player.js, index.html
Update Resi Player for Easter services
Needs to go up on Saturday at 2:55 and go away on Sunday at 1
Also a space for a content block that will take over the current series section. This content block will be scheduled by AG to go live at 8am on Sunday
Test the [deploy preview](https://deploy-preview-2594--crds-net.netlify.app/oakley) by changing your date and time on your machine to the service times
=> US22369 Resi Easter Service

_includes/_head.html
This PR gives Devy the ability to specify URLs to the crds-components library directly in the CMS so they can test authentication on a specific page, without disrupting other routes.
=> Do not load components in _head.html if they're defined in the CMS

_assets/stylesheets/pages/_homepage.scss
This background image on the Logged Out Homepage does not properly resize when you change the viewport size
DE8961 https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fdefect%2F639629882907
The css class .home-jumbo-rel with the background-size: cover; needed a bg position of:
background-position: center;
Deploy Preview: 
https://62a09201439cff03f714fc09--int-crds-net.netlify.app/
Currently the INT and Prod deploys have different content for the affected backgrounds. The Int deploys show a topographic map image. It now centers on smaller screens. Note that the cover size scales vertically and/or horizontally to cover the entire container background. This update makes it center. 
=> add center to home-jumbo-rel bg image

_assets/javascripts/lib/distance-sorter.js
Remove geolocation browser prompt from /locations page load
remove call to function in init
remove-locations-geolocation
https://629fc3e1a21d4d0067bf602d--int-crds-net.netlify.app/locations
When testing be sure to watch the url if clicking through site, as you'll often end up off this branch build. This PR refers to the /locations page.
=> remove geolocation from locations page load

redirects.csv
Redirect from crds-net to crds-unified was missing a slash
Add slash before `:splat` so the redirect works properly
=> [Defect] Unified Redirect 

_assets/stylesheets/pages/_humans-of-crossroads.scss
Broken image on https://www.crossroads.net/media/humans-of-crossroads/ needed restored
Replaced URL w/ an intact version of this image from the similar https://www.crossroads.net/media/topics/humans-of-crossroads
Given I am a user
When I visit https://www.crossroads.net/media/humans-of-crossroads/
Then the main bg image will match https://www.crossroads.net/media/topics/humans-of-crossroads
=> Restore Humans of Crossroads BG image

redirects.csv
Redirect not working for the desired urls
Remove it because it's not needed in this capacity
N/a
Make sure site doesn't explode when the redirect is removed. It wasn't working anyway, so no functionality for removal needs to be tested.
=> Remove redirect for Crds-Unified

_includes/_bitmovin-player.html
*Single quotations in recommended collection and timestamps for messages would cause the page to not display any video for the bitmovin component*
*Escaped special characters in those fields when creating the component*
=> Escaping special characters for reccomended collection and timestamps

_plugins/generators/sorted_podcasts_generator.rb
Marketing wants the 'Crossroads Messages' podcasts in position number one. 
Make 'Crossroads Messages' show up first.
[Deploy Preview](https://deploy-preview-2678--int-crds-net.netlify.app/media/podcasts/)
---
- https://app.asana.com/0/0/1202670799550093
=> Move 'Crossroads Messages' podcast to the front of the list

_includes/_head.html
IDT wants to include entry IDs in Contentful with Segment events so we need to expose that value on the page. 
This PR exposes a new metatag in the page's header so we can grab this value in GTM when sending in events
=> Expose contentful entry IDs via meta-tags

_includes/_columbus-top-section.html
-Replaced "Get to know us in 7 days" modal at the top with "address"
-Moved address code from "Next in person gathering" to "address"
-Removed "Currently looking for new digs to house our ever-growing {{ page.name }} community."
=> Updates to the location-info-row

Gemfile, Gemfile.lock
We need to reduce the number of items per page in our Contentful queries. This PR updates the version of `jekyll-contentful` to its latest to reduce the page number from 500 to 250.
=> Bump jekyll-contetful to its latest

_layouts/anywhere.html, _layouts/established.html, _layouts/frontier.html
Promos on location pages are currently sorted by `date` field
Sort the promos by `published_at` instead
Check the location pages and confirm that the promos under `events & updates` are sorted according to the `published_at` field.
Example from the Eastside page:
=> [Hotfix] Sort promos by published_at

Gemfile, Gemfile.lock, _config.yml, package.json
**1. Max length issues**
The depth of some of our content models is causing Contentful to throw max-length errors for articles & series content. We can work around this issue with minimal risk by reducing the number of entries returned per page (from 1000 to 250). This is a good quick fix but results in a much larger number of queries.  
**2. Verbosity**
Sometimes Netlify truncates the build logs which can make troubleshooting challenging. So we need to reduce the verbosity of our build output to the smallest possible amount.  
This PR bumps `crdschurch/jekyll-contentful` to version 3.3.0 which provides new options to specify items per page on a per content-type level and reduces verbosity. 
---
- …
=> Bump version of jekyll-contentful and adjust queries to reduce number of requests

_assets/stylesheets/_fonts.scss, _config.yml, _includes/_media-card.html, _includes/_media-label.html, _includes/_overlay-card.html, _layouts/tag.html, _plugins/generators/song_album_generator.rb
Tag landing pages associated with the 7 proven practices are not showing certain types of content.
Update so all content types can populate the pages.
In Contentful, use the tag content model to assign practices to content and confirm that any of these content types are able to populate on the given page (I used Share Your Story for testing):
Album 
Article 
Episode 
Message (live and online)
Podcast 
Series 
Collection (including Show and Next Level)
Song 
Video 
https://deploy-preview-2732--int-crds-net.netlify.app/media/tags/share-your-story/
---
- https://app.asana.com/0/0/1203166629225652
=> Add missing content types to tag landing pages

redirects.csv
redirects are 301 instead of 302s
made them 302s
merge to development 
while not signed in & view the growth path page or any of the pillar set a goal pages
you should be redirected back to signin
if you are signed in you should not be redirected to signin & should be allowed to stay on those pages
---
- https://app.asana.com/0/0/1203374479811215
=> Alter Redirect Status

_layouts/series.html
on /media/series/{series-slug}
we want Online to say Full Service & show live messages content below
we want At Sites to say Message Only & show "online" messages
"online" is going to be converted to show shortened live messages in the future
[Task Link](https://app.asana.com/0/1201454420722044/1203365469722789/f)
did that
pull down locally & verify changes are correct & work as described in the problem statement
or 
merge to development & verify changes are correct & work as described in the problem statement
=> Weekly Teaching Updates

redirects.csv
We dont want to utilize nf_jwt for tracking authentication on unified, the routes here are currently being proxied to show a user the auth block pages based on nf_jwt.
removed role user from unified routes
removed redirects to signin from auth blocked pages because this file has no concept to determine if we are logged in now
---
- https://app.asana.com/0/0/1203331084606721
=> Remove Role=user from Unified Routes

_includes/_head.html, _plugins/filters/chomp.rb
The SEO nerds want canonical link tags on every page. Today, we're only rendering these tags when there is [more than one distribution channel](https://github.com/crdschurch/crds-net/blob/master/_includes/_head.html#L43-L49).
This PR adds canonicals to all non-distro channel pages.
You're looking for the following convention in the page's source... 
Some examples... 
* https://deploy-preview-2756--int-crds-net.netlify.app/media/
* https://deploy-preview-2756--int-crds-net.netlify.app/media/videos/get-to-know-alli
* https://deploy-preview-2756--int-crds-net.netlify.app/media/videos/get-to-know-alli
* https://deploy-preview-2756--int-crds-net.netlify.app/media/podcasts/spirit-stories
* https://deploy-preview-2756--int-crds-net.netlify.app/spiritual-outfitters/
* …
=> Add canonical link tags to non-distro channel pages

redirects.csv
Reverts crdschurch/crds-net#2741
Temporary revert to have crds-unified in a properly working state while we adjust the authentication modifications on that external repo.
=> Revert "Remove Role=user from Unified Routes"

_plugins/generators/env_generator.rb
crds-net was not outputting `crds_env` or `contentful_env` variables, which are needed to populate the alerts bar.
Add the missing variables to the EnvGenerator.
- See the deploy preview or check out the branch & run locally
- Ensure that you have the two variables above defined in your `.envrc`
- Confirm that you can see alerts on .net pages such as /oakley, /media, etc.
=> Add missing env var config

redirects.csv
Swaps Growth Path page redirects so that the default page is logged-out & redirects to the logged-in version if Role=user. The rationale here is that the homepage links directly to the logged-out version and will standardize the url for users regardless of auth status.
=> Swap growth path redirects

_assets/javascripts/components/resi-player.js
There are no service times for xmas
remove services times this week
change date to sunday between 8:25 am & 1pm 
you should not see the live stream player
=> xmas 2022 remove services times | demo

_layouts/series.html
[Asana Card](https://app.asana.com/0/1201454665996628/1203674525880237/f)
- Change tab label on Services template from "Live Service" to "Full Service"
[Deploy Preview](https://deploy-preview-2829--int-crds-net.netlify.app/media/series/god-stories)
This change should apply to all `/series` pages.
=> Full service label

redirects.csv
we are no longer going to be proxying rock pages
removed all proxy redirects
going to demo.crossroads.net/{insert rock page url} should result in a 404 oops page & one should instead visit 
rockdev.crossroads.net/{insert rock page url}
=> remove all rock proxies

_layouts/series.html
The Full Service tab was not showing videos on the series pages.
Update the slot name to reflect the existing naming convention so that videos populate that tab.
https://deploy-preview-2833--int-crds-net.netlify.app/media/series/god-stories
---
- https://app.asana.com/0/0/1203802000082757
=> [Defect] Series landing page not showing full services

_includes/_gtm-head.html, _includes/_gtm_noscript.html, _includes/_head.html, _layouts/default.html, _layouts/default_footer_flush.html, _layouts/no-header-no-footer.html
Loading GTM directly via googletagmanager.com is problematic as certain browsers are blocking 3rd party requests. Thus, we want to load GTM via 1st party hostname, so we need to load GTM as a destination of Segment. 
Replace GTM snippet with a new Segment source which loads GTM as a destination. This allows GTM to function as it always has but makes it load via CDN proxy analytics.segment.crossroads.net so its not considered a 3rd party request. 
- https://github.com/crdschurch/crds-unified/pull/369
- https://github.com/crdschurch/crds-net/pull/2763
...TBD
=> Replace GTM w/ Segment

_layouts/series.html
If only one message video is present, only that video/tab should be shown on the series detail page.
If there is only one video, confirm that only the tab for the existing video shows and center that video card.
Option 1 (Contentful): In `int` Contentful, unpublish either the Full Service or Message Only video on the latest series (or whatever series is being shown in that environment).
Option 2 (local): 
Pull down Contentful
Find the latest _series in collections directory and comment out/delete the videos or live_messages
Run crds-net server
See the changes reflected on /watch. You should only see the videos that exist for that series.
https://deploy-preview-2838--int-crds-net.netlify.app/media/series/god-stories
=> Account for one message video on series detail page

redirects.csv
Adds a redirect for practice tag index pages (such as `practice/share-your-story`).
=> Add redirect for practice index pages

_assets/stylesheets/_fonts.scss, _assets/stylesheets/pages/_articles.scss, _layouts/article.html
On article pages, titles were using `h2` tags and the footer CTA text was using `h1` tags which is not ideal SEO.
- Change article title elements from `h2` to `h1`
- Change Jumbotron CTA from `h1` to `h4` (`h2` and `h3` are already being used well semantically based on the page context)
- Also add styling to ensure the appearance stays the same regardless of tag name
Check that article titles and the footer CTA text are using the correct tags as described above
---
- https://app.asana.com/0/0/1204179871685798
=> Footer CTA fix for Articles 

_assets/javascripts/components/analytics.js, _assets/javascripts/config.js
This reverts commit af2af373729b76fc7f4e43831c2d97e966c245a7.
Dave had asked us to nullify user_ids prior to the Rock cutover. This commit was designed to reset user IDs but that may be contributing to some odd behavior that Insights has been troubleshooting. 
Now that we're on the Rock officially, I'd like to revert this change to reduce the factors.
=> Revert "Reset user_ids for Segment migration plan"

_assets/javascripts/components/resi-player.js
The resi player should be visible during these times:
- Friday 4/7 between 7:00pm - 8:20pm
- Saturday 4/8 between 3:00pm - 6:30pm
- Sunday 4/9 between 8:30am - 2:00pm
Also updated the refresh intervals for the start and end of each of these livestream periods.
=> Update Easter resi player times

_assets/javascripts/components/resi-player.js
resi player should show during horse service times
Sat, 4/22 between 3pm - 6:30pm
Sun, 4/23 between 9am - 5pm
Added service times
update date time on computer before during after service times to see the resi player show hide accordingly
=> add horse weekend times

_layouts/anywhere.html
Replaces the Okta form on the /anywhere page with a link to register in Rock.
`int` and `demo` will link to `mydev.crossroads.net`, and `prod` will link to `my.crossroads.net`.
=> Replace form with link to Rock signup

_includes/_head.html
The title on the `/media/articles` page was too long and was causing SEO ranking issues for articles. Removed `| Crossroads Church` from the formatted title for Articles only
Add a condition to check if the formatted page title in `head.html` will include `Articles`. If it does, don't add `| Crossroads Church`
=> Remove "| Crossroads Church" from title on /media/articles page

_includes/_head.html
Addressing a request to remove ` | Crossroads Church` from article titles. Both the articles landing page and each individual article.
Provide conditional logic to only render the page title instead of the meta title for artlces.
---
- https://app.asana.com/0/0/1204523718827565
=> fix for articles titles

_layouts/anywhere.html, _layouts/established.html, _layouts/frontier.html
Remove mention of current series from location pages
Change copy and logic on location templates to show the most recent message instead of the most recent series.
Changes were made in the following templates:
- `anywhere.html`
- `frontier.html`
- `established.html`
---
- https://app.asana.com/0/0/1204758025493765
=> change copy for current message and logic for current message

_layouts/default.html, _layouts/default_footer_flush.html, _layouts/no-header-no-footer.html
we have a free widget that we want to deploy on demo but no where else
added conditional check for jekyll_env to conditionally render script tag or not
locally youll need to have this line defined in your .envrc file
```bash
export JEKYLL_ENV=production
```
direnv allow
run project you should not see any userway widget displayed
```bash
export JEKYLL_ENV=demo
```
direnv allow
run project you should see the userway widget displayed
=> add userway widget to crdsnet pages

_includes/_locations-grid.html, redirects.csv
we need to be able to decommission locations & maintain their happenings but remove them from /locations page
added new field to filter by on /locations
updated /georgetown to /georgetown-decommissioned
added a redirect from /georgetown-decommissioned to /georgetown
added helper text in contentful field to try to document issue for content admins
given you have a page created to handle the decommissioned location like this one
https://app.contentful.com/spaces/y3a9myzsdjan/environments/demo/entries/4TLuytPG4ht34pCd8syY8v
mark a location as decommissioned & update its slug to include "-decommissioned" at the end of it like so
https://app.contentful.com/spaces/y3a9myzsdjan/environments/demo/entries/5dUYaUyMwgWUC6AyKkckU0
add a redirect in contentuful for your from the location slug to the …
=> filter out decommissioned locations

media/topics.html
With category content type being used for topics and video shorts now, we needed to implement a way to filter out excluded categories.
[Task](https://app.asana.com/0/1201454420722044/1205173108415310/f)
Add a condition to the existing if statement to filter out any category that has excluded set to `true`.
There are currently 4 excluded categories. (excluded set to true). 
- [Crossroads Music](https://app.contentful.com/spaces/y3a9myzsdjan/environments/demo/entries/51MVLD7HZ3AtThu70TmmWI)
- [Crossroads](https://app.contentful.com/spaces/y3a9myzsdjan/environments/demo/entries/4KIciGti4VXjUesihtnGEJ)
- [Student Ministry](https://app.contentful.com/spaces/y3a9myzsdjan/environments/demo/entries/45GgGf0SqOhhhmBvaVXazl)
- [Kids'Club](https://app.contentful.com/spaces/y3a9myzsdjan/environments/de …
=> add condition to filter out excluded items

redirects.csv
we have registration link that is not being redirected to new registration page
add redirect to handle this situation
navigating to /register should navigate you to my.crossroads.net/NewAccount or mydev.crossroads.net/NewAccount depending on the environment you are on
=> add redirect for registration

_layouts/message.html
The goal was to link a song on the message detail page (in or near the description section). We couldn't add this to the description body because it would show up in other places like the /watch page.
Created a new field on messages called `worshipSong` that gets rendered only on the message detail page.
Contentful entry with a Worship Song added: https://app.contentful.com/spaces/y3a9myzsdjan/environments/demo/entries/228a47KRO5jSZEOtFs9laF
---
- https://app.asana.com/0/0/1205366657186148
=> Add worship song section to messages

_includes/_bitmovin-player.html
There is currently no video identification passing to the bitmovin player on crds-net that would be captured in analytics. 
update the variable that we use and method to use the contentful id.
=> remove the .sys from the video-id reference.

lib/crds/redirects.rb
We need the ability to create a proxy for flex pages in Contentful as they get created.
Update `redirects.rb` to fetch all flex page entry slugs, then insert them into `redirects.csv` in addition to the existing redirect entries.
- View any Contentful flex page in demo and note the slug field for that entry.
- You should be able to visit that url (aka not get a 404 page) by adding the slug to the deploy preview url. This means the redirect was created successfully.
- For example, the slug `/test-flex-page` is viewable at https://deploy-preview-3172--demo-crds-net.netlify.app/test-flex-page
To test the redirects file directly:
- Pull down this branch locally and fetch the latest `demo` entries from Contentful
- Run this command to build `redirects.csv`:
```
ruby bin/contentful-redirects …
```
=> Add Flex Page Proxies dynamically within crds-net

redirects.csv
Revert `/happy-thanksgiving` redirect so that temporary thanksgiving campaign can be live in prod.
This link should go to [Registering Your Box](https://crossroads-3993985.hs-sites.com/thanksgiving-food-drive-box-registration) until Nov 13:
https://deploy-preview-3183--demo-crds-net.netlify.app/happy-thanksgiving
=> Revert  Thanksgiving Redirect

redirects.csv
Given I am a CR community member
When I navigate to Crossroads.net/mycamps
Then I will have the same experience as when I navigate to My.Crossroads.net/mycamps.
=> Added redirect for mycamps to rock domain

_includes/_livestream.html, _includes/_resi-player.html, _layouts/anywhere.html, _layouts/established.html, _layouts/frontier.html, _plugins/hooks/livestreams.rb
The goal is to use the Livestream model in Contentful to manage livestream events
- Fetch livestream JSON from `crds-data` and append to `site.data`
- Add a script that determines whether a livestream should show
- Include the script on all location pages
https://github.com/crdschurch/crds-unified/pull/1129
- Create or modify a livestream entry in Contentful
- Based on the datetime and page selections, the livestream should only show during those times/on those location pages
https://deploy-preview-3208--demo-crds-net.netlify.app/
=> Add livestream toggle to location pages

_layouts/collection.html
Crossroads would like content block to the right of the text block removed from the real encounters page.
Remove the content block, widen the column's the text consumes, and center the text.
- Go to the /media/collections/realencounters page and verify that the text blocks appears in accordance with the clients request.
---
- https://app.asana.com/0/0/1206200107653384
=> Realencounters updates

_includes/_head.html
Sets `crds-components` back to prod
=> Revert "Temporarily use demo crds-components"

netlify.toml
Netlify is forcing all plugins to run on Node 20.
They notified us that one of our plugins will be effected,
---
- https://app.asana.com/0/0/1206408373230426
=> Remove health check plugin from `netlify.toml`.

_layouts/article.html
The hubspot form on article pages is no longer needed.
Remove link in article.html file that displays that hubspot form
No corresponding branches
Randomly select 4 articles on the article index page and confirm that none of them have the hubspot form on the page anymore.
---
- https://app.asana.com/0/0/1206612801710180
=> Remove hubspot form from the article page.

_layouts/podcast.html
Spotify link showing bad url
Point link to correct contentful field in the `_layouts/podcast.html` file.
Navigate to a podcast with a spotify url and confirm the button displays and is pointing to the correct source.
---
- https://app.asana.com/0/0/1206868528794538
=> Fix incorrect link to spotify url

_assets/stylesheets/pages/_message.scss, _assets/stylesheets/pages/_modules.scss, _layouts/message.html, index.html
Message videos don't currently allow for Spanish video source.
On a message detail page, if there is a source_url_spanish provided in Contentful, the video jumbotron will now show a button to "Ver en Español".
https://github.com/crdschurch/crds-components/pull/2085
https://github.com/crdschurch/crds-unified/pull/1382
Go to a message in contentful, provide a value in the Source Url Spanish field, navigate to that message, and confirm that the page shows the button, and that the button switches the video source.
=> Feature Spanish Video Player

_includes/_subscribe-buttons.html, _layouts/podcast.html, _layouts/series.html
Extraneous events found in Segment seem to be caused by elements having an onClick event in addition to an upstream GTM event on the same trigger. Most of these events were related to outbound links on Jekyll pages, which have an onclick `ContentEngaged` event in the code but a `LinkClicked` event in GTM. 
Removing the `ContentEngaged` gets rid of the extraneous event in Segment. `LinkClicked` still fires as it did previously.
These primarily came from social share buttons on media pages. Test those and confirm that you don't see any extraneous events appear in Segment. Example pages:
https://deploy-preview-3313--demo-crds-jekyll.netlify.app/media/podcasts/messages
https://deploy-preview-3313--demo-crds-jekyll.netlify.app/media/series/test-student-ministry-series3/test-future-message-josh
=> Fix for Extraneous Events in Segment

_config.yml, _includes/_columbus-top-section.html, _includes/_location-card.html, _includes/_location-info.html, _layouts/location.html, _plugins/generators/location_service_times.rb
service time variable name got normalized and conflicted with the app service time names causing them to not show up on the locations pages. 
Update the name to be unique from the app service time names
[crds-unified]()
=> update service times to use 'reference' prefix.

_layouts/anywhere.html, bin/update-image-urls.sh
The topo image at the bottom of the /anywhere page was not loading due to how imgix query params were being handled for background images.
Change the `update-image-urls` script to better handle query params for background images.
https://deploy-preview-3332--demo-crds-jekyll.netlify.app/anywhere
Make sure all existing images are loading correctly in addition to the one that was fixed.
=> Fix /anywhere topo bg image

_assets/javascripts/components/chat.js, _layouts/anywhere.html, bin/update-image-urls.sh
[Asana Task](https://app.asana.com/0/1201454420722044/1206558274609681/f)
- Adds alternative functionality to the "Chat with us now" button on the /contactus page. The button will result in a mailto action if:
- `window.Intercom` is undefined (meaning the script did not initialize), or
- The `.intercom-launcher` class is not present on the page
https://deploy-preview-3340--crds-jekyll.netlify.app/contactus/
- Visit the testing link in a private/incognito window
- Click "deny" on the cookie consent banner (may take a few tries to reproduce)
- Assuming the chat widget does not appear on the bottom right, click "Chat with us now" and ensure that an email client opens which is directed to [hello@crossroads.net](mailto:hello@crossroads.net) 
- If the chat widget DOES appear, the expected …
=> [Demo] /contactus alternative chat button functionality

_layouts/series.html, _layouts/video.html, _plugins/generators/student_ministry_series_videos.rb
[Asana Task](https://app.asana.com/0/1201454665996628/1207432108755913/f)
Shouldn't the "media" stay "student ministry' so the breadcrumb from [this page](https://demo.crossroads.net/student-ministry/series) to [this page](https://demo.crossroads.net/media/series/test-student-ministry-series3) is a build up? so on that second page the breadcrumbs would be "Student Ministry / Series /"
[Student Ministry Series](https://deploy-preview-3350--demo-crds-jekyll.netlify.app/media/series/student-test-series-with-videos)
Also updated the breadcrumbs on the video layout if the video is associated to a series that is a flagged with (Is Student Ministry Series)
[Student Ministry Series Video](https://deploy-preview-3350--demo-crds-jekyll.netlify.app/media/videos/when-we-dont-know-how-to-pray)
=> Update student ministry breadcrumbs

_layouts/series.html, _layouts/video.html
[Asana Task](https://app.asana.com/0/1202525367528099/1207432108755913/f)
when you click "Student Ministry" breadcrumb it goes to a 404. It either needs to go to /students or we need to put a redirect in place from /student-ministry to /students
[Deploy Preview](https://deploy-preview-3352--demo-crds-jekyll.netlify.app/media/videos/god-is-bigger-than-feelings-for-older-kids-or-kids-club)
`/students` 404s on the deploy preview but is the correct url
=> update student ministry breadcrumb

spec/fixtures/redirects.csv, spec/unit/redirects_spec.rb
removed links to various netlify instances we do not maintain / many of which are believed to have been recreated in the rock
Testing will need to be done post merge on this one
we need to visit these links when this body of work has been merged to demo & ensure that the links are still functional & point to their rock counter parts.
signup to serve pages
event check-in
forms
=> remove references to dead domains

_plugins/hooks/index_static_pages.rb
Static page entries need to include the full url instead of just the page slug.
Generate the full url based on `CRDS_ENV` and add it to each Algolia record.
=> Include full url when indexing static pages

_plugins/hooks/index_static_pages.rb, about.html, digital-tool-belt.html, our-memories.html, spiritual-outfitters.html, timeline.html
- Adds required fields that were missing from the output
- Updates static page descriptions
You can check the updated fields in the static index here: https://dashboard.algolia.com/apps/8Y3N3H5PNJ/explorer/browse/demo_crds_net_static?searchMode=search
=> Update fields for static Jekyll page indexing

_plugins/hooks/index_static_pages.rb
[Task](https://app.asana.com/1/37330734394864/project/1201454665996628/task/1209641195645766)
Adds a `description` field to static pages that get indexed. This text will be displayed in each search hit.
To test/verify, I ran the hook locally which updated the entries in the `demo_crds_net_static` index: https://dashboard.algolia.com/apps/8Y3N3H5PNJ/explorer/browse/demo_crds_net_static?page=2&searchMode=search
I also removed the `image` field since they will all return the placeholder image for static pages.
=> Include description field when indexing static pages

_includes/_head.html, _includes/header.html, _plugins/hooks/config.rb
**_head.html:**
Updates the logic so that the legacy component library is always loaded. If `use_unified_components` is true, we also load crds-unified-components.
**header.html:**
Check for `use_unified_components` before determining which header to use.
**config.rb:**
Updates `CRDS_UNIFIED_COMPONENTS_ENDPOINT` (we are not using this variable) to `CRDS_UNIFIED_COMPONENTS_DOMAIN` and fixes the url syntax.
=> Update conditional logic for component libraries/headers

_includes/_media-card.html, _includes/_overlay-card.html, _includes/_overlay-feature-card.html, _includes/_video-player-card.html, _plugins/filters/jsonify_message.rb
Remove dependencies for the message background image so that the field can be removed upstream in Contentful.
Removed the background image dependency for message content type by:
1. Standardizing the use of the `image` field across all content types
2. Removing special case handling for message content type images in:
- `_includes/_video-player-card.html`
- `_includes/_overlay-card.html`
- `_includes/_overlay-feature-card.html`
- `_includes/_media-card.html`
3. Removing the `background_image` and `bg_image` fields from the message JSON structure in `_plugins/filters/jsonify_message.rb`
4. Simplifying the image fallback logic to use the standard image field and default image
N/A
---
- …
=> Remove bg image references
