tv-app.html

update tv app copy

---

tv-app.html

Reverts crdschurch/crds-net#1862

Revert "update tv app copy"

---

_assets/stylesheets/pages/_tv-app.scss
tv-app.html

Update TV app content and image

---

tv-app.html

adding fb pixel to /tvapp

---

redirects.csv

Reverts crdschurch/crds-net#1875

Revert "switch to new invoice spa"

---

cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/locations/locations_landing_page_spec.js
cypress/integration/locations/locations_search/locations_search_out_of_range_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js

update index on location and onsite group test

update index on location and onsite group test

---

netlify.toml
tv-app.html

Reverts crdschurch/crds-net#1880

Revert "Algolia crawler spike"

---

_layouts/location.html

https://www.crossroads.net/georgetown
Under "Address" need to list "Office Address: 1242 Paris Pike, Geogetown, KY 40324" and "Worship & Prayer meeting place:  Great Crossing High School, 120 Betsy Way, Georgetown, KY. 40324"
Since there are two addresses listed and the layout and location content type only supports one address, I hardcoded a solution for the Georgetown page for now. I decided to hardcode the solution for this one location because it only happens once.
[Preview Link](https://deploy-preview-1890--crds-net.netlify.app/georgetown)

Update Georgetown Addresses

---

logged-in-homepage.html

Reverts crdschurch/crds-net#1899

Revert "remove student ministry category from logged in hp"

---

about.html
redirects.csv

Change 30 day trial to 30 day challenge and create a redirect

---

index.html
logged-in-homepage.html

disable journey banner

---

logged-in-homepage.html

rm student ministry category from logged in hp

---

redirects.csv

Redirect all /waivers/* traffic to /go /cc @tatelucas

Legacy Redirects

---

redirects.csv

Reverts crdschurch/crds-net#1915

Revert "swap back to old /invoices"

---

brian-tome.html

/brian-tome's instagram feed is not populating correctly. 
Comments out the instagram feed for now

Hides instagram feed

---

lib/crds/redirects.rb

need spouse invite stuffs too

---

spec/fixtures/redirects.csv
spec/unit/redirects_spec.rb

fixing tests

---

.github/workflows/run.cypress.yml
cypress/plugins/index.js

Kill travis

---

.github/workflows/run.cypress.yml

testing zapier commit filter

---

brian-tome.html

Social component has been fixed, this unhides BT's instagram feed.

Unhides instagram feed

---

redirects.csv

Updating URL and redirects to point to the okta sign in widget

removed redirescts to original sign in page

---

_assets/stylesheets/components/_ctas.scss
_assets/stylesheets/components/_modules.scss
logged-in-homepage.html
our-history.html
seven-hills.html
what-we-believe.html

30 day & tv app ctas

---

_assets/javascripts/components/bitmovin.js
redirects.csv

Christmas time with jake

---

_layouts/location.html

Need to update Georgetown and Richmond's addresses on their site pages and /locations (/locations pulls from Contentful).
[Paymo](https://app.paymoapp.com/#Paymo.Projects/2344222/tasks/simple/task/20055439)
**_Richmond_** 
Add "Office Address" and change address
105 S Third Street
Richmond, KY 40475
[Preview](https://deploy-preview-1976--int-crds-net.netlify.app/richmond)
**_Georgetown_**
Remove the "Worship & Prayer meeting place" address
[Preview](https://deploy-preview-1976--int-crds-net.netlify.app/georgetown)

Updates Richmond and Georgetown locations

---

_assets/javascripts/components/bitmovin.js
_includes/media/_bitmovin-player.html

autoplay via include param

---

_assets/javascripts/components/bitmovin.js

removing console log

---

_assets/javascripts/components/bitmovin.js
_includes/media/_bitmovin-player.html

Watch autoplay hotfix

---

_assets/javascripts/components/bitmovin.js
_includes/media/_bitmovin-player.html

fixing sound and formatting

---

_assets/javascripts/components/bitmovin.js

actually fixing sound

---

_includes/groups/_meeting-details-card.html
_layouts/onsite-groups/detail.html

Create new group detail page based off of [new design](https://invis.io/6BZOS8ZSE2Y#/440779330_03-03b-Site-Based-Groups-Internal)
[Preview](https://deploy-preview-1987--int-crds-net.netlify.app/groups/onsite/fathers/mason/)
**👇 This needs to be merged first**
[**Crds-Styles**](https://github.com/crdschurch/crds-styles/pull/502)

US20478 Group Detail Page

---

_assets/javascripts/components/resi-player.js

Change resi player time for testing

US20499 Test Resi Player

---

_includes/home/_our-best-content.html

Images were not optimizing. This is the fix until we fix the crds-image component.

Fix Broken Media Object Image

---

_includes/about/_leadership.html

Updates leadership to prod. See [PR](https://github.com/crdschurch/crds-net/pull/2003)

Leadership updates on prod

---

_assets/javascripts/components/resi-player.js
_assets/javascripts/config.js
_layouts/location.html

Put Resi Player in prod with the correct Sunday Service times
[Rally Task](https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fuserstory%2F480093836208&fdp=true?fdp=true)

US20499 Resi Player Prod

---

cypress/integration/404/404_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/infrastructure/redirect_regression_spec.js
cypress/integration/live/live_jumbotron_spec.js
cypress/integration/liveStream/live_stream_player_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js

*Reference to onsite groups is now site-based groups.*
*modify query string to filter onsite groups by category *
https://github.com/crdschurch/crds-net/tree/US20510-update-cypress-test
run cypress test suite

modify contentful queries to filter onsite groups on category

---

netlify.toml
redirects.csv

Corkboard doesn't woork
make corkboard work

added corkboard endpoint env var; updated redirects

---

_includes/_head.html

Adds the Osano script so it can start discovery to allow us to categorize items.
**Testing**
- The script https://cmp.osano.com/6olYRSI8uN8V3oE3/ee6703e4-e14a-4e11-bf03-f5b7b37c7061/osano.js **should** be loaded
- The script https://cmp.osano.com/6olYRSI8uN8V3oE3/65a23ab1-e0ce-4ccd-bc3c-2c8b89cb18f5/osano.js **should not** be loaded
- The script https://cmp.osano.com/AzqNJBSIcXEcQ40MM/3953df23-00fe-4c20-a7e5-156807dd17c5/osano.js **should not** be loaded
- There should be no cookie popup/any other changes.
- [US20516](https://rally1.rallydev.com/#/66096747656d/detail/userstory/483244917748)
- [Preview](https://deploy-preview-2015--crds-net.netlify.app/)

[Prod] Adds Osano scripts

---

_includes/_head.html

Adds the Osano script so it can start discovery to allow us to categorize items.
**Testing**
- The script https://cmp.osano.com/6olYRSI8uN8V3oE3/65a23ab1-e0ce-4ccd-bc3c-2c8b89cb18f5/osano.js **should** be loaded
- The script https://cmp.osano.com/6olYRSI8uN8V3oE3/ee6703e4-e14a-4e11-bf03-f5b7b37c7061/osano.js **should not** be loaded
- The script https://cmp.osano.com/AzqNJBSIcXEcQ40MM/3953df23-00fe-4c20-a7e5-156807dd17c5/osano.js **should not** be loaded
- There should be no cookie popup/any other changes.
- [US20516](https://rally1.rallydev.com/#/66096747656d/detail/userstory/483244917748)
- [Preview](https://deploy-preview-2016--int-crds-net.netlify.app/)

[Dev] Adds Osano scripts

---

redirects.csv

removing the 404 at just /sign-up/

---

robots.txt

[Rally Hotfix](https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fuserstory%2F487212108540&fdp=true?fdp=true)

Hotfix update robot txt with media sitemap

---

redirects.csv

removing splat from sign up

---

_layouts/sign-ups.html

changing laayout for angleica to help

---

_layouts/sign-ups.html

changing layout

---

_plugins/generators/onsite_groups_generator.rb

updated onsite group generator script

---

_layouts/onsite-groups/index.html
_plugins/generators/onsite_groups_generator.rb
redirects.csv

This PR cleans up some newly introduced 404s on groups pages.

[prod] DEXXXX 404s for Groups

---

redirects.csv

Ensure http -> https and sans-www -> www are eval'd first

DEXXXX Redirects

---

cypress/integration/live/live_jumbotron_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js

add error handling to fix cypress test

fix cypress test

---

.calibre/config.yml

Reverts crdschurch/crds-net#2079

Revert "add calibre config"

---

redirects.csv

remove `/groups/online`  redirect

Hotfix Remove Redirect

---

_includes/about/_leadership.html

leadership updates

---

redirects.csv

Apply temporary proxy rule for /media/shows to work around Netlify defect. 
https://deploy-preview-2106--crds-net.netlify.app/media/shows

[Production] DEXXXX Shows Redirect

---

_includes/_footer-script.html
_includes/_media-card.html
_includes/_media-label.html
_includes/_media-social-share.html
_includes/_product-feed.html
_layouts/location.html
index.html
media/index.html

- remove page.js_manifest from footer-script
- update logic for hotjar script
- fix locations page

[Runway] Remove errors

---

_assets/javascripts/components/resi-player.js

Change times for Easter Service 
(Saturday) April 3:
4pm service
stream go live at 3:55pm - run until 5:10pm
5:30pm service
stream go live at 5:25pm - run until 6:40pm
(Sunday) April 4:
Normal service and run times...
stream go live 8:25am - run until 9:40am
stream go live 9:55am - run until 11:10am
stream go live 11:40pm - run until 12:55pm

US20880 Resi Easter Service

---

_assets/javascripts/components/background-video.js
_assets/javascripts/config.js
_includes/_shows-most-recent.html
_layouts/collection.html
media/shows.html
redirects.csv

Remove CRDS_MEDIA_ENDPOINT redirects and shows redirect

Runway Clean up

---

_assets/javascripts/components/resi-player.js

Streaming service for Easter Sunday were not automatically refreshing the page at service time.
This segments Saturday and Sunday service and automatically refreshes at service time.
**DO NOT MERGE UNTIL AFTER SATURDAY'S LAST SERVICE**
This is only for /oakley and /mason

resolves sunday service stream

---

_assets/javascripts/components/resi-player.js

Change Resi Player back to the original service times

Update Resi Player Service Times

---

cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/support/loginCommands.js

convert cypress to use okta-login

remove reference to mp login

---

_layouts/established.html
_layouts/frontier.html

This PR adds placeholder layouts for the new Frontier and Established layouts work so the pages will not break during work in a separate branch

US20885 location layout

---

_layouts/established.html
_layouts/frontier.html

Signed-off-by: Dan Holloran <dan@helloample.com>

Adds placeholder layouts for new locations template

---

Gemfile
Gemfile.lock

Upgrades Jekyll Contentful to the latest 3.2.0

Fixes Int Build

---

_config.yml
_includes/_location-info.html
_layouts/frontier.html

Create the jumbotron for the new Frontier locations page design. 
https://invis.io/TQZOZZ4VSXR#/447468244_Columbus_-_Desktop_-_2

US20887 Frontier Jumbotron

---

_assets/javascripts/components/header.js
_assets/stylesheets/pages/_hoc-detail.scss
_assets/stylesheets/pages/_humans-of-crossroads.scss
_assets/stylesheets/pages/_modules.scss
_config.yml
_includes/_footer-script.html
_layouts/established.html
_layouts/frontier.html
_layouts/humans-of-crossroads.html
_plugins/hooks/humans_of_crossroads.rb
media/humans-of-crossroads.html

Also fixed locations layout and removed references of front chat

HOC into Netmergia

---

_assets/stylesheets/_utilities.scss
_includes/_pagination.html
_includes/_preloader.html
media/humans-of-crossroads.html

Implement pagination on the humans of crossroads index page
[Preview](https://humans-pagination--demo-crds-net.netlify.app/media/humans-of-crossroads/) for testing. (added some more articles so that we can test if pagination works)

US20989 Humans Pagination

---

_assets/stylesheets/_utilities.scss
media/index.html

Add HoC section to the homepage
Check it out! 👉  https://humans-on-media-hp--demo-crds-net.netlify.app/media/ 👈

US20938 Humans Sections

---

_includes/_location-info.html

Links the pastor on the new location pages to the "community pastor" tab.
**Note:** This is dependent on the following [crds-components PR](https://github.com/crdschurch/crds-components/pull/1158)

Links location pastor to tab

---

_assets/stylesheets/pages/_locations.scss
_includes/_frontier-launch-team-modal.html
_includes/_location-info.html
_layouts/established.html
_layouts/frontier.html

- fix jumbotron headers
- Adds launch form
- fixes pastor circle image and border
- fixes content
- fixes button alignment
- removes second footer
- clean up

Location QA fixes (Silas)

---

redirects.csv

Try to fix an issue with redirect and studentcamps

---

_assets/javascripts/components/autoplay-controller.js

Fix autoplay issue for the message, video detail pages, and media homepage. Currently only works for net homepage

Use crds-media version of autoplay-controller

---

_assets/javascripts/components/bitmovin.js
_assets/javascripts/components/youtube.js
_includes/_video-player.html
docker/development/Dockerfile.local
docker/development/docker-compose-local.yml
docker/development/entrypoint-local.sh

Need to capture when a video or message is watched for Personal Engagement feature.
Render the crds-media-metric component and fire off an event that the component is listening for.
Watch a video  and then go to azure cosmos db and see that a media metrics collection has a record for that video

My impact v1

---

_layouts/article.html

Track article views
Call crds-media-metrics component after 30 seconds to send off an update that the article had been viewed.

Add event to fire off media metric for article views after 30 seconds

---

_assets/stylesheets/components/_cards.scss

Text on media cards being too large and cut off. [Asana ](https://app.asana.com/0/1198951831278010/1200290763427522)

Fixes text on media cards

---

_layouts/established.html
_layouts/frontier.html

[Asana](https://app.asana.com/0/1198951831278010/1200290763427528)

Details don't always have appropriate spacing between columns

---

_includes/_media-social-share.html
_layouts/article.html

show media metric unless saying otherwise

---

_includes/_media-social-share.html
_includes/_social-share.html
_includes/_video-player.html
_layouts/article.html

Reverts crdschurch/crds-net#2237

Revert "removing media metric components"

---

robots.txt

Remove media from sitemaps

---

_includes/_media-social-share.html
_includes/_social-share.html

Fix bug where articles with ' in the name could not be shared.

---

_includes/_social-share.html

Fix social share for twitter. 
I also fixed facebook
[Deploy Preview](https://twitter-share--int-crds-net.netlify.app/media/humans-of-crossroads/bill-k-story)

US21108 Share Twitter

---

_assets/stylesheets/pages/_hoc-detail.scss
_assets/stylesheets/pages/_humans-of-crossroads.scss
_layouts/humans-of-crossroads.html
media/humans-of-crossroads.html

Fix Image frame on ipad - distorted right now
Redo HoC image styles
[Preview](https://hoc-frames--int-crds-net.netlify.app/media/humans-of-crossroads/)

DE8319 HoC Frames

---

_assets/javascripts/components/resi-player.js

Revert Resi times back to normal

Change Resi Service Times

---

wcig.html

Fix WCIG video defect

---

cypress/config/int_crossroads.json
cypress/integration/404/404_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/locations/locations_search/location_search_api_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/messagePage/bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/messagePage/second_part_bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/videoPage/video_player_spec.js
package-lock.json
package.json

remove the skip for media audio test

add media audio test back in

---

_assets/stylesheets/pages/_our-memories.scss
our-memories.html

US21133 Digital Mosaic Randomize

---

_includes/_location-info.html
_layouts/established.html

add "hang out during the week"

Location Page Update

---

_includes/_frontier-launch-team-modal.html

US21208 Locations Launch Form

---

logged-in-homepage.html
wcig.html

• edit wcig.html text for undivided

add content block to home page for location ads

---

_assets/stylesheets/components/_skeletons.scss

Add skeleton class for location content component

HOTFIX Location Content

---

_assets/stylesheets/pages/_articles.scss
_includes/_article-social-share.html
_includes/_collapsible-discussion-questions.html
_layouts/article.html

[Design](https://invis.io/HNYKN2CF7VJ#/436889269_Article_V2_A)
[Deploy Preview](https://article-redesign--int-crds-net.netlify.app/media/articles/handling-depression-how-to-keep-getting-up)
[Crds-Component (heart-button)](https://github.com/crdschurch/crds-components/pull/1261)
Changes I made that contradict the design
- I kept the media object component the same. Only difference was that the card stamp was white instead of black
- In design there are 7 authors shown in the "Popular Author" section but I changed it to show 6 because 7 does not work with our 12 column layout.

US20386 Article Redesign

---

_includes/_the-basics.html
history.html

History page updates with corresponding updates to the shared-footer component in `crds-data` repo.
Asana Task:
https://app.asana.com/0/home/1157286040753232/1200341377180946
Update links in footer: https://github.com/crdschurch/crds-data/pull/73
Update /history page
https://int.crossroads.net/history/

Updates to /history page

---

_assets/stylesheets/components/_hubspot-forms.scss

Hbspt Safari Checkbox

---

_includes/_article-social-share.html
_layouts/article.html

- fix discussion questions
- fix social share logo color

Article QA

---

_assets/stylesheets/pages/_articles.scss
_layouts/article.html

fix text issue on cards on this page https://int.crossroads.net/media/articles/
Create custom class so these styles aren't used on the main /articles page
[Test article page](https://article-redesign--int-crds-net.netlify.app/media/articles/handling-depression-how-to-keep-getting-up) to make sure it's styling isn't affected.

create custom class for headings on article pages

---

_assets/stylesheets/pages/_articles.scss
_layouts/article.html

Demo - DE8359: The defect for the text is too big and cut on the top of some of the articles card is back

---

_layouts/established.html

if there are not SM hours do not show SM section

USXXXXX Location SM Section

---

_layouts/established.html
_layouts/frontier.html

[US21063](https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fuserstory%2F603485904076&fdp=true?fdp=true): [Locations] +CP contact (email) option (front end & CMS)
[US21064](https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fuserstory%2F603486809416&fdp=true?fdp=true): [Locations] +CP social Links (front end & CMS)
[Established Preview](https://60c8ea6b035b1600b4659a44--crds-net.netlify.app/oakley)
[Frontier Preview](https://60c8ea6b035b1600b4659a44--crds-net.netlify.app/columbus)

US21063 US21064 Location CP Contact Info

---

brian-tome.html

[Rally Task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fdefect%2F601859048273)
- Commented out instagram feed so it can be turned back on in the future.
- Changed tan section font color to gray-dark.
Go to `/brian-tome`

Update Brian Tome instagram & podcast feeds

---

_assets/stylesheets/_utilities.scss
_layouts/established.html
_layouts/frontier.html

[US21065](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fuserstory%2F603486812356&fdp=true?fdp=true): [Locations] +SM Pastor Contact info (front end & CMS)
[Preview](https://sm-leader--int-crds-net.netlify.app/oakley)

US21065 Add SM Leader Email

---

media/shows.html

video_file needs to be preview_video
Follow up to this PR: https://github.com/crdschurch/crds-net/pull/2314
[Rally Task](https://rally1.rallydev.com/#/66096747656d/teamboard?detail=%2Fdefect%2F509646936656)

Replace video file with preview video

---

_includes/trips/_trips-footer.html

Remove Support Raisins from footer

---

_assets/javascripts/components/bitmovin.js
_includes/_bitmovin-player.html

Add Chapters to Bitmovin Video
Use the timestamp feature from contentful and update bitmovin player config to use the timestamps in their api.
https://rally1.rallydev.com/#/41662702253d/custom/346988092616?detail=%2Fuserstory%2F519405159452

Add markers for bitmovin chapters

---

_layouts/established.html

Add second SM Leader on /mason. Hard code for now until we see more request for this 
[US21313](https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fuserstory%2F602617899037&fdp=true?fdp=true): Add second SM Leader on /mason

US21313 Add Second SM Leader for Mason

---

media/series.html

DE8418 Current Series Text Color

---

_assets/javascripts/components/bitmovin.js
_includes/_bitmovin-player.html

Add bitmovin chapters

---

_layouts/trip.html

Remove Total cost note for fundraising

---

_includes/_head.html
netlify.toml

This code reverts the removal of the gtag.js implementation.

Revert back to gtag.js implementation

---

_layouts/established.html

Add stay up to date image if it is available, else use default stay up to date  image

US21337 Stay up to date image

---

_layouts/frontier.html

- remove series section from frontier

US21335 Frontier Series

---

cypress/integration/homepage/home_page_current_series_spec.js
cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/integration/live/live_current_series_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/seriesPage/series_page_current_series_spec.js

update reference to description in test

updated reference to description

---

_layouts/frontier.html

[Rally Task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fuserstory%2F602614585619)
remove "Crossroads Columbus" from in front of Caroline and Dakota's titles

Copy update for feature/us21311 Columbus location update

---

_layouts/frontier.html

[Asana Task](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?detail=%2Fuserstory%2F602614585619)
Meet the team align content top

Align Top Bugfix - Feature/us21036 author template update

---

_layouts/frontier.html

Columbus Team Edits

---

_layouts/default.html
_layouts/no-header-no-footer.html

Add hubspot tracking code to default and no-header-no-footer layouts
[Asana Task](https://app.asana.com/0/1200386240453000/1200412027456001/f)

Add hubspot tracking code

---

_layouts/frontier.html

Remove Current Series from Columbus page

[HOTFIX] Remove Current Series from Columbus

---

_layouts/established.html
_layouts/frontier.html

Can you turn back on current series for Cbus today and turn off for /uptown

Hotfix location series

---

_assets/stylesheets/pages/_locations.scss
_layouts/frontier.html

Needs to be in master. Currently in INT

add Columbus overlay to master

---

_includes/_head.html

Code contained errant gtag() references. This PR removes that.

Remove errant gtag() references

---

_layouts/series.html

Fix message cards on series page

---

_assets/javascripts/lib/video-modal-close.js
_layouts/frontier.html

Columbus Video doesn't stop when modal is closed
Add logic: when modal is closed - also stop video

add stop video logic

---

_assets/javascripts/components/pagination.js
_assets/stylesheets/components/_pagination.scss
_includes/_article_index.html
_includes/_pagination.html

There was a request to refactor the pagination on the articles index page
from having a "Load More" button to resemble something more akin to 
traditional pagination.
Pagination on the article index is now in the format of [n] of NN, where
"n" is the current page your are on, "[]" is the input field that allows
you to change which page you are on, and "NN" is the total number of
paginated pages.
No corresponding branches.
Given I am on the first page of the Articles index page
When I scroll down to the bottom of the page
Then I should see an input field with the placeholder of "1"
And I should see the text "of 'NN'", where 'NN' is the total number of pages
And I should see a button with the text "Go!" inside
And I should see a button with ">>" inside.
Given I have typed a value into the …

Article Index Pagination

---

netlify.toml
redirects.csv

Reverts crdschurch/crds-net#2426

Revert "add redirect for online registrants"

---

_assets/javascripts/components/resi-player.js
_assets/stylesheets/pages/_locations.scss
_includes/_columbus-top-section.html

On Demand SB

---

_assets/javascripts/components/resi-player.js
_assets/stylesheets/pages/_locations.scss
_includes/_columbus-top-section.html
_includes/locations/_ondemand-card.html
_layouts/established.html
_layouts/frontier.html

No way to communicate with members that there is a prior weeks service available for watching during non-service hours.
Created CTA to render while it's not service time for viewing the most recent service.
Look at designs on screen to verify work against design.

Ondemand master

---

netlify.toml

Add environment variables for proper redirection of users from Church online registration.

add netlify env vars.

---

cypress/integration/404/404_spec.js
cypress/integration/currentSeriesPage/current_series_page_spec.js
cypress/integration/homepage/home_page_current_series_spec.js
cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/infrastructure/redirect_regression_spec.js
cypress/integration/live/live_current_series_spec.js
cypress/integration/locations/locations_landing_page_spec.js
cypress/integration/locations/locations_search/locations_search_in_range_spec.js
cypress/integration/locations/locations_search/locations_search_invalid_spec.js
cypress/integration/locations/locations_search/locations_search_out_of_range_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/messagePage/bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/messagePage/download_links_spec.js
cypress/integration/messagePage/message_player_spec.js
cypress/integration/messagePage/second_part_bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js
cypress/integration/seriesPage/series_page_current_series_spec.js
cypress/integration/videoPage/video_player_spec.js

add error checking to cypress test

add error checking to cypress test

---

netlify.toml
redirects.csv

replace env vars to be set in netlify UI, casing on redirect cookie.

remove var from netlify toml, change redirect casing.

---

_includes/_columbus-top-section.html

Sign up button on jumbotron is not showing modal

HOTFIX Columbus sign up button modal

---

logged-in-homepage.html

[US21862](https://rally1.rallydev.com/#/?detail=/userstory/614136367661&fdp=true): Remove My groups Component from .net Homepage

US21862 Remove Groups List from logged in homepage

---

logged-in-homepage.html

US21862 Remove Groups List from Homepage

---

_layouts/trip.html

Adding the new filter options to display on each trip detail page

add filter results on trip detail page

---

redirects.csv

Update connect to findGroups

---

media/weekend-follow-up.html

I removed the "Creating a group with prompt" video and text

Removed Video and video text

---

media/weekend-follow-up.html

I removed the tan 3-step content block at the bottom and updated the description of the page

Update Copy and remove content block

---

_layouts/article.html

[DE8753](https://rally1.rallydev.com/#/?detail=/defect/615616192013&fdp=true): [Media] Popular Author images on articles are not fully rendering
10x10 image is not rendering to full size image. 
Set desired width and height in img url 
[Deploy Preview](https://deploy-preview-2479--crds-net.netlify.app/media/articles/god-didnt-forget-about-my-grief)

DE8753 Popular Author Images

---

Gemfile
Gemfile.lock
_config.yml

Add meta to config
[Rally Story](https://rally1.rallydev.com/#/?detail=/defect/615638488679&fdp=true)
[Facebook debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-2478--crds-net.netlify.app%2Fmiamivalleylights%2F)

DE8754 Meta Image

---

_layouts/episode.html

[DE8805](https://rally1.rallydev.com/#/?detail=/defect/619164277337&fdp=true): Extraneous Character in Content Author Grouping attribute

DE8805 Author Content Grouping

---

_layouts/established.html
_layouts/frontier.html

Removed the <crds-image> component which is hard coded to be 4x3

Change Current Series to 16x9

---

redirects.csv

Create redirects from live messages that were videos that are now messages
[Look here for documentation](https://docs.google.com/spreadsheets/d/1ThicVFXPHSan3i7hMGArKiMBjWAPiGEQhp9NHYIr0Yg/edit?usp=sharing)

create redirects for old live messages urls

---

_includes/home/_latest-message.html

Markdown was not rendering correctly on the home page

Hotfix Message desc markdownify

---

_assets/javascripts/components/resi-player.js
_includes/locations/_resi-player.html

Update Resi Players to use iframes. This is the recommended way for us to implement a player according to Resi
Also will need to update /watch in the cms

Update resi player to use iframe

---

_assets/javascripts/components/resi-player.js
_includes/_columbus-top-section.html
_layouts/established.html
_layouts/frontier.html
index.html
logged-in-homepage.html

Resi player needs to show up 8:25 to 1:00

Change Resi Player timing

---

_assets/javascripts/components/resi-player.js
_includes/_resi-player.html
_includes/locations/_resi-player.html

[US22006](https://rally1.rallydev.com/#/?detail=/userstory/620688252279&fdp=true): [HOT FIX] Adjust stream schedules for xmas - DUE 12/23

Resi Xmas Eve Service

---

.github/workflows/run.cypress.yml
cypress/integration/404/404_spec.js
cypress/integration/currentSeriesPage/current_series_page_spec.js
cypress/integration/homepage/home_page_current_series_spec.js
cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/infrastructure/redirect_regression_spec.js
cypress/integration/locations/locations_landing_page_spec.js
cypress/integration/locations/locations_search/locations_search_in_range_spec.js
cypress/integration/locations/locations_search/locations_search_invalid_spec.js
cypress/integration/locations/locations_search/locations_search_out_of_range_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/messagePage/bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/messagePage/download_links_spec.js
cypress/integration/messagePage/message_player_spec.js
cypress/integration/messagePage/second_part_bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js
cypress/integration/seriesPage/series_page_current_series_spec.js
cypress/integration/videoPage/video_player_spec.js
cypress/support/elementCommands.js
index.html
package-lock.json
package.json

run test in docker container from github action
add automation id for online and live message 
added error handling 
skipped series test
updated the version of cypress from 4.8.0 to 6.5.0
updated version on action from v1 to v2

add cypress test to a docker container

---

.github/workflows/run.cypress.yml
cypress/integration/404/404_spec.js
cypress/integration/currentSeriesPage/current_series_page_spec.js
cypress/integration/homepage/home_page_current_series_spec.js
cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/infrastructure/redirect_regression_spec.js
cypress/integration/locations/locations_landing_page_spec.js
cypress/integration/locations/locations_search/locations_search_in_range_spec.js
cypress/integration/locations/locations_search/locations_search_invalid_spec.js
cypress/integration/locations/locations_search/locations_search_out_of_range_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/messagePage/bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/messagePage/download_links_spec.js
cypress/integration/messagePage/message_player_spec.js
cypress/integration/messagePage/second_part_bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js
cypress/integration/seriesPage/series_page_current_series_spec.js
cypress/integration/videoPage/video_player_spec.js
cypress/support/elementCommands.js
index.html
package-lock.json
package.json

Reverts crdschurch/crds-net#2517
Build is broken and causing deploys to go in a broken state.

Revert "add cypress test to a docker container"

---

.github/workflows/run.cypress.yml
cypress/integration/404/404_spec.js
cypress/integration/currentSeriesPage/current_series_page_spec.js
cypress/integration/homepage/home_page_current_series_spec.js
cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/infrastructure/redirect_regression_spec.js
cypress/integration/locations/locations_landing_page_spec.js
cypress/integration/locations/locations_search/locations_search_in_range_spec.js
cypress/integration/locations/locations_search/locations_search_invalid_spec.js
cypress/integration/locations/locations_search/locations_search_out_of_range_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/messagePage/bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/messagePage/download_links_spec.js
cypress/integration/messagePage/message_player_spec.js
cypress/integration/messagePage/second_part_bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/onsite/onsite_group_landing_page_spec.js
cypress/integration/seriesPage/series_page_current_series_spec.js
cypress/integration/videoPage/video_player_spec.js
cypress/support/elementCommands.js
index.html
package-lock.json
package.json

Reverts crdschurch/crds-net#2520
put cypress changes back into development branch

Revert "Revert "add cypress test to a docker container""

---

_redirects

• I tried in contentful but it wouldn’t take

Add atrium event redirects

---

_layouts/collection.html

[US22128](https://rally1.rallydev.com/#/?detail=/userstory/623612638751&fdp=true): Adding trailer to a Show detail page
[Preview](https://shows-trailer--int-crds-net.netlify.app/media/collections/garage-bible-study)

Add trailer modal

---

_includes/home/_our-best-content.html

The Title "Our best content" isn't reflective of the actual content since it's not dynamic. 
Change it to be "Most popular"

hotfix our best content section title

---

_plugins/netlify-plugin-health-check/index.js

Health check wasn't catching some problems
Added checks for application.css, application.js, and application-deferred.js
No corresponding branches
Confirm Netlify health check runs on a build in Netlify

US22090 Update Health Check for CSS and JS

---

_assets/javascripts/lib/location-finder.js

This commit changes the logic and hardcodes the endpoint from which
location data is retrieved. There was consideration toward using a new
env variable, but since the old Gateway API endpoint is getting revamped
one piece at a time, it was decided to hard code until the changeover is
complete, reducing the number of env vars that get created.

HOTFIX US22151 Fix Location Finder Endpoint

---

_layouts/collection.html

Fix button styling on collections (centered white outline button on black background)

US21759 Shows Pagination

---

_assets/javascripts/components/resi-player.js

This PR adjusts the logic and timing around displaying the resi player
for the Super Bowl of Preaching weekend.

US22165 Update Service Times for Super Bowl

---

_layouts/message.html

Messages be metered
Remove metering component from messages.

unmeter those messages.

---

_layouts/video.html

Make copy more relevant now that we only meter shows.

update copy in modal

---

redirects.csv

Removes OC redirect line from redirects file. 
See adjacent PR's:
crds-online: https://github.com/crdschurch/crds-online/pull/562
crds-components: https://github.com/crdschurch/crds-components/pull/1605

reove OC redirect.

---

redirects.csv

Fix issue with a paid ad for Cohorts that is redirecting to get started.

add redirect for cohorts page

---

redirects.csv

testing for cohorts ad redirection issue

add cohort redirect

---

logged-in-homepage.html

Remove link "My Student Camps"
Comment out the link 
https://github.com/crdschurch/crds-net/tree/US22233-remove-camps-link

US22233 - remove camps link

---

redirects.csv

testing branch for cohorts redirect inconsistency issues.

update redirects for cohorts page exlucsion.

---

redirects.csv

fixing online redirects to work with different envs

---

index.html

Current series still shows Easter

HOTFIX HP Current series

---

_includes/locations/_ondemand-card.html

On demand card on location pages shows easter series instead of John

Fix current series on ondemand card

---

_layouts/established.html
_layouts/frontier.html

Current Series should not be Easter

Fix current series on Location pages

---

redirects.csv

Demo Deploy 4-27-22

---

_includes/about/_leadership.html

Updated Alli Patterson's photo and description/bio

Update Alli photo and bio

---

_includes/_overlay-card.html

Making overlay card display image not background image

---

redirects.csv

add a redirect for proxying unified website requests to the proper place

add catch-all redirect for unified websites.

---

redirects.csv

Group Renew redirect try

---

redirects.csv

group renew try

---

netlify.toml

Redirect test

---

netlify.toml
redirects.csv

Move everything back to what it was

---

redirects.csv

Redirect workaround for group renewal

---

redirects.csv

test to see if this rediirect is even being used.

---

redirects.csv

Test if redirect is even working

---

_includes/about/_leadership.html

Updated Kyle's title to Director of the Experience Team

Update Kyle's title

---

_assets/stylesheets/components/_hubspot-forms.scss

EX:
https://www.crossroads.net/go/trip-interest-list/

Add width: auto to checkbox

---

_includes/header.html

Add classname to skeleton logo svg

Add classname to skeleton logo svg

---

.github/workflows/run.cypress.yml
cypress/config/int_crossroads.json
cypress/config/vault_config.json
cypress/fixtures/location_search_results.js
cypress/integration/404/404_spec.js
cypress/integration/homepage/home_page_current_series_spec.js
cypress/integration/homepage/home_page_happenings_noprod_spec.js
cypress/integration/homepage/home_page_latest_message_spec.js
cypress/integration/infrastructure/redirect_regression_spec.js
cypress/integration/locations/locations_landing_page_spec.js
cypress/integration/locations/locations_search/locations_search_in_range_spec.js
cypress/integration/locations/locations_search/locations_search_invalid_spec.js
cypress/integration/locations/locations_search/locations_search_out_of_range_spec.js
cypress/integration/mediaHomePage/landing_page_current_series_spec.js
cypress/integration/messagePage/bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/messagePage/download_links_spec.js
cypress/integration/messagePage/message_player_spec.js
cypress/integration/messagePage/second_part_bitmovin_message_autoplay_subtitle_mute_spec.js
cypress/integration/seriesPage/series_page_current_series_spec.js
cypress/integration/videoPage/video_player_spec.js
spec/config/int_crossroads.json
spec/support/index.js

update vault_config to use  secret Crossroads.Automation instead of Media
updated uptown location response
updated error checking on several test

fixed some broken test

---

_includes/_bitmovin-player.html

Adding recommended collection and special character fix

---

_assets/stylesheets/components/_jumbotron.scss

Updating css to fix gap in logged in homepage

---

_assets/stylesheets/pages/_all-trips.scss
_includes/_trip-card.html

fix mobile sizing
col-xs width hack :)

AG trips update master

---

_assets/stylesheets/pages/_all-trips.scss
_includes/_trip-card.html

AG trips update (dev)

---

redirects.csv

Removing corkboard from redirects

---

netlify.toml

removing corkboard refs in netlify.toml

---

logged-in-homepage.html

Removing tithe challenge section from logged in homepage

---

_assets/stylesheets/_utilities.scss
_assets/stylesheets/pages/_locations.scss
_layouts/anywhere.html

[Asana Task](https://app.asana.com/0/1201985975628366/1202644533795663/f)
QA feedback and content changes are still ongoing but would like to have these changes show up in the int environment
[Deploy Preview](https://anywhere-page--crds-net.netlify.app/anywhere)
Once merged, I will need to update the Anywhere Location layout field to anywhere

Anywhere layout

---

_assets/stylesheets/pages/_shows.scss
_includes/_shows-most-recent.html
_layouts/collection.html
_plugins/generators/next_level_generator.rb
_plugins/generators/shows_generator.rb
media/next-level-academy.html
media/shows.html

[Asana Task](https://app.asana.com/0/1201985975628366/1202644533795669/f)
QA feedback and content changes are still ongoing but would like to have these changes show up in the int environment
[Next Level Landing page](https://deploy-preview-2696--int-crds-net.netlify.app/media/next-level-academy/)
[Next Level detail page](https://deploy-preview-2696--int-crds-net.netlify.app/media/collections/prayer101)
- We need to make sure all of the Next Level Content has a crossroads.net as the distro channel
- Need to add collection reference to each video

Move Next Level Academy to Crds.net From Online Repo

---

redirects.csv

Remove anywhere redirects so we can view the new /anywhere page

remove anywhere redirects

---

redirects.csv

Unified redirects

---

_includes/_article-social-share.html
_includes/_social-share.html
_includes/_subscribe-buttons.html
_layouts/article.html
_layouts/episode.html
_layouts/humans-of-crossroads.html
_layouts/message.html
_layouts/podcast.html
_layouts/series.html
_layouts/video.html

The following changes add requisite code to enable accurate reporting of the ContentEngaged analytics event.
Add requisite code to enable the new "ContentEngaged" analytics event to get reported.
There is a corresponing PR in the crds-components repo. https://github.com/crdschurch/crds-components/pull/1747
While monitoring the Segment debugger, confirm "ContentEngaged" events get reported while pushing various subscribe buttons, like buttons, share buttons, when videos start, and when videos finish.

Implement ContentEngaged Event

---

_assets/stylesheets/pages/_shows.scss

[Asana Task](https://app.asana.com/0/0/1203086941040786/f)

fix shows video bg

---

media/next-level-academy.html
media/shows.html

fix carousel

---

media/next-level-academy.html
media/shows.html

[Asana Task](https://app.asana.com/0/1201985975628366/1203144885310943/f)
Carousel slots were starting at 18. Once I changed the variable name from slot, which is also being used on other pages, to shows_slot everything started to work

HOTFIX shows carousel

---

404.html

Hot fix, handle redirectis client-side due to Okta POST to /signin

---

redirects.csv

We need to proxy /api to the NextJS application so we can can expose server-side API routes.
This PR updates the redirects.csv

Expose /api for NextJS

---

redirects.csv

This PR adds a proxy rule for /signout to crds-unified. 
crdschurch/crds-unified#316

Proxy /signout to crds-unified

---

redirects.csv

Added a redirect rule for the new monthly prayer night page

add redirect for monthly prayer night page

---

_layouts/frontier.html
seven-hills.html

Added "flex-child" to the div class for Brenna and Matt team bios

Added "flex-child" to Team bios

---

redirects.csv

Demo Deploy 11-22-2022

---

_layouts/series.html

Change in the wording for the new receive weekly teaching initiative.

Change tab wording on media template page

---

_includes/_frontier-launch-team-modal.html
_layouts/established.html
_layouts/frontier.html
_layouts/location.html

Remove formInstanceId that is causing thank you message to not show

HOTFIX Hubspot form not showing "Thank you" message

---

404.html
Gemfile
Gemfile.lock
_assets/javascripts/components/analytics.js
_assets/javascripts/config.js
_assets/stylesheets/components/_hubspot-forms.scss
_config.yml
_includes/_frontier-launch-team-modal.html
_layouts/anywhere.html
_layouts/established.html
_layouts/frontier.html
_layouts/location.html
bin/build-command.sh
media/next-level-academy.html
media/shows.html
package.json
seven-hills.html

Upstream changes in `master` need to be reflected in `development`
This PR introduces upstream changes to `development`.

Backmerge master to development

---

_layouts/series.html
redirects.csv

HOTFIX Message wording tweak

---

404.html

Swap blue cup for orange cup

---

redirects.csv

Reverts crdschurch/crds-net#2764
Yup, revert revert. We are ready to have these changes back into INT as the authentication in unified has been updated to accept these changes.

Revert "Revert "Remove Role=user from Unified Routes""

---

redirects.csv

Adds the redirects for Unified auth pages back into the mix.

add old auth-redirects.

---

redirects.csv

Need to handle redirects for both logged-in and logged-out Growth Path pages
Add the appropriate redirects
https://github.com/crdschurch/crds-unified/pull/389
Check that you see the appropriate Growth Path page based on your auth status

Testing/logp Redirects

---

redirects.csv

Needed redirects added for the cohort pages in crds-unified
Added a redirect for the cohort landing page `/cohorts`
added a redirect for the cohort detail pages `/cohorts/*`

add cohorts redirects

---

media/index.html
redirects.csv

Reverts crdschurch/crds-net#2790

Revert "Prod deploy 12-20-2022"

---

redirects.csv

Adds redirect for logged out growth path page

Logged out growth path redirect

---

_assets/javascripts/components/resi-player.js

There are no service times for xmas
remove services times this week
change date to sunday between 8:25 am & 1pm 
you should not see the live stream player

xmas 2022 remove services times | dev

---

index.html

Rescue nil array before we try to sort them

---

_assets/javascripts/components/resi-player.js

Change our service times back after xmas 2022
added service times back
change date to sunday between 8:25 am & 1pm 
you should see the live stream player

post xmas service times 2022 | Dev

---

redirects.csv

removing wildcard redirect that I was using for testing.

Remove redirect wildcard for NewAccount page

---

_assets/javascripts/components/resi-player.js

Change our service times back after xmas 2022
added service times back
change date to sunday between 8:25 am & 1pm 
you should see the live stream player

post xmas service times 2022 | demo

---

redirects.csv

add cohort redirects

---

redirects.csv

Prod Deploy 1/9/2023

---

redirects.csv

Reverts crdschurch/crds-net#2821

Revert "Prod Deploy 1/9/2023"

---

_includes/_location-card.html

Removing the set my site button on location card

---

_includes/_location-card.html
_layouts/series.html

[task](https://app.asana.com/0/1201454420722044/1203636114445641/f)

Account for only one weekend message

---

redirects.csv

Need to redirect to the new rock login page instead of the existing `signin` page.
Change redirects using `signin` to use `login`
[Corresponding PR](https://github.com/crdschurch/crds-unified/pull/493)
Test and verify that the redirects work correctly.

change signin redirects and add redirct for signin to login

---

_assets/javascripts/components/resi-player.js

Change live service times to:
Sat 2:55 to Sun 8:30

change resi player times

---

_includes/header.html

Updated the shared header to pass root url so the login put works correctly on the rock environment.

update root url for header - temporarily.

---

redirects.csv

modify redirect to use CRDS_ROCK_DOMAIN variable

---

_assets/javascripts/components/resi-player.js

Reverts crdschurch/crds-net#2848

Revert "change resi player times"

---

_assets/javascripts/components/resi-player.js

Reverts crdschurch/crds-net#2841

Revert "update resi-player for SBOP"

---

_assets/javascripts/components/resi-player.js

[INT] change stream begin to 840

---

_assets/javascripts/components/resi-player.js

Update refresh time to match the update service time of 8:40

update refresh time

---

_assets/javascripts/components/resi-player.js

[DEMO ]change stream begin to 840

---

redirects.csv

Reverts crdschurch/crds-net#2854

Revert "create redirects to rock downtime page"

---

redirects.csv

remove .ROCK_AUTH from cookie check

---

_config.yml

uncomment disable_hubspot

---

_config.yml

Reverts crdschurch/crds-net#2866

Revert "uncomment disable_hubspot"

---

redirects.csv

had typo on 2 redirect links
fixed typo

fix typo on env variable

---

_layouts/default.html
_layouts/no-header-no-footer.html

comment out hubspot imports

---

_layouts/default.html
_layouts/no-header-no-footer.html

Reverts crdschurch/crds-net#2871

Revert "comment out hubspot imports"

---

bin/build-command.sh

add trace flag to build

---

_includes/about/_leadership.html

Changed leadership title type from Vivenne to Vivienne

Typo change Vivenne to Vivienne

---

redirects.csv

Add redirects in to send users to the rock-downtime page.

add a few more redirects for downtime.

---

_assets/javascripts/components/resi-player.js

---
- https://app.asana.com/0/0/1204006083600282

[INT] Update service times

---

redirects.csv

Bring in the "final" version of redirects for the crds-net & rock pages.

final live redirects

---

_assets/javascripts/components/resi-player.js

[DEMO] Update service times

---

lib/crds/redirects.rb

remove auth redirects

---

redirects.csv

Application was getting 502 error, reverting until Monday

Revert "add volunteer search back into redirects."

---

redirects.csv

removed volunteer search redirect

---

redirects.csv

add back volunteer/search redirect

---

redirects.csv

Fix url in practice index redirect

---

_plugins/generators/transcription_generator.rb

---
- https://app.asana.com/0/0/1204066110808912

[INT] Try to solve sporatic errors in transcription_generator

---

_plugins/generators/transcription_generator.rb

Prod deploy for transcription generator fix

---

redirects.csv

Update demo cookies

---

redirects.csv

Practice Index Redirects

---

redirects.csv

Practice Index Redirects [Prod]

---

_assets/stylesheets/_fonts.scss
_assets/stylesheets/pages/_articles.scss
_layouts/article.html

Footer CTA fix for Articles

---

_assets/stylesheets/_fonts.scss
_assets/stylesheets/pages/_articles.scss
_layouts/article.html

Update header tags

---

_assets/javascripts/components/resi-player.js

Update resi player for Easter

---

_layouts/video.html

Demo ungate shows

---

_assets/javascripts/components/resi-player.js

Revert Easter resi player changes

---

_assets/javascripts/components/resi-player.js

Reverts crdschurch/crds-net#2943

Revert "Update resi player for Easter"

---

redirects.csv

handle redirect

---

redirects.csv

alter status code

---

redirects.csv

alter position of redirect

---

redirects.csv

---
- https://app.asana.com/0/0/1204400787200495

redirect to logged out page if not logged in

---

_layouts/video.html

remove overlay meter

---

redirects.csv

Add ?new param redirects

---

redirects.csv

Reorder ?new redirects

---

redirects.csv

Remove query param redirects

---

_assets/javascripts/components/resi-player.js

resi player should show during horse service times
Sat, 4/22 between 3pm - 6:30pm
Sun, 4/23 between 9am - 5pm
Added service times
update date time on computer before during after service times to see the resi player show hide accordingly

add horse weekend times

---

_assets/javascripts/components/resi-player.js

Reverts crdschurch/crds-net#2964

Revert "add horse weekend times"

---

redirects.csv

Test to see if adding quotes around the redirect parameters will address the issue where we needed to maintain separate lines of redirecting to match a condition.

add quotations around the cookie and status praams.

---

redirects.csv

Reverts crdschurch/crds-net#2967

Revert "add quotations around the cookie and status praams."

---

_layouts/article.html

remove the sidebar form from the articles page.

remove sidebar subscription box

---

_layouts/article.html

Reverts crdschurch/crds-net#2970

Revert "remove sidebar subscription box"

---

redirects.csv

Adjust netlify redirect to be back to two lines, remove the csv cookie configuration.

Netlify tests

---

_layouts/series.html

Prod Deploy 5/18/2023

---

redirects.csv

add redirect / proxy for annual report 2020

---

redirects.csv

testing a redirect issue

---

redirects.csv

update a couple redirects to isolate changes for netlify redirecting functionality

add role user check and update cookie check for dev.

---

redirects.csv

add redirect to new /watch

---

redirects.csv

add new redirect to new watch page

---

redirects.csv

[DEMO] add grow-guide/thank-you redirects

---

redirects.csv

add grow-guide redirects prod deploy

---

_includes/_head.html

[PROD] fix to shorten articles titles

---

redirects.csv

fix grow guide redirect

---

redirects.csv

add redirect for unified annual reports route

---

_layouts/podcast.html
brian-tome.html
media/podcasts.html

add pixel scripts to pages in task

---

_layouts/topic.html

Issue 13602 - Show thumbnail images for Podcast Episodes on Topics pages

---

redirects.csv

add redirects for annual reports & 2020 report

---

_layouts/topic.html

Prod release of fixing podcast images for the topics page.

change image source.

---

_includes/_the-basics.html

update url for annual report

---

_layouts/podcast.html
brian-tome.html

add missing hyphen

---

_includes/_head.html

add debugging statement

---

_layouts/anywhere.html
_layouts/established.html
_layouts/frontier.html

[Prod Deploy] Location Page Current Message

---

redirects.csv

add redirects for go trips

---

redirects.csv

add proxies for go trips

---

redirects.csv

add explicit go redirect

---

redirects.csv

redirects prod deploy

---

redirects.csv

add proxy for wie page

---

redirects.csv

Demo fix gotrips redirects

---

redirects.csv

add redirect & proxy for world impact experience page

---

redirects.csv

add redirects for trips

---

redirects.csv

remove -ky

---

redirects.csv

add redirects to prod branch

---

redirects.csv

add explicit redirects for partners and events

---

redirects.csv

add more redirects

---

redirects.csv

[PROD DEPLOY] add further redirects for old pages

---

redirects.csv

add redirects for gotrips pages

---

redirects.csv

add proxies for local, partners, and events

---

redirects.csv

add proxies for events, partners, local

---

redirects.csv

Happenings page redirect

---

redirects.csv

go/local  redirects

---

redirects.csv

Add /go/local landing page redirect

---

redirects.csv

add redirects for nepal & india

---

redirects.csv

testing redirects

---

redirects.csv

add auth deploy preview redirects

---

redirects.csv

add redirect for nepal & india

---

redirects.csv

Clean up redirects

---

redirects.csv

Add back happenings page redirect

---

redirects.csv

Update grow guide thank you page redirects

---

redirects.csv

post download of pdf for dpd page is redirecting to login page
add proper redirect for 
Download pdf on dpd page and check if redirect goes to thank you page

add auth redirect fr thank you page

---

redirects.csv

Adds a redirect for daily prayer devotional so that logged in users to not get redirected to the login page.

[Prod Deploy] Update dpd redirect

---

redirects.csv

remove redirect

---

redirects.csv

correct env variable

---

redirects.csv

remove / on redirect

---

_includes/_subscribe-buttons.html
_layouts/message.html
_layouts/series.html

14352 display link to messages podcast on two page types

---

media/series.html

Update App Images on the web

---

media/series.html
redirects.csv

[PROD DEPLOY] Change image on /media/series 8/15/2023

---

_layouts/established.html

---
- https://app.asana.com/0/0/1205340182683757

update established layout to remove kids and students from the tab list

---

redirects.csv

Remove slash

---

redirects.csv

Fix volunteer redirect [2]

---

redirects.csv

Remove invalid redirect, add back /go and /volunteer

---

_layouts/established.html
_layouts/message.html

Adds worship songs to the message detail page

Prod Deploy 9-14-2023

---

robots.txt

The disallow directives were blocking the home page from getting indexed
Remove the disallow lines
---
- https://app.asana.com/0/0/1205327723459438
- https://app.asana.com/0/0/1205467544430247

Remove disallow directives for home pages

---

robots.txt

Remove disallow home page lines from robots.txt

Prod deploy 9-14-2023 (update robots.txt)

---

redirects.csv

we need to block nepal & india from viewing messages
block specific message from nepal & india on series
block bluteam vision night for nepal & indiad it.*
Youll need a vpn to change your location to nepal or india to test this

block nepal & india

---

redirects.csv
robots.txt

Prod Deploy September 15, 2023

---

_layouts/default.html
_layouts/default_footer_flush.html
_layouts/no-header-no-footer.html

remove  old user way instance
removed
userway widget should be removed in demo when this is merged

remove static userway implementation

---

redirects.csv

add clips proxy

---

media/weekend-follow-up.html

change weekend follow up banner

---

_layouts/default.html
_layouts/default_footer_flush.html
_layouts/no-header-no-footer.html
media/weekend-follow-up.html
redirects.csv
robots.txt

removing userway from demo env

Prod Deploy September 26, 2023

---

redirects.csv

Move _next redirects to top of file

---

media/weekend-follow-up.html
redirects.csv

10/02/2023 Prod Deploy (Next Proxies)

---

redirects.csv

add explicit /go redirect

---

redirects.csv

add wildcard

---

redirects.csv

Testing Go proxies fix

---

redirects.csv

Add explicit go trips proxy

---

_layouts/article.html

Add Hubspot form to article page layout

---

_layouts/article.html
redirects.csv

- Adds Hubspot form to article page template

Prod deploy 10-11-2023

---

_plugins/hooks/ig_images.rb

Adds a hook that fetches the latest 10 images from the crsrdscamps Instagram API (basic display).

Camps Instagram Carousel

---

_layouts/article.html
_plugins/hooks/ig_images.rb
redirects.csv

October 13, 2023 Prod Deploy

---

_layouts/collection.html

[Asana](https://app.asana.com/0/1201454420722044/1205668376569410/f)
- Add optional playlist button in jumbotron.
- Add `playlist_url` prop in Contentful
[Deploy preview](https://deploy-preview-3163--demo-crds-net.netlify.app/media/collections/realencounters)

Add playlist button to Collection

---

redirects.csv

Add redirect for thanksgiving-food-drive

---

redirects.csv

Create a redirect for the new prayerexperience page for Real Encounters.

add redirect for prayer experience.

---

_layouts/collection.html

[Deploy Preview](https://deploy-preview-3170--demo-crds-net.netlify.app/media/collections/realencounters)

add signup banner for real encounters

---

_layouts/collection.html
redirects.csv

10/19/2023 Prod Deploy Real Encounters Banner

---

_includes/_bitmovin-player.html

Updates the video-id field to be the value of the contentuful system Id of the video.

Defect: Contentful Entry Id's

---

redirects.csv

Add redirect for `/happy-thanksgiving`
- https://github.com/crdschurch/crds-unified/pull/1017

Add redirect for Happy Thanksgiving

---

_includes/_bitmovin-player.html

Reverts crdschurch/crds-net#3173

Revert "Defect: Contentful Entry Id's"

---

_layouts/collection.html

Crds had urgent edits needing done for the Real Encounters page.
Styling and markup changes to address then edits asks.
Check the code to make sure it looks alright and make sure the page looks okay.

real encounters edits

---

_layouts/collection.html

move trailer btn to the left

---

redirects.csv

Add /cgd to redirects 
- https://github.com/crdschurch/crds-unified/pull/1040

Set up /cgd redirect

---

redirects.csv

We need to proxy the crds-unified womens retreat page to the crds-net site.
Add a proxy to the redirects.csv file for womens retreat.
https://github.com/crdschurch/crds-unified/pull/1044

Add proxy for womens retreat

---

redirects.csv

remove cgd proxy for now.

---

redirects.csv

Given I am a CR community member
When I navigate to Crossroads.net/mycamps
Then I will have the same experience as when I navigate to My.Crossroads.net/mycamps.

US23999 - Added redirect for mycamps to rock domain

---

redirects.csv

Return the cgd proxy

---

redirects.csv

11/07/2023 Prod Deploy

---

redirects.csv

`happy-thanksgiving` goes to a 404 page
Add proxy to redirects.csv
---
- https://app.asana.com/0/0/1205925559463238

add proxy for happy thanksgiving

---

redirects.csv

Happy Thanksgiving Proxy Prod Deploy

---

_layouts/frontier.html

Add Kiefer Reyes to "the team" section

Add Kiefer Reyes to "the team" section

---

_layouts/article.html

Remove Prefooter HS form

---

media/index.html

Remove Prefooter HS form from media page(s)

Remove Prefooter HS form from media page(s)

---

_layouts/article.html
_layouts/frontier.html
media/index.html

https://github.com/crdschurch/crds-net/pull/3213#issue-2038627623
https://github.com/crdschurch/crds-net/pull/3212#issue-2038620787

Prod deploy 12-13-2023

---

_layouts/default.html

userway is loading on the christmas vr page and that's problematic due to the vr experience being hindered in the browser. 
add conditions so that userway does not load on the christmas vr page

add exception for pages loading userway.

---

_layouts/default.html
_layouts/no-header-no-footer.html

Removes the userway widget from the christmas-story page on crds-net.

Uuserway removal christmas-story

---

_layouts/collection.html

Deploys:
- Real encounters pages updates

[Prod Deploy] 12/21/23

---

_includes/_head.html

Hard-codes demo components for testing purposes.

Temporarily use demo crds-components

---

_includes/_columbus-top-section.html

change "Connect With Us" section to reflect text-in updates and weekly emails

Update "Connect With Us" section

---

_includes/_columbus-top-section.html

copy changes for the Text/Weekly Email section

copy changes for the Text-In/Weekly Email section

---

_includes/_columbus-top-section.html

Update image for Text-In/Weekly Email section

Update image for Text-In/Weekly Email section

---

_includes/_columbus-top-section.html

Get Sarah H changes into prod without bringing in work in demo for testing.

1/4/2024 Prod Deploy

---

_includes/_location-info.html

New Building Modal and Btn

---

_includes/_location-info.html

add copy to new building modal

add copy to new building modal

---

_includes/_location-info.html

Change text color of new building modal

Change text color of new building modal

---

_includes/_annual-reports.html
_includes/_head.html
_includes/_location-info.html

Reverts crdschurch/crds-net#3241

Revert "1/12/2024 Prod Deploy"

---

_includes/_annual-reports.html
_includes/_head.html
_includes/_location-info.html

Reverts crdschurch/crds-net#3243

Revert "Revert "Revert "1/12/2024 Prod Deploy"""

---

_includes/_location-info.html

Dayton New Building Modal Prod Deploy

---

_includes/_head.html
_plugins/hooks/config.rb

add import statements dynamically

---

_includes/_head.html
_plugins/hooks/config.rb

Generate prod deploy preview

---

netlify.toml

Deploys:
- removal of health check plugin for Netlify build version change.

[Prod Deploy] 01-29-24

---

netlify.toml

add health check plugin back to config

---

_includes/about/_leadership.html

Update Kyle's headshot

---

_includes/about/_leadership.html

Prod Deploy 2-1-2024

---

_includes/about/_leadership.html

Prod deploy 2-8-2024

---

_layouts/article.html

https://app.asana.com/0/1201454665996628/1206362955395003
Include weekly banner to article page
Preview - https://deploy-preview-3261--demo-crds-unified.netlify.app/media/articles/my-last-conversation-with-my-young-life-leader

weekly banner article page

---

_assets/stylesheets/pages/_media-homepage.scss
media/index.html

https://app.asana.com/0/1201454665996628/1206362955394987
Include weekly banner in media homepage
Preview - https://deploy-preview-3260--demo-crds-unified.netlify.app/media/

add weekly banner to media homepage

---

_assets/javascripts/components/chat.js

Add logging for Intercom widget

---

bin/update-image-urls.sh

Revert our memories image changes

---

_layouts/anywhere.html

Update anywhere team

---

_includes/_columbus-top-section.html

Fix columbus specific service time issue
copy liquid code used in the main location template in the columbus specific file.

port code into columbus specific html file

---

_includes/_columbus-top-section.html

Hotfix for Columbus page service times

---

_layouts/anywhere.html

Add Cristin Fissinger to Anywhere Team

Add Cristin Fissinger to Anywhere Team

---

_layouts/anywhere.html

New members needed to be added to the Crossroads anywhere team.
Add new html block containing information for new team member

[Prod Deploy] Add new anywhere team member

---

_includes/_location-info.html

Add Dayton Building Button

---

_includes/_location-card.html

Add Dayton building button to /locations

Add Dayton building button to /locations

---

_includes/_location-card.html

Update Dayton new building modal

---

_includes/_location-card.html

Move new Dayton location modal to Contentful

---

_includes/_location-card.html

Moves the Dayton new location modal markup & script into the `/locations` Contentful page

Dayton location modal fix

---

_includes/_media-card.html
_plugins/generators/collected_documents.rb
brian-tome.html

[Asana Task](https://app.asana.com/0/1201454665996628/1206757340158778)
- In brian-tome.html
- Added nil check for article.author.full_name where iterating articles
[/brian-tome](https://deploy-preview-3287--demo-crds-jekyll.netlify.app/brian-tome/)

Added null check for author

---

_layouts/established.html
_layouts/frontier.html

Prod deploy (Adjust display logic for email button in 'About Crossroads Students')

---

_layouts/default.html
_layouts/podcast.html

[Pixel changes for Spanish OTT Campaign](https://app.asana.com/0/1202525367528099/1206803097183904/f)
-  added to unified https://github.com/crdschurch/crds-unified/pull/1383

Pixel changes 

---

_assets/stylesheets/pages/_message.scss
_assets/stylesheets/pages/_modules.scss
_layouts/message.html

Reverts crdschurch/crds-net#3297

Revert "Feature Spanish Video Player"

---

_layouts/established.html

Add Plan Your Visit banner

---

_includes/_subscribe-buttons.html
_layouts/frontier.html
_layouts/podcast.html
_layouts/series.html

Prod Deploy April 4, 2024

---

_config.yml
_includes/_columbus-top-section.html
_includes/_location-card.html
_includes/_location-info.html
_layouts/location.html
_plugins/generators/location_service_times.rb

change to serviceTimes in config

---

_includes/about/_leadership.html

Edit/Add people to /about

---

_includes/about/_leadership.html
bin/update-image-urls.sh

About page is out of date with most current staffing and leadership information
Update that information to reflect accurately on the leadership page.

[Prod Deploy] 05-02-2024

---

_assets/javascripts/components/chat.js

Updates `console.log` to `console.warn` when Intercom is undefined

Update chat.js script logging

---

_layouts/article.html

Ticket - [link](https://app.asana.com/0/1201454665996628/1207152060357880)
Added value to `appcta` attribute in `crds-weekly-banner` in `article.html` to show the download app button.
PR in components repo with banner changes - [link](https://github.com/crdschurch/crds-components/pull/2104)

Add appcta value to crds-weekly-banner

---

_layouts/series.html

Reverts crdschurch/crds-net#3345 accidental merge

Revert "Update student ministry series breadcrumbs"

---

_includes/about/_leadership.html

[Asana Task](https://app.asana.com/0/1198951831278010/1207591243287130/f)
Update leadership pictures /about
[Deploy Preview](https://deploy-preview-3351--demo-crds-jekyll.netlify.app/about)

Update leadership pictures /about

---

_includes/about/_leadership.html

Update leadership pictures /about
[Deploy Preview](https://deploy-preview-3354--crds-jekyll.netlify.app/about)

Prod deploy 6-28-2024

---

_includes/_location-info.html
_layouts/established.html

Userway issue - same ID for two different modals
[Task](https://app.asana.com/0/1201454665996628/1207497922910223)
- changed the ID to one of the modals and changed the data-target attr for the buttons triggering the modal

Changed the IDs of subscribe modal and data-target id for the buttons

---

_layouts/anywhere.html

add griff ray to anywhere team

Add Griff Ray to Anywhere Team

---

_includes/about/_leadership.html

Update Leadership photos

---

_includes/about/_leadership.html
_layouts/anywhere.html

Prod Deploy 7/23/2024

---

_includes/_location-info.html
_layouts/frontier.html

https://app.asana.com/0/1198951831278010/1208493958241732/f

Dayton Signup Link Changes

---

media/series.html

series with transparent background image and white text is hard to see
add a gradient to the background temporarily to enable the white text to be legible.

add background gradient to feature image:

---

_layouts/frontier.html

Fix Dayton info on Columbus page

Fix Dayton info on Columbus page

---

_includes/_head.html

add back segment script

---

_layouts/message.html

youtube spanish video functionality

---

_layouts/message.html

overlap sound fix

---

_layouts/message.html

spanish message toggle not properly toggling the spanish video to play.

fix spanish message toggle

---

_layouts/message.html

---
- https://app.asana.com/0/0/1210035587127817

autoplay on initial load

---

_layouts/episode.html

---
- https://app.asana.com/0/0/1210051046797166

add youtube to episode page

---

_layouts/author.html

add console logs

---

_layouts/message.html

Reverts crdschurch/crds-net#3453

Revert "autoplay on initial load"

---

_includes/about/_faqs.html
_includes/about/_leadership.html

add new question / description to top of FAQ section
did that
[deploy preview](https://deploy-preview-3461--demo-crds-jekyll.netlify.app/about)
scroll to FAQ section. click top link you should scroll to corresponding answer

update faq section

---

_layouts/article.html
media/authors.html

---
- https://app.asana.com/0/0/1210368925707338

fix links in bio

---

_includes/about/_leadership.html

[Task](https://app.asana.com/1/37330734394864/project/1201454665996628/task/1210870089479571?focus=true)
[Deploy Preview](https://deploy-preview-3478--demo-crds-jekyll.netlify.app/about)

Add Nakita to /about

---

_layouts/article.html

update to add more logs.

---

_assets/javascripts/components/popup-modal.js
_layouts/article.html

[Prod Deploy] debugging prod env

---

_includes/_article-social-share.html

[prod deploy] Social share links

---

_includes/about/_leadership.html

Need to update Joel's new title on [crossroads.net/about](http://crossroads.net/about)! It should say "Next Gen Director" on his picture (not director of 0-18)
[Deploy Preview](https://deploy-preview-3502--crds-jekyll.netlify.app/about)

Update Joel's title
