crdschurch/crds-net

_layouts/default.html, _plugins/filters/html_and_meta_util_filter.rb, lib/utils/meta_util.rb, locations.html, spec/unit/meta_util_spec.rb
Description of changes in the commit comments.
=> De5734 markdown showing in meta description

live.html
-Made title a link
-removed uppercase class and used liquid upcase instead
-pulled series title using message slug
=> Address defect introduced in /live conversion

_assets/stylesheets/pages/_live.scss
Style wasn't present on live page.
=> Added styling for 'Remind Me' button for hover color

_includes/_head.html
...of rendering responsibility.
=> Adding Netlify meta data tag for clarity

redirects.csv
Append splat to proxied routes
=> DE5822 API & Gateway Proxies

Gemfile, Gemfile.lock, _config.yml
update Jekyll Contentful + config changes
=> US1483: Promo Migration

_config.yml, _plugins/hooks/has_many.rb, lib/crds/has_many.rb, live.html
Setup associations for series/messages
=> DE5787 HasMany

Gemfile.lock, _assets/javascripts/application.js, _layouts/default.html
Moved reference to set-redirect-url.js to the application.js since it's needed for every page load
will use the same logic for the Media project
=> refactor of redirection script reference

_assets/javascripts/lib/set-redirect-url.js
Taylor bought up a good point. Path should be path so it's more browser agnostic.
=> Small change to redirectUrl cookie js

Gemfile, Gemfile.lock, _config.yml
use placeholdes to expose permalink instead of slug
=> DE5840: Slug => Permalink

redirects.csv
Add slammers to proxy rules so proxy is handled by Netlify's CDN, per Netlify support team
=> USXXXX Proxy Performance

Gemfile, Gemfile.lock
Use forked version of jekyll-crds
=> DEXXXX Production ENV Vars

Gemfile, Gemfile.lock
=> DEXXXX ENV Vars Prod

redirects.csv
Setup redirect for /undivided-training
=> USXXXX Undivided Training

redirects.csv
Setup redirect for /undivided-training per @adamtgeorge
=> [hotfix/demo] Undivided Training Redirect

redirects.csv
Setup redirect for /undivided-training per @adamtgeorge
=> [hotfix/www] Undivided Training Redirect

live.html
=> DEXXXX: Remove Media Snippets

_assets/stylesheets/_utilities.scss, updates.html
* add /updates
* still has some `imgix` flashing, need to discuss how to fix this in DE5757
* all external requests are `https`
=> US14960: Updates Page

lib/crds/has_many.rb, netlify.toml
edited the .toml to get only what we need.
=> US14967: Restrict content from CMS

.gitignore, _includes/_footer.html, _includes/_shared_global_header.html, _plugins/hooks/purgecss.rb, netlify.toml
=> US14968: Purgecss

_plugins/hooks/purgecss.rb
add visible to purgecss whitelist
=> DE5895: Watch Now Button

_layouts/location.html
=> DEXXXX: Location Promos

_layouts/location.html
Just copied the Uptown video section and tweaked it for Oxford.
=> Add Oxford videos

stream.html
- added square placeholders
- changed button styling in contentful
=> DE5866: Be The Church

_config.yml, the-chaser.html
Adam and I worked on adding the chaser page to www. We will want to back merge this into demo, int.
Work done: 
- + discussions collection so we could query for questions
- + chaser page with liquid for weekend date and dynamically served questions from latest message
=> Dynamic Chaser Page

Gemfile, Gemfile.lock
Update crds-styles.
Note: The actual fix was here: https://github.com/crdschurch/crds-styles/pull/332
---
This also covers DE5929, which was introduced into crds-styles here: https://github.com/crdschurch/crds-styles/pull/333
=> DE5928 - Card Title Coverup

live.html
=> DE5901: Live Page Connect Section

_assets/stylesheets/pages/_live-stream.scss, stream.html
- removed giving widget
- added css to adjust card sizes and hide controls on large screens
=> US14804: Pushpay Link

_config.yml
=> DE5948: Ordering Promos

_includes/_promo-card.html, stream.html
=> DE5961: Imgix Size

_assets/javascripts/application_deferred.js, _assets/javascripts/components/legacy-imgix.js, _includes/_current-series.html, _includes/_footer.html, _includes/_shared_global_header.html, _layouts/location.html, live.html
just some js that loads some other js if it lacks said js.
U kno, just js...
=> DE5941: Legacy Imgix Support

redirects.csv
Apply 301 instead of 200! due to redirect loop issue
=> US15178 The Chaser

live.html
update imgix params to find faces
=> DE5901: Connect Section Images

Gemfile, Gemfile.lock, _assets/javascripts/application_deferred.js, _assets/javascripts/lib/height-watcher.js, _assets/javascripts/views/live-stream.js, _includes/_shared_global_header.html, _layouts/default.html, stream.html
- add script from maestro
- dynamically switch streamspot player in each environment
=> DE5966: Height Watcher

Gemfile, Gemfile.lock
=> US15236: Update Jekyll

_layouts/default.html
add conditional logic to default template
=> US15255: Redirect Unauthenticated Users

lib/crds/redirect_writer.rb, redirects.csv
=> DE5998 - 301 to HTTPS

live.html
include amazon fire stick & alexa. remove smart TVs
=> update "ways to watch"

_assets/javascripts/application_deferred.js, _assets/javascripts/lib/smooth-scroller.js, _assets/javascripts/views/live.js, _layouts/location.html
added button to locations layout, also made smoothscroller available to all pages
=> locations happenings button content change

_assets/javascripts/application_deferred.js, _assets/javascripts/lib/smooth-scroller.js, _assets/javascripts/views/live.js, _layouts/location.html
added button to locations layout, also made smooth-scroller available to all pages
=> button addition for locations

_layouts/no-header-no-footer.html
add basic no header no footer layout
=> US15285: No Header Layout

_assets/stylesheets/pages/_forms.scss, _assets/stylesheets/pages/_go-trips.scss, _assets/stylesheets/pages/_groups.scss, _assets/stylesheets/pages/_modules.scss
+ move groups, go-trips, and forms scss
=> US15378: Maestro CSS

_layouts/container-fluid.html, _layouts/container.html, _layouts/eight-column.html
added </br> to all layouts that have a footer to create proper padding. Will require each new layout we add to have this </br> tag added.
=> DE5945 footer spacing issue

_assets/javascripts/views/live.js
- improved regex to accommodate all forms of youtube link
=> DE5963: YouTube Modal

_assets/javascripts/views/family-meeting-stream.js, family-meeting-stream.html
it needs to point/replace current:
crossroads.net/family-meeting-stream
=> Add Family Meeting Stream

_layouts/container-fluid.html
=> DEXXXX: Container Fluid

Gemfile, Gemfile.lock
Bump jekyll-cloudsearch to latest version
=> DE6041 Search Results

_assets/javascripts/application_deferred.js
move imgix js higher in bundle to avoid race condition
=> DE6083: Promo Heights

_pages/groups-getting-started.html, _pages/groups-in.html, _pages/groups-out.html, _pages/groups-up.html
remove filter buttons + sidebar column fix
=> DE6132: Groups Layout

README.md
add contribution tips + meta data
=> US15668: Update Documentation

redirects.csv
redirect /angel-tree/to christmas-gift-drive
=> [MASTER] DE6146: Angeltree Redirects

_layouts/location.html
=> change link for Andover

redirects.csv
redirect /angel-tree/to christmas-gift-drive
=> [RELEASE] DE6146: Angeltree Redirects

_pages/four-year-olds---full-week.html, _pages/four-year-olds.html, _pages/three-year-olds.html, _pages/two-year-olds.html
=> DE6144: Hide Registration Buttons (Preschool)

Gemfile, Gemfile.lock, _assets/stylesheets/components/_cards.scss, _pages/serve.html
Issue:
We added this fix to the DDK but the specificity only affected `.card` classes that are nested under `.card-deck` parents. This fix will get all card text.
=> DE6137: Card Text Crop

_pages/baptism.html, _pages/co-ed-ongoing.html, _pages/oxford-onsite-groups.html, _pages/real-jesus.html, _pages/resubscribe.html
added bootstrap classes around page content to format properly
=> DE6138 Alignment issues with migrated pages

_pages/christmas-gift-drive.html
=> [hotfix] christmas gift drive changes

_pages/kentucky-refugee-ministry.html, _pages/next-big-thing-faq.html, _pages/thanksgiving-day-fall-feast.html, _pages/the-diner.html, _pages/the-outlet-at-city-gospel-mission.html, _pages/undivided-next-steps.html
- change layout
- change imgix params
=> DE6142: Misc Layout Fixes

_config.yml, _pages/kentucky-refugee-ministry.html, _pages/thanksgiving-day-fall-feast.html, _pages/the-diner.html, _pages/the-outlet-at-city-gospel-mission.html
round two, this time with parameterized imgix string
=> DE6142: Misc Layout Defects

cypress/kickOffCypress.sh
- Cypress will run as PR check against Netlify's preview builds only, unless we're building for Prod
=> shenney/CYP - Fix Travis instructions

_assets/javascripts/components/simple-fred.js
The old approach didn't take affect because it is loading after the content is already rendered. Inline styles should work better.
=> US15338: Form Styles

cypress/integration/live/live_current_series_spec.js
- Fixed a typo in the failing live_current_series_spec test & separated logic a bit
=> shenney/CYP-DE - Watch Trailer defect

lib/crds/redirects.rb, spec/unit/redirects_spec.rb
always set contentful redirects to 302
=> US15812: Contentful Cleanup

_pages/high-school.html, _pages/middle-school.html
=> hotfix - remove friendsgiving text

_pages/high-school.html, _pages/middle-school.html
=> [hotfix] remove friendsgiving mentions (release)

_pages/high-school.html, _pages/middle-school.html
=> [hotfix] remove friendsgiving mentions (master)

_layouts/location.html
• add if else statement to show different info for kids club on
georgetown
=> hotfix - christmas changes 12/05

_pages/student-ministry.html
• image & text swap on /studentministry
=> hotfix - remove friendsgiving, add next big thing

_layouts/location.html
• add if else statement to show different info for kids club on
georgetown
=> [hotfix] georgetown is offering kids club but no other site is (release)

_layouts/location.html
• add if else statement to show different info for kids club on
georgetown
=> [hotfix] georgetown is offering kids club but no other site is (master)

_layouts/location.html
• florence was 9am, is now 9:30am
• georgetown was 11:30am, is now 11:00am
=> hotfix - service time fix (georgetown/florence)

_layouts/location.html
• florence was 9am, is now 9:30am
• georgetown was 11:30am, is now 11:00am
=> [hotfix] fix service times - florence & georgetown (release)

_layouts/location.html
• florence was 9am, is now 9:30am
• georgetown was 11:30am, is now 11:00am
=> [hotfix] fix service times - florence & georgetown (master)

_config.yml, index.html
• update config file to point to correct pathway
=> fix int home page

index.html
Temporarily replaces inline video with video modal
=> DE6186 Jumbotron Inline Video Style Issues

_pages/christmas-gift-drive.html
• make East Side say it doesn’t need volunteers anymore. it’s full
=> hotfix - christmas gift drive update

_pages/family-convo.html
• this gets updated every week!
=> hotfix - update family convo

_pages/marketing.html
=> hotfix - marketing page update

_pages/marketing.html
=> hotfix - marketing page fix

index.html
**Problem**
Topic cards are being shown in a vertical column
**Solution**
Remove img optimization on these until Sean can fix main defect
=> DEXXXX: Home page topic cards

_pages/kids-club.html
• add serve link for downtown lex
=> hotfix - serve / kids club

_assets/stylesheets/application.scss
=> DEXXXX - Glyphicons Not Working

Gemfile, Gemfile.lock, _config.yml, package-lock.json, robots.txt
=> US15314 Sitemaps

.github/PULL_REQUEST_TEMPLATE,md
It's pretty much the wild, wild west out here with PRs. Context would be nice.
This PR template. Duh.
N/A
You are testing this right now by reading it. Thanks.
=> USXXXX: Pull Request Template

.travis.yml
- Removed all branch blacklist so Travis will run tests again
=> feature/US15755 - Fix caching config

live.html, locations.html
• edit times on /live
• edit times on /locations for anywhere
=> hotfix - edit streaming times

_pages/man-camp-its-gonna-be-hard.html, _pages/man-camp.html, _pages/summer-camp.html
• add new blog page
• add blog reference on /mancamp
• edits to student camp
=> hotfix-MC-camps-update

index.html
…them apart from message code on same page, this should address issues with travis builds
=> Cypress fix for duplicate automation ids

_includes/_location-card.html
fixes an issue stakeholders are having in prod
=> DE6243: Markdownify Location Text

_plugins/hooks/cloudsearch.rb
Ensure we don't try to set an instance variable on a nbil object
=> DEXXXX Cloudsearch

_plugins/hooks/cloudsearch.rb
Nuclear option: disable all cloudsearch stuff unless explicitly enabled
=> DEXXXX Frozen NilClass

_layouts/location.html
• reused Luke JS
• lives under happenings
=> hotfix - add form to site pages

_assets/javascripts/components/simple-fred.js
added a wrapper function to make sure simple-fred tag gets wrapped in a <p> tag
=> DE6240 Simple-Fred must be inside <p>

_assets/stylesheets/_fonts.scss, _layouts/location.html
• remove Christmas banners from location pages
• remove sign up to serve btns
=> hotfix - remove Christmas

_assets/stylesheets/components/_hubspot-forms.scss
fixed selector on style sheet to match a previous change to locations hubspot form
also made previous width fix more specific so that it won't affect any other hubspot forms we might be using
=> DE6253 selector incorrect

_pages/big.html, _pages/student-ministry.html, _pages/wayfinder-leader-resources.html, _pages/your-role.html
• update /big to look before christmas event
• remove NBT from /studentministry
• update wayfinder w/ new link to revised PDF
• update text on /your-role page
=> hotfix - 4 changes

_assets/stylesheets/pages/_go-trips.scss
When removing a hotfix file during cleanup, I accidentally removed some scss affecting trips maps
added it back into the project in the correct scss file.
n/a
n/a
=> DE6256: Trips SCSS

netlify.toml
=> fixing group leader proxy for prod

netlify.toml
=> fixing proxy for prod

_pages/go-local.html, _pages/preschool.html
=> hotfix - golocal and preschool

_pages/go.html
Front matter was undefined so page was falling back to maestro
`undefined` to `layout`
=> DEXXXX: Go Layout

_pages/go.html
=> [hotfix] DEXXXX: Go Layout (master)

_pages/go.html
=> [hotfix] DEXXXX: Go Layout (release)

_includes/_trip-grid.html, _layouts/location.html
• list KC, FI serve links
• FB event links
• service times
• hide may trip 2
=> Super Bowl location specific items

_includes/trips/_trips-footer.html, _includes/trips/_trips-header.html, _layouts/trips.html
Trips pages have a ton of duplicate html in regards to the header and footer
Create trips header and footer includes as well as a layout for content team to leverage to reduce duplication and complexity
=> added new header, footer, and layout for trips

netlify.toml, redirects.csv
=> US15897 - Adding groups/search redirect. Fixing group leader envs.

_layouts/location.html
=> [hotfix] Remove > Typo Release

_layouts/location.html
=> [hotfix] Remove > Typo Master

_includes/_trip-grid.html
• fixed alignment for all trips page
=> fix for all trips page

_includes/_trip-grid.html
_trips-grid.html has gone missing
added _trips-grid.html back
=> adding _trips-grid.html back to release

_includes/_trip-grid.html
=> updated trips-grid.html to match dev/release

redirects.csv
=> maestro removal rollback

_layouts/location.html
• edit oxford hours
• edit community care section
=> hotfix - edit community care

_layouts/location.html
• edit oxford hours
• edit community care section
=> edits to location (add lexington)

Gemfile, Gemfile.lock
moving to one space in contentful requires us to make jekyll-contentful/cloudsearch environment aware
updated gem versions for jekyll-cloudsearch and jekyll-contentful
=> DE6280 Meta References

redirects.csv
sign out doesnt work
redirect signout to crds-angular
=> US15701 - REmove Maestro Redirect - Signout Redirect to angular

_layouts/location.html
=> [release] edit community care section

_layouts/location.html
=> [master] edit community care section

redirects.csv
Adding giving and serve redirects
=> US15701-Remove-Maestro-Redirect

redirects.csv
giving link not working
adding redirect for /me/giving
=> US15701 - /me/giving redirect

redirects.csv
giving redirects infinite loop
play with redirects
=> US15701 - giving redirects

_assets/javascripts/lib/card-filters.js
didn't solve spacing issue before with drop down and happenings text
added push-half-left to create proper spacing
=> added class to card filters to give drop down more space on mobile

netlify.toml
Env var missing for serve endpoint 
add env var for serve endpoint
=> US15701 - Remove Maestro - Serve Endpoint Env Var

_assets/javascripts/components/countdown.js
new javascript is causing error on pages
switch from JS to jQuery
=> DE6331 - homepage JS error

netlify.toml, redirects.csv
Giving Redirect Infinite Loop
Point to netlify profile endpoint
=> US15701 - Remove Maestro - Giving Redirects

_layouts/location.html
=> update west side FB event

_layouts/location.html
=> hotfix - columbus ss

_layouts/location.html
=> add columbus sign up to serve

live.html
…ded hide class
the "remind me" button is stacking on mobile, this was introduced with US16288
move remind me back out of the div for separation and hide it by default as well
=> DE6335 - remind me wrapping

redirects.csv
404 on camps/:campid/family routes
Add wildcard for camps
=> adding wildcard so all routes after that are also redirected

_includes/_trip-grid.html
• blocked out bolivia motorcyle trip
=> update-trip-grid (release)

_includes/_trip-grid.html
• blocked out bolivia motorcyle trip
=> update-trip-grid (master)

_includes/_trip-grid.html
• Blocked out week 1 Puerto Rico trip.
=> blocked-out-trip

_assets/stylesheets/pages/_live.scss
jumbotron styling added wasn't scoped properly
scope it properly
=> DEXXXX - live jumbotron style scoping

.travis.yml, cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js, cypress/kickOffCypress.sh
*A set of tests weren't using the defined test user.*
*There's a big modal in /camps that's blocking the profile icon.*
*Send the password variable to Travis.*
*Skip the /camp test until we can work around the modal better.*
=> [CYP] Authenticated test fix

_includes/_trip-grid.html
• blocked out a trip to Durban that is full
=> blocked-out-durban-trip

_includes/_trip-grid.html
• Blocked out another Durban June trip.
=> trip-grid-june-pull-off

_includes/_trip-grid.html
=> trip grid change (master)

cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js
Increased the max load time for some pages so tests won't fail because the page wasn't loaded.
=> [CYP] Increased more timeout times

_plugins/hooks/systempage.rb
Rescue exception related to system pages.
=> DEXXXX System Pages

_includes/_trip-grid.html
• changed out an image for joberg trip
=> image-change-for-south-africa

_includes/_trip-grid.html
• blcoked out June Nicaragua trip from grid.
=> pull-june-nicaragua-trip

_includes/_reachout-google-map.html, _includes/_trip-grid.html
Trips grid is referencing the variable at the page level
reduce it to the "local" level
=> updated trips grid js to look at local lat and long versus page level

.gitmodules, netlify.toml
Using _pages to dynamically add pages to all three environments
remove _pages
=> removed _pages submodule

_includes/_reachout-google-map.html
=> changed scope of zoom jekyll variable

_includes/spark/_allgotrips.html
/spark/ is over the 50000 character limit for Contentful
added include for all the season talks to reduce /spark size for contentful
=> Add include for the talks that will need updated yearly

_layouts/location.html
=> hotfix - community care fix

_layouts/default.html
masonry_js doesn't load what pages that require it are in contentful
drop the liquid required to add the javascript directly into contentful and remove logic from crds-net
=> removed masonry logic, will be moved to the html directly

_includes/_trip-grid.html, _layouts/location.html
• Changed serve to volunteer
• added new Puerto Rico trip to the grid.
=> locations-trips-changes

_assets/javascripts/lib/data-tracker.js
Expose labels in `data-tracker` so we can customize what is sent to Astronomer via data-* attributes.
=> US15395 Giving Analytics

redirects.csv
/sign-up and /volunteer-sign-up are producing infinite loops, added redirects to mitigate infinite loop for pages that don't actually exit
Add redirects to 404
=> DE6478 sign-up and volunteer-sign-up infinite loops

_includes/_head.html, redirects.csv
=> changed redirect to go to /404 and not the application

_assets/javascripts/lib/data-tracker.js
=> change variable back

README.md, _assets/javascripts/lib/data-tracker.js
Cleanup regression in data-tracker.js
=> DEXXXX - DataTracker 

_config.yml
=> [int] upped limit on series

_assets/javascripts/components/smart-banner.js, _assets/stylesheets/vendor/_smart-banner.scss
Didn't show smart banner for non-safari iOS users
show it
Also added minimal click tracking
=> US16167: Smart Banner

_config.yml
=> [production] Hotfix/mas series issue

_config.yml
=> [demo] upped limit on series

_layouts/location.html
currently difficult to manage in crds-net repository
added feature_section to show if it exists in contentful
https://github.com/crdschurch/crds-contentful-migrations/pull/101
=> US16365 add feature_section to locations in contentful

_assets/javascripts/components/smart-banner.js
I messed up the logic for the user agents.
Added another use case to catch all non-safari browsers including chrome on ios
=> US16167: Mobile Smart Banner

README.md, redirects.csv
want to use appEndpoint url in shared header to fetch correct env search component
add redirect for search component
=> adding search component redirect.

_includes/_locations-grid.html
• changed prison links from "Serve" to "Volunteer"
=> [development] changes to locations grid

_includes/_locations-grid.html
• changed prison links from "Serve" to "Volunteer"
=> [master] changes to locations grid

cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js, package-lock.json
- Cross-origin exception catcher didn't know the exact error that was being caught, now it does.
=> [CYP] - Updated cross-origin exception catch

redirects.csv
=> added wildcard redirects back

cypress/Contentful/Models/MessageModel.js, cypress/Contentful/Models/SeriesModel.js, cypress/integration/external_repo_media/landing_page_current_series_spec.js, cypress/integration/external_repo_media/series_page_current_series_spec.js
- The https:// prefix for the CRDS_MEDIA_ENDPOINT environment variable was removed.
- Added https:// prefix to media url references in all tests
=> [CYP] - Added https prefix to Media url references

_config.yml, _includes/media/_overlay-card.html, index.html
Add featured media to home page.
This should follow the same approach as crds-media's home page
add featured media, songs and videos from Contentful
add featured media to homepage
use 'site' field from Contentful to pull in featured media
https://github.com/crdschurch/crds-media/pull/547
https://github.com/crdschurch/crds-contentful-migrations/pull/102
=> us16605 add feature content section to homepage

spec/vcr/contentful/redirects.yml
=> updated vcr

_includes/_trip-grid.html
Added a trip and pulled off five other trips
=> trip-grid changes and additions

redirects.csv
Add redirect for discipleship.crossroads.net.
=> US16832 Discipleship Redirect

_includes/_trip-grid.html
added a medical trip to the grid.
=> added trip to grid

Gemfile, Gemfile.lock
Builds are failing due to out of date jekyll-contentful gem
update gem
=> updated jekyll-contentful version

_plugins/filters/html_and_meta_util_filter.rb
title for pages with matching system page should update their title to system page title
Make it do that
=> DE6644 updated get title to use match_system_page

_includes/_trip-grid.html
reworked the grid to make it by date
=> reworked the grid (JB)

_includes/_trip-grid.html
reworked the grid to make it by date
=> reworked the grid

_includes/_trip-grid.html, package-lock.json
=> fix merge conflicts

_includes/_trip-grid.html
=> revert to old grid

_assets/javascripts/vendor/ash-wednesday-experience.js
=> ash wednesday js

_includes/_trip-grid.html
• organized the trip grid to relfect proper dates as well as cleaned up blocked out code.
=> Fixed grid organization

index.html, package-lock.json
Lighthouse (and others) are hating on our homepage performance. Also the monetate Easter banner was a bit janky.
Use everything we've got to optimize imgs.
=> US16046: HP Image Sizing

index.html, package-lock.json
=> HP Image Sizing + Easter Banner

index.html
=> Easter updates

_assets/stylesheets/components/_cards.scss, index.html
=> DE6700: Topic Cards

README.md
=> Freshen Up Readme

_assets/stylesheets/pages/_community-store.scss, _assets/stylesheets/pages/_modules.scss
Add supporting styles for community store.
Test here: https://deploy-preview-854--int-crds-net.netlify.com/community-store/
=> US16904 - Community Store

.gitignore
=> added buildlog.txt to gitignore

_config.yml, index.html
=> Home Page Content Block

_assets/stylesheets/pages/_community-store.scss
This PR updates the stylesheet used by /community-store (via Contentful)
=> DE7619 Revisions

README.md
=> US16854 documented build logs

_assets/stylesheets/pages/_community-store.scss, _assets/stylesheets/pages/_modules.scss
This hotfix cherry-picks the commits that introduce styles for /community-store into the `demo` branch. Let me know if you have any questions.
=> [hotfix] Community Store (Demo)

_assets/stylesheets/pages/_community-store.scss, _assets/stylesheets/pages/_modules.scss
This hotfix cherry-picks the commits that introduce styles for /community-store into the `master` branch. Let me know if you have any questions.
=> [hotfix] Community Store (Production)

_includes/_trip-grid.html
• added a callout background and moved trip to top of the trip grid.
=> Calling out october trip

.travis.yml
- This feature was turned off in April when we ran out of dashboard storage, which auto-failed tests. Turning it back on here.
- Please ignore the failing Travis checks, this is expected and was just used for testing
=> [CYP] Reporting to Cypress dashboard

_assets/stylesheets/pages/_app.scss, _assets/stylesheets/pages/_modules.scss, package-lock.json
=> removed newApp.html and made updates to _app.scss

_config.yml, _plugins/hooks/systempage.rb, lib/utils/imgix_util.rb, package-lock.json, package.json
We were not exposing a usable image url for system page meta
system_pages.json now has useable urls for image assets
=> US17107: Update System Page Image Assets

_includes/_head.html
Adding some new og props as per FB's recommendations
=> add og:image width/height

.travis.yml, cypress/integration/homepage/home_page_current_series_spec.js, cypress/integration/homepage/home_page_happenings_spec.js, cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/locations/locations_search_spec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_authspec.js, cypress/integration/sharedHeader/crossroads_logo_redirect_spec.js, cypress/integration/sharedHeader/media_dropdown_current_series_spec.js, cypress/integration/sharedHeader/profile_dropdown_link_authspec.js, cypress/integration/sharedHeader/sign_in_and_out_authspec.js, cypress/support/commands.js
- Workarounds for DE6613 and DE6665 are not always working
- Took another workaround strategy for DE6665
- Maybe decreased the likelihood of DE6613, but not sure
=> [CYP] DE6778 - Attempted workaround fix

_config.yml
Add query to filter out excluded content from CFL payload. This is related to crdschurch/crds-contentful-migrations#121
=> US17310 Exclude Content

index.html
=> DE6819 Meta

_includes/_trip-grid.html
=> Trip Grid Update

_assets/javascripts/components/youtube.js, _assets/javascripts/config.js, _includes/media/_youtube-embed.html
what if bitmovin is goofed? we can use YT as backup
added youtube js to crds-net, added autoplay param search, created bitmovin/youtube logic
=> US17317-stream-redundancy

cypress/integration/homepage/home_page_latest_message_spec.js
- Latest message link test on the homepage now includes autoplay and volume param
=> [CYP] Latest message link update

_includes/trips/_trips-header.html
• info session to find out more
=> changed to nav item name

_includes/trips/_trips-header.html
• info session to find out more
=> [prod] changed to nav item name

_includes/_trip-grid.html
• pulled off trips that are full and fixed the dates to go chronologocal.
=> trip grid revisions

_assets/javascripts/components/smart-banner.js
Smartbanner doesn't seem to be showing up.
Simplify logic: check for all non safari browsers on small sized devices.
=> update safari logic

_includes/_trip-grid.html
• Fixed date issues and duplicate trips
• Changed out images on some trips.
=> Grid-fixes

Gemfile.lock, _includes/spark/_allgotrips.html
• deleting old talks
• updates will be coming weekly when spark launches
=> remove specific spark talks

_includes/trips/_trips-header.html
=> nav-change

Gemfile, Gemfile.lock, _includes/_head.html
Liquid is showing up in meta descriptions
Use a filter that removes liquid
=> DE6840: Remove Liquid From Meta Description

_includes/_trip-grid.html, _includes/trips/_trips-footer.html
• Blocked out Haiti from Trip Footer
• Fixed a few small issues on the trip grid
=> Pull Haiti from footer

_includes/_trip-grid.html
=> fixed trip grid

_includes/_trip-grid.html
=> removed duplicate trip

_includes/_trip-grid.html
=> fixed trip order

_includes/_trip-grid.html
=> refreshed trip grid

_includes/_trip-grid.html
• pulled new orleans off the grid.
=> pull new orleans off

_includes/_trip-grid.html
• pulled new orleans off the grid.
=> [master] pull new orleans off

cypress/integration/homepage/home_page_happenings_spec.js, cypress/integration/homepage/home_page_latest_message_spec.js, package-lock.json, package.json
- A link test checked for '?autoplay=true&sound=11' when it shouldn't
- crds-cypress-tools version issues were breaking some checks
- Fix the test and update the version
- Bonus hardening of happenings tests
=> [CYP] Fixed link validation and updated cypress-tools

Gemfile, Gemfile.lock
new patch exposes Google maps api key
=> update jekyll-crds to 1.3.4

_assets/stylesheets/pages/_live-stream.scss
=> hide seekbar on live stream

liveStreamTests/cypress/config/demo_crossroads.json, liveStreamTests/cypress/config/int_crossroads.json, liveStreamTests/cypress/config/prod_crossroads.json, liveStreamTests/cypress/integration/live_stream_message_spec.js
- streamSchedule was hardcoded to be from int - now pulled from an envvar
=> [CYP] "hotfix" to release - Encoding test fix

_includes/footer.html, _includes/header.html
- Updates crds-styles
- removes inline styles for crds-component tags
=> de6903-detached-sh-skeleton

_includes/footer.html, _includes/header.html, package-lock.json
* Cannot open profile menu or sign in on desktop on runway
* Update int.json paths to 'int' in crds-data
* Update runway components to site.jekyll env
[This PR is also part of the solution](https://github.com/crdschurch/crds-data/pull/7)
=> DE6902-profile-menu-break

_includes/_trip-grid.html
• fixed names on trips
• fixed info on a few trips
• got things in better order.
=> Changes to grid

_layouts/location.html
• merge two cards into “get connected”
• add “wayfinder”
=> add new card to "go deeper" on location detail pages

_includes/_meta-tags.html
=> adjusted title to use proper method in jekyll-crds

_assets/javascripts/components/bitmovin.js, _includes/media/_bitmovin-player.html
also PRs in CRDS-MEDIA and CRDS-Video-Service
=> adding subtitles externally and not from manifest

cypress/kickOffCypress.sh
- Left out a comma in the script to run cypress on travis
=> [CYP] Fixed script to kick off automated test

_assets/javascripts/components/bitmovin.js, _assets/stylesheets/pages/_live-stream.scss
Brian wants people to be able to stop time and pause live streamz
give the people back their pause buttons
=> add pausing feature back to live stream

_includes/media/_overlay-card.html
=> fixed path on overlay-card

_assets/javascripts/components/bitmovin.js
watermark on the chromecast
new stylesheet in AWS that allows us to overwrite that
PR in media: https://github.com/crdschurch/crds-media/pull/716
=> add chromecasting + stylesheet for live stream

_assets/stylesheets/components/_cards.scss, package-lock.json
If a user hovers on autoplay card, the subtitles jump to reveal the control bar we are hiding
Fix the subtitles to the bottom of the card
=> US7492 Prevent Hover Jank

_assets/javascripts/components/bitmovin.js, _assets/stylesheets/components/_preloader.scss, _includes/media/_bitmovin-player.html
when bitmovin loads slowly it has a weird blank space than can be confusing for the user.
Are a preloader spinner showing them we are setting up the video. Also report analytics on load times.
=> DE6912: Loading Experience

_includes/footer.html, _includes/header.html
Update prefix for header, footer, and snail trail
=> Fix header naming issue

_includes/_head.html
Use unpkg URL for crds-components@1.0.0
=> USXXXXX - Prep For Components Release

cypress/integration/404/404_spec.js, cypress/support/commands.js
- Updated an element selector after a name change
(Safe to merge into development)
=> [CYP] Fixed shared-header element selector

_includes/spark/_allgotrips.html
added grid items for season 4 of Spark.
=> Spark season 4

redirects.csv
- proxying anything on the /oktasignin* route to the okta signin project
- proxying anything on /signin* to the okta signin project
=> Routes for oktasignin

_includes/_head.html
Pull components from Netlify, respecting ENV.
=> DEXXXX Components Netlify

_assets/javascripts/lib/set-redirect-url.js
Ensure that we don't set redirectUrl cookie on Hubspot iframe.
=> DEXXXX Redirect After Signin

_assets/stylesheets/components/_cards.scss
Moving subtitles above the weird shadow that happens on hover
=> Autoplay card hovering

cypress/Contentful/Entries/ExtendedMessageEntry.js, cypress/integration/homepage/home_page_current_series_spec.js, cypress/integration/homepage/home_page_happenings_spec.js, cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/liveStream/live_stream_player_spec.js, cypress/integration/locations/locations_landing_page_spec.js, cypress/integration/locations/locations_search_spec.js, cypress/support/commands.js
- Fix tests so they don't fail if a message does not have subtitles
- Improved error handling for property undefined console errors
=> [CYP] US17630 - Fix tests - transcription is optional

Gemfile, Gemfile.lock
=> DE6995 updated jekyll crds to 1.4.2

_assets/javascripts/components/bitmovin.js, _assets/stylesheets/pages/_live-stream.scss, _includes/media/_bitmovin-player.html
Things done:
- made Bitmovin external JS synchronous
- changed the BG on live stream (slightly lighter so you can see the video loading easier)
- removed the preloader per BM's advice to make it like media
- fixed poster image so now you see a poster when available
=> DE6912: Not Loading

_includes/media/_bitmovin-player.html
=> use async if video card to prevent race condition

_includes/spark/_allgotrips.html
• added this weeks spark talks
=> new-spark-videos

_includes/trips/_trips-header.html
• pulled NOLA from the trips nav
=> Pulled NOLA from nav

_includes/trips/_trips-footer.html
=> pulled NOLA from footer

_config.yml
Update query for podcasts & episodes to exclude any flagged content.
=> US17678 Exclude Podcasts

_assets/stylesheets/components/_hubspot-forms.scss
css for hubspot forms w/ radio buttons
=> update styles for radio buttons

_includes/spark/_allgotrips.html
* added week 3 spark talks to grid
=> added new spark talks

_includes/spark/_allgotrips.html
* added week 3 spark talks to grid
=> [Production] added new spark talks

_includes/_trip-grid.html
• added two india trips for november 2020
=> additions to trip grid

_includes/_trip-grid.html
whoops! got those tiny things fixed.
=> whoops-fixes

_includes/spark/_allgotrips.html
• 18 spark talks added for this season
=> added final spark talks

_includes/spark/_allgotrips.html
=> additional spark talk added

_assets/stylesheets/_fonts.scss, cypress/integration/homepage/home_page_happenings_spec.js, index.html, package-lock.json
This PR adds the happenings component but stills needs to have the client auth lib work that will pass in the auth token.
=> US17814: Site Happenings

_includes/_trip-grid.html
simple wording change for bolivia trip.
=> Changed simple wording thing

_includes/_trip-grid.html
simple wording change for bolivia trip.
=> [master/production] Changed simple wording thing

homepage.html
=> US17625 auth check

_assets/stylesheets/pages/_kids-club.scss, _assets/stylesheets/pages/_modules.scss
• create new styles specific for /kids-club
• update modules to recognize this stylesheet
=> add styles for /kids-club

_assets/stylesheets/components/_happenings.scss
=> added css to fix skeleton page overflow

_assets/javascripts/config.js, _assets/javascripts/views/homepage-auth.js, _includes/_head.html, index.html, logged-in-homepage.html, package-lock.json, redirects.csv
We don't have a homepage for authenticated users to land on
Add javascript and html to create and support a Homepage logged in experience
HPLO is /
HPLI is /h
=> Us17935 logged in homepage

cypress/Contentful/ExtendedPromoEntry.js, cypress/integration/homepage_happenings/home_page_logged_out_happenings_spec.js
- Added test to check happening card content
=> [CYP] US17947 - Happenings card components

logged-in-homepage.html
=> duplicated skeleton look for logged in page

Gemfile, Gemfile.lock
Related PR: crdschurch/crds-media#755
=> DE7104 Album Card Image

Gemfile, Gemfile.lock
=> [hotfix/demo] DE7104 album card image :fire:

_assets/stylesheets/components/_modules.scss, _assets/stylesheets/components/_skeletons.scss, logged-in-homepage.html
=> US17934 Add Recommended Content To LIHP

_includes/_trip-grid.html
=> changed out images and dates on a couple trips

logged-in-homepage.html
=> updated component tag

_plugins/filters/in_groups_of.rb, _plugins/filters/onsite_groups_filters.rb, _plugins/generators/onsite_groups_generator.rb
Rescue nil values in groups filters & generator.
=> DE17984 Groups Build Issues

_plugins/filters/onsite_groups_filters.rb, _plugins/generators/onsite_groups_generator.rb
Cleanup regressions related to e567cd7
=> DE17984 Groups

404.html
analytics logic lives in html <script> tag
Removing javascript from 404 page and moving it to GTM
=> DE6981 analytics 404 issue

_config.yml, _plugins/generators/onsite_groups_generator.rb, onsite-groups.html
Remove OSG pages from build temporarily until we're ready to move to production.
=> [hotfix] Onsite Groups

_assets/javascripts/components/bitmovin.js
Set to 720. Looked fine on desktop. Want to merge to find out if it looks okay on mobile. Can change the filter to select a higher quality after testing.
=> setting card quality to lowest 720 bitrate

_layouts/onsite-group-detail.html
Cleanup some styles; ensure title is rendered for each meeting
=> DE7156 Group Meetings

cypress/integration/liveStream/live_stream_player_spec.js, cypress/integration/locations/locations_landing_page_spec.js, cypress/support/commands.js
- Fixed a regex extracting a youtube id that wasn't matching all valid youtube url formats
- Worked around an issue where markdown is not removed correctly from links if the link text contains a newline. This will be patched in the crds-cypress-contentful package soon.
=> [CYP] DE7144 - Fixed some text matching issues

_assets/stylesheets/pages/_kids-club.scss
=> update kc-body for mobile styles

redirects.csv
=> Remove /giving redirect

Gemfile, Gemfile.lock
need to use new jekyll-contentful 2.0 to leverage new lambda function to schedule builds for content
upgraydd to 2.0.0
=> upated to version 2.0.0 of jekyll-contentful

_assets/javascripts/config.js, _assets/javascripts/lib/auth-required.js, _includes/_head.html, _layouts/default.html, spec/vcr/contentful/redirects.yml
Reverts crdschurch/crds-net#1164
=> Revert "adding auth-required logic to redirects in redirects.rb"

_includes/_trip-grid.html
• deleted a trip
• changed a trip
• added a trip
=> trip updates

logged-in-homepage.html
=> fixed paginator slices to pull most recent

logged-in-homepage.html
=> Homepage hotfix

index.html, logged-in-homepage.html
=> Monetate hotfix

_config.yml, _layouts/onsite-group-detail.html, _layouts/onsite-group-location.html, onsite-groups.html
Ensure that all OSG pages have correct snail-trail.
=> DE7120 Snail Trail Groups

logged-in-homepage.html
=> Fix Live Stream Banner

_assets/stylesheets/components/_cards.scss
When hovering around location card on the landing page, cursor should turn to hand
Add cursor pointer to card
=> DE7247 Onsite Group

_includes/_trip-grid.html
• Changed August Mumbai Trip to May
=> Change Aug trip to May

_includes/_trip-grid.html
* Change Aug trip to May
• Changed August Mumbai Trip to May
* reverting styles
=> Change Aug trip to May (#1198)

logged-in-homepage.html
=> added tithe challenge to LIHP

_layouts/onsite-group-detail.html
- Childcare text not showing in meeting card
- Conditionally render childcare based on meeting
=> DE7262-cleanup-OSG

_layouts/onsite-group-detail.html
Ensure location is available to Liquid template.
=> DE7156 Onsite Group Meetings

netlify.toml, redirects.csv
Fix event checkin URLs for inconsistency across ENVs
=> DE7279 Event Checkin Redirects

logged-in-homepage.html
=> updated logged in homepage to use the overlay card

_includes/_location-card.html, _includes/_locations-grid.html
=> site select on /locations

_assets/javascripts/lib/distance-sorter.js, _assets/stylesheets/pages/_locations.scss, _includes/_locations-search.html
want to be able to sort cards on /locations using geolocation
use navigator.geolocation to sort the cards
=> added geo button and functionality

_layouts/location.html
• volunteer
• services
• gift drive
=> hotfix - christmas stuff on locations

_layouts/location.html
=> Hotcocoa fix christmas

_assets/stylesheets/components/_cards.scss
=> remove incorrect cursor property

_layouts/location.html
If I don't need this...please delete
=> HOTFIX-volunteer 1206

_assets/stylesheets/pages/_locations.scss
"Set my site" button should stack **beneath** "Learn more" button at/around iPad screen width.
=> Locations buttons

_layouts/location.html
Make editing special service times for locations easier and more efficient for non-technical staff by editing the content via Contentful.
Created a new special_service_times field in Contentful and data-binded it to front-end HTML in the locations template.
feature/special-service-times-for-holidays origin/feature/special-service-times-for-holidays
Local testing or on int if pushed to development branch.
=> Contentful integration for holiday special service times

_layouts/onsite-group-detail.html, _layouts/onsite-group-location.html
This PR wraps registration links in a conditional.
=> DEXXXX Groups

_layouts/onsite-group-detail.html, _layouts/onsite-group-location.html
Reverts crdschurch/crds-net#1246
=> Revert "DEXXXX Groups"

_layouts/onsite-group-detail.html, _layouts/onsite-group-location.html
This PR wraps onsite groups registration links with a conditional so they only display for meetings that have them.
=> [PROD] DEXXXX Onsite Groups Registration Links

_layouts/location.html
=> Below jumbo feature

_assets/stylesheets/pages/_onsite-group.scss, _layouts/onsite-group-location.html
The following page has a small rendering defect wherein the location cards are not clearing floats for each new row... https://www.crossroads.net/groups/oakley/
Fix cols to clear so that we had 4 to a row
[Preview](https://deploy-preview-1261--int-crds-net.netlify.com/groups/oakley/)
The way I was testing this is that I took the code for the content on prod because int does not have a lot of onsite content. So, Copy code below then find `col-md-3` and click on the three dots next to it and choose "Edit as HTML" and paste the code.
```
<div class="col-md-3">
<h4 class="font-family-condensed-extra text-uppercase">
<a href="/groups/onsite-groups/womens">
Womens AM  | Oakley
</a>
</h4>
<p class="text-gray flush-bottom small">Join a community of women from diverse backgrounds, experiences and …
```
=> DE7373 Rendering Issue OSG

_assets/stylesheets/components/_cards.scss
When hovering around location card on the landing page, cursor should turn to hand
Add cursor pointer to card
=> DE7247 Onsite Location Card

_assets/stylesheets/pages/_onsite-group.scss, _layouts/onsite-group-detail.html, _layouts/onsite-group-location.html
We need to add the day of the week to Onsite Groups meeting times [task](https://rally1.rallydev.com/#/66096747656d/detail/userstory/356181248976?fdp=true)
- [Preview Group Page](https://deploy-preview-1266--int-crds-net.netlify.com/groups/healing/severe-and-persistent-mental-illness-support-group)
- [Preview Location](https://deploy-preview-1266--int-crds-net.netlify.com/groups/uptown/)
- [Preview DE7373 Rendering Issue OSG](https://deploy-preview-1266--int-crds-net.netlify.com/groups/oakley/) cherry picked from original [task](https://rally1.rallydev.com/#/38108142417d/detail/userstory/356181248976?fdp=true)
=> Hotfix: Adds day of the week to on site group meeting times & DE7373 Rendering Issue OSG

cypress/integration/404/404_spec.js, cypress/integration/homepage/home_page_current_series_spec.js, cypress/integration/infrastructure/redirect_regression_spec.js, cypress/integration/locations/locations_current_series_spec.js, cypress/integration/locations/locations_landing_page_spec.js, cypress/integration/locations/locations_search/helpers/location_search.js
=> fix cypress location test [Master]

_layouts/onsite-group-location.html
=> [Hot Fix] US18721 OSG Add Start Date

redirects.csv
=> Hotfix De7407

_assets/stylesheets/_utilities.scss, onsite-groups.html
This PR adds linkable anchors to the OSG landing page.
=> [hotfix] US18761 Section Links (Production)

_assets/stylesheets/_utilities.scss, onsite-groups.html
This PR adds linkable anchors to the OSG landing page.
=> US18761 Section Links

cypress/integration/404/404_spec.js, cypress/integration/homepage/home_page_current_series_spec.js, cypress/integration/homepage/home_page_happenings_authspec.js, cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/infrastructure/redirect_regression_spec.js, cypress/integration/live/live_current_series_spec.js, cypress/integration/live/live_jumbotron_spec.js, cypress/integration/live/live_past_weekends_spec.js, cypress/integration/liveStream/live_stream_player_spec.js
=> fix homepage, infrastructure, live and livestream test [development]

cypress/integration/404/404_spec.js, cypress/integration/homepage/home_page_current_series_spec.js, cypress/integration/homepage/home_page_happenings_authspec.js, cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/infrastructure/redirect_regression_spec.js, cypress/integration/live/live_current_series_spec.js, cypress/integration/live/live_jumbotron_spec.js, cypress/integration/live/live_past_weekends_spec.js, cypress/integration/liveStream/live_stream_player_spec.js
=> fix homepage, infrastructure, live and livestream test

_layouts/location.html
=> fix downtown lex care link

_config.yml, _includes/_trip-card.html, package-lock.json
Adding 'Trips' as a content model and the include for trip cards
=> Trips content model

_includes/_trip-card.html
=> add text transform to handle compound country names

_assets/stylesheets/pages/_locations.scss
Styles in the locations.scss were being applied to all crds-button components within crds-net
Adding an ID in locations.scss to scope the styles to /locations
=> location style fix

_includes/_trip-card.html
replacing <a> button with crds-button component
=> switch to using button component

_includes/_trip-card.html
=> fix button/image link

redirects.csv
=> removed /connectv2

_includes/header.html
On crossroads.net/groups, we need to remove the snail trail. 
In order to remove we will need to update the snail trail drop down in Contentful to have an option for "no snail trail"
[Preview](https://deploy-preview-1306--int-crds-net.netlify.com/groups2/)
[Migration PR for this to work on contentful](https://github.com/crdschurch/crds-contentful-migrations/pull/184/files)
=> US18837 Snail Trail Disabled

_layouts/onsite-group-location.html
US18783 To Master
[Original PR for US18783](https://github.com/crdschurch/crds-net/pull/1292)
=> US18783 to Master

index.html, logged-in-homepage.html
adding ID's for phantom lake CTA
=> Phantom lake

_includes/media/_album-card.html
=> fixing broken music links

_includes/explore/_explore-resources.html
Add Columbus map location icon and name to BG graphic on /explore.
Added Columbus map location icon and name to BG graphic.
Updated legacy stylesheet definitions for Explore.html
Targeted Contentful imgx for map graphic updates moving forward.
origin/hotfix/update-explore-map
INT testing.
=> Update map graphic for Cbus

_includes/_head.html
Ensure we're loading crds-components from correct subdomain.
=> [demo] DE7414 Components

_includes/_head.html
Ensure we're loading crds-components from correct subdomain.
=> [production] DE7414 Components

logged-in-homepage.html
=> adding hotjar trigger

logged-in-homepage.html
=> Hotjar trigger prod

logged-in-homepage.html
=> fixing forloop

_assets/stylesheets/_fonts.scss, _assets/stylesheets/pages/_modules.scss, _assets/stylesheets/pages/_trip.scss, _config.yml, _includes/_reachout-google-map.html, _includes/_trip-card.html, _layouts/trip.html
Adding trip layout to build out trip details pages
=> Trip details

cypress/integration/homepage/home_page_latest_message_spec.js
=> add erroe handling to home_page_latest_messgae

cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/liveStream/live_stream_player_spec.js
=> Us18940-add_error_handling_for_test

_config.yml, bin/build-command.sh
- Adds distribution to config
- Updates netlify build command
=> Adds updates for distribution channels

redirects.csv
Would like to do Dry Run Cutover
Change redirects.csv file to allow for this
Need to do it in demo 
Going to manually test
=> Update for Demo Dry Run Cutover

logged-in-homepage.html, package-lock.json
=> merge to master: Us19008/video amplitude event

_config.yml
- page , podcast, query, video, category were previously removed [here](https://github.com/crdschurch/crds-net/pull/1344/files#diff-aeb42283af8ef8e9da40ededd3ae2ab2L156)
=> Adds missing types

redirects.csv
Initiate Rollback
Update redirects file to use old sign in page
=> Begin rollback

Gemfile.lock, _assets/stylesheets/_fonts.scss, _layouts/location.html, logged-in-homepage.html
Fix spacing issue on location pages
=> Location spacing

netlify.toml
This PR updates environment variables defined within `netlify.toml` to reflect the enterprise CDN.
=> Enterprise CDN Support

netlify.toml
Reverts crdschurch/crds-net#1394
=> Revert "Enterprise CDN Support"

_includes/_fb-pixel.html, _layouts/location.html
=> moving pixel code to location layout for all locations

_includes/groups/_footer.html, _layouts/onsite-group-detail.html, _layouts/onsite-group-location.html, onsite-groups.html
This PR consolidates the footer logic & markup on all OSG pages so that we have a single version and its visible across this entire group of pages.
=> DE7589 OSG Footer

logged-in-homepage.html
add current message to logged in hp
=> Add current message

_assets/javascripts/components/bitmovin.js, _assets/stylesheets/pages/_live-stream.scss, _includes/media/_bitmovin-player.html, index.html, logged-in-homepage.html
=> Ig feed hp

_functions/env-redirector.js
This PR adds support for redirecting users to a different URL within the demo or release environments.
=> US18872 Giving Redirect

index.html, logged-in-homepage.html
=> adding ig feed to hp and hp logged in

liveStreamTests/cypress/integration/live_stream_message_spec.js
commented out auto play test until defect is resolved created
=> removed check for crds-net production support live stream auto play

_includes/media/_bitmovin-player.html
=> US19274 added query params to bitmovin url

.gitignore, _includes/groups/_footer.html, _includes/groups/_meeting-details.html, _layouts/onsite-group-detail.html, _layouts/onsite-group-location.html, _layouts/onsite-group-meeting.html, _plugins/filters/onsite_groups_filters.rb, _plugins/generators/onsite_groups_generator.rb, lib/crds/jekyll_pages.rb, lib/crds/onsite_groups.rb, lib/crds/redirects.rb, onsite-groups.html, spec/fixtures/collections/_locations/eastside.md, spec/fixtures/collections/_locations/florence.md, spec/fixtures/collections/_locations/mason.md, spec/fixtures/collections/_locations/oakley.md, spec/fixtures/collections/_locations/westside.md, spec/fixtures/collections/_onsite_group_categories/onsite-groups.md, spec/fixtures/collections/_onsite_group_meetings/onsite_group_meeting-1xJH47b9VtMEHlN961zzTn.md, spec/fixtures/collections/_onsite_group_meetings/onsite_group_meeting-27PaFfzJ5EZDN67nNAL38g.md, spec/fixtures/collections/_onsite_group_meetings/onsite_group_meeting-2fis1qVWaqR4Pow8UWMilD.md, spec/fixtures/collections/_onsite_group_meetings/onsite_group_meeting-5157xqQ7zWsu5MYbDdqW2x.md, spec/fixtures/collections/_onsite_group_meetings/onsite_group_meeting-7eLZZxTyOcDYcD7DUZf5AD.md, spec/fixtures/collections/_onsite_groups/adoption-and-foster-family-resources.md, spec/spec_helper.rb, spec/support/jekyll_helper.rb, spec/unit/jekyll_pages_spec.rb, spec/unit/onsite_groups_spec.rb, spec/unit/redirects_spec.rb
This PR manually ports all OSG changes to a master-compatible topic branch.
=> [prod] Deploy Onsite Groups

redirects.csv
Reverts crdschurch/crds-net#1444
=> Revert "adding mapView redirect param in case thats causing the windows issues"

index.html, logged-in-homepage.html
=> removed instagram stuff

_assets/javascripts/components/bitmovin.js, _includes/media/_bitmovin-player.html
=> Us19378 [master]

redirects.csv
[Rally story](https://rally1.rallydev.com/#/38108142417d/detail/defect/382235644412)
=> DE7616 Netlify Redirect Error Development

_assets/javascripts/components/bitmovin.js
fixed subtitle issue on safari
=> [DEPLOY] DE7626

cypress/Contentful/OnsiteGroupEntry.js, cypress/Contentful/OnsiteGroupQueryManager.js, cypress/integration/404/404_spec.js, cypress/integration/homepage/home_page_latest_message_spec.js, cypress/integration/live/live_past_weekends_spec.js, cypress/integration/onsite/onsite_group_landing_page_spec.js, package-lock.json
=> add onsite group entry query manager a test landing page

redirects.csv
[Rally story](https://rally1.rallydev.com/#/38108142417d/detail/defect/382235644412)
=> DE7616 Netlify Redirect Error Master

logged-in-homepage.html
Update runway with the new logged in snail trail on the logged in homepage
[Rally Story](https://rally1.rallydev.com/#/38108142417d/detail/userstory/379482156500)
=> US19311 Logged in Snail Trail

redirects.csv
=> Hopefully final try...?

_assets/javascripts/components/bitmovin.js
stopped preprocessHttpRequest from modifying .vtt request
=> DE7663 deploy to prod

liveStreamTests/Dockerfile, liveStreamTests/README.md, liveStreamTests/cypress/config/demo_crossroads.json, liveStreamTests/cypress/config/int_crossroads.json, liveStreamTests/cypress/config/prod_crossroads.json, liveStreamTests/cypress/integration/live_stream_message_spec.js, liveStreamTests/cypress/plugins/index.js, liveStreamTests/cypress/support/commands.js, liveStreamTests/cypress/support/index.js, liveStreamTests/docker-compose.yml, liveStreamTests/package-lock.json, liveStreamTests/package.json
*Cypress and other packages were way out of date.*
*Fix for a known Docker/Cypress bug has not been applied.*
*Update packages and patch the Docker bug.*
*This mini-suite is run by scheduled builds in Team City. Once merged, run https://ci.crossroads.net/viewType.html?buildTypeId=Qa_Production_Bearsharktopus_LiveStreamEncodingTestProd*
=> defect/DE7018 - [PROD]Cypress Live Stream test update

redirects.csv
=> added splat

netlify.toml
This PR updates the sign-in proxy path
=> Rebrand - Sign In 

redirects.csv
=> updating giving redirects

redirects.csv
=> redirect rule in the wrong project

netlify.toml, redirects.csv
=> remove redirect for crds.net/forms

_assets/stylesheets/components/_jumbotron.scss, _includes/home/_kids-club-jumbotron.html, index.html, rebrand.html
Create Kids Club jumbotron in [this design](https://invis.io/5TWTAP2G7SH#/418123067_Home_-_V8)
Hardcode content here, content won't change frequently
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/395270394540?fdp=true)
[Preview](https://deploy-preview-1517--rebrand-crds-net.netlify.app/)
=> US19625 Kids Club Jumbotron

_layouts/location.html
Update jumboton font
Change jumbotron button to orange
[Design](https://invis.io/5TWTAP2G7SH#/414573493_Oakley_-_Signed_Out_-current-)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/396947139884?fdp=true)
[Preview](https://deploy-preview-1532--int-crds-net.netlify.app/oakley)
=> US19668 Location Jumbotron

_layouts/location.html
Add happenings component without location toggle
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/397178037468?fdp=true)
Update page to use crds-happenings component and specify a location using a location prop
The component will not work correctly until [this PR ](https://github.com/crdschurch/crds-components/pull/649/)is merged
=> US19674 Location Happenings

_assets/stylesheets/components/_jumbotron.scss, _includes/home/_kids-club-jumbotron.html
Update Kids Club Jumbotron
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/397604568828?fdp=true)
=> US19686 Kids Jumbotron

_includes/home/_content-menu.html, rebrand-logged-out-home.html
Related to crdschurch/crds-net#1540
=> US19633 Content Menu

_includes/home/_latest-news.html, rebrand-logged-out-home.html
Compose the Good news section in "Your Impact will be massive" section
Do we hardcode this content or wire it up to featured media model? AG is good either way but its important that they can administer this content
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/395269622896?fdp=true)
[Design Here](https://invis.io/5TWTAP2G7SH#/418123067_Home_-_V8)
[Preview](https://deploy-preview-1552--int-crds-net.netlify.app/rebrand-logged-out-home)
I think we should hard code this info for now and after launch we can figure out the best way to handle pulling in the news content
**This PR will be ready to review once these are merged:**
[Crds-Components](https://github.com/crdschurch/crds-components/pull/659)
[Crds-Styles](https://github.com/crdschurch/crds-styles/pull/462)
=> US19624 Latest News

_layouts/container-fluid.html, join.html
Build out the page based on the [approved design](https://invis.io/5TWTAP2G7SH#/418134900_Join_-_R2)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/395944839440?fdp=true)
[Preview](https://deploy-preview-1557--int-crds-net.netlify.app/join)
1. Still need links for "start your adventure now" button, "chat with us" button and video link
2. There is a space at the bottom of the page and it is a div around the footer in the container-fluid layout. I deleted the class so we might have issues in other places.
=> US19641 Join

_includes/home/_content-menu.html
=> DE7785 Our Content Menu

_includes/home/_latest-news.html
1. Add more space below the arrow and above the first horizontal rule
2. The dashed hr is too thicky thicc
3. The thumbnail shouldn't touch the dashed hr - add more padding between the two
[Rally Defect](https://rally1.rallydev.com/#/detail/defect/398544857080?fdp=true)
[Preview](https://deploy-preview-1565--int-crds-net.netlify.app/rebrand-logged-out-home)
[Crds-Styles](https://github.com/crdschurch/crds-styles/pull/468)
=> DE 7793 Good News

_assets/stylesheets/_utilities.scss, _assets/stylesheets/components/_labels.scss, logged-in-homepage.html
=> US19707 Homepage Logged In

_assets/javascripts/lib/smooth-scroller.js, _includes/about/_leadership.html, about.html
1. Link the "About Brian" button to /brian-tome/ instead of his author page (all others will remain the author page)
2. Make all the social links for each of the leadership team open in a new tab
3. Within "The Basics", the links for the pages are as follows:
- Crds History - /ourhistory
- Seven Hlils - /sevenhills
- What We Believe - /whatwebelieve
- Annual Report - /annualreport
4. Can you get the jumbotron image reflected in the design from AG and update here?
5. For the leadership team, the btn labels should read "More from Brian" "More from Chuck" etc (instead of "About Brian")
6. The smooth scroll when clicking on the FAQs is rather slow - can you speed that up a lil bit?
[Preview](https://deploy-preview-1575--int-crds-net.netlify.app/about)
=> DE7798 about pg edits

_assets/stylesheets/components/_hubspot-forms.scss
Bump crds-styles to latest
[Preview](https://deploy-preview-1581--int-crds-net.netlify.app/)
=> DE7805 Border Radius

index.html
Updates "What Matters to You" link in Our Best content section to go to: /media/videos/what-matters-to-you
- **Note:** Page only exists in prod
- [Rally](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F399002823556)
- [Preview](https://deploy-preview-1585--int-crds-net.netlify.app/)
=> DE7808 [rebrand] homepage - best content links

_assets/stylesheets/components/_hubspot-forms.scss, _includes/about/_faqs.html, about.html
- **Note:** These will need to be merged/deployed first
- **Note:** crds-styles Submodule will need to be updated once the PR is merged
- [crds-styles](https://github.com/crdschurch/crds-styles/pull/477)
- [crds-components](https://github.com/crdschurch/crds-components/pull/669)
- **See Screenshot 1**
- **See Screenshot 1**
- **Dependant on [crds-components](https://github.com/crdschurch/crds-components/pull/669) PR**
-  **See Screenshot 2**
- **Dependant on [crds-styles](https://github.com/crdschurch/crds-styles/pull/477) PR and Submodule update**
- [Rally](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F398975289204)
- [Preview](https://deploy-preview-1581--int-crds-net.netlify.app/about)
=> DE7804 [rebrand] a few more about pg updates

_includes/about/_faqs.html
Fixes FAQs scrolling past the heading it should. This PR adds an offset above the heading to make sure it does not over-scroll
- [Preview](https://deploy-preview-1592--int-crds-net.netlify.app/about)
- [Rally](https://rally1.rallydev.com/#/66096747656d/custom/24109743995?qdp=%2Fdetail%2Fdefect%2F398975289204)
=> DE7804: [rebrand] a few more about pg updates

_includes/about/_leadership.html
Add darin yates
fix typo. `img-src` to `image-src`
=> DEXXXX Add Darin Yates

_assets/stylesheets/pages/_live-stream.scss
Fix bg color of "don't miss" section
=> USXXXXX Fix live stream BG

_includes/about/_faqs.html
Add another FAQ to About page and appropriate anchor link. 
[Rally](https://rally1.rallydev.com/#/66096747656ud/detail/userstory/399512496696?fdp=true)
[Deploy Preview ](https://5ef100d90b264800081d93cd--int-crds-net.netlify.app/about)
=> US19746/Adds FAQ to about page

index.html
The "articles, podcasts and more" section of logged out homepage is supposed to show the three most recent pieces of content. Two issues I'm seeing here:
1. These aren't the three most recent content items (not even the three most recent articles)
2. One of them is duplicated (the big feature one and the lower right)
[Preview](https://deploy-preview-1605--int-crds-net.netlify.app/)
=> DE7821 Most Recent

_assets/stylesheets/_utilities.scss
Delete unneeded styles for `bg-overlay` because it is already in crds-styles
=> DE7833 Media Image Overlay

30-day-trial.html, _includes/home/_jumbotron.html, about.html, index.html, redirects.csv
1. update meta title to reflect "30 Day Trial"
2. Update video -- NEED FROM AG (as of 6/23 @ 9:40am AG still doesn't have it, please move the story without it and i'll just create a new story once we get it)
3. Update first bullet in the What to Expect box to read:
Create a profile (if you don’t have one already) and kickstart your growth by going on a 30-day journey to learn about how God made you and what plans He has for your life.
4. Update URL to use kabob case ("THE ONLY CORRECT CASE" -Dan) /30-day-trial
5. Add redirect for /30daytrial --> /30-day-trial
6. Update necessary links to point to /30-day-trial (homepage logged out, /about)
7. Update links on page to sign up to point to /30-day-trial/sign-up (btns in jumbotron and below the video) …
=> DE7806 30 Day Trial

_includes/_location-card.html, _includes/_locations-grid.html
My local dev branch had issues so I created a new one following Taylor's guidance. Including rebrand to location-cards
INT and Local
=> Adding rebrand to location cards

spiritual-outfitters.html
Update metadata on this page. Please add a meta title, description and image. 
- title: Spiritual Outfitters 
- descrip: Crossroads has a brand new look. 
- img: https://crds-media.imgix.net/7EFusaW9y0WFSxO9KCdumH/2edc127ce50430b3894692f7075122fb/spiritual-outfitters.jpg
[Preview](https://deploy-preview-1620--int-crds-net.netlify.app/spiritual-outfitters/)
[Hey Meta](https://www.heymeta.com/url/deploy-preview-1620--int-crds-net.netlify.app/spiritual-outfitters/)
=> DE7846 Spiritual Outfitters

netlify.toml
Serve Okta signing pages from discreet Netlify project (not branch deploys)
=> DEXXXX Branch Deploys

30-day-trial.html, our-history.html, seven-hills.html, spiritual-outfitters.html, statement-of-faith.html, what-we-believe.html
Update meta Data for new pages
/seven-hills
page title: Seven Hills We Die On | Crossroads
descrip: As a church, we believe that if something is worth living for, it is worth dying for. 
img: http://crds-media.imgix.net/3u1o8P0WJH07ktyJbUj4pc/9984660755eeee4b608b3ce60e8ab620/seven-hills.jpg
/what-we-believe
title: What We Believe | Crossroads
descrip: Learn more about what we believe as a church.
img: http://crds-media.imgix.net/50FBEpFzihpFas4F67NhnS/76b9d09dc500c84ff6cedfb6b71cdfc8/what-we-believe.jpg
/statement-of-faith
title: Statement of Faith | Crossroads
descrip: Learn more about our statement of faith.
img: http://crds-media.imgix.net/2400yJgIheb1iCSLedBvm/b49f37686517f24841e1688136e35ba7/statement-of-faith.jpg
/our-history
title: Our History | Crossroads
descrip: In 1995, a group …
=> US19757 Meta Data

30-day-trial.html
Update Page based off [new design](https://invis.io/5TWTAP2G7SH#/422867212_Join_-_Final_FINAL)
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/399992554564?fdp=true)
[Preview](https://deploy-preview-1631--int-crds-net.netlify.app/30-day-trial/)
=> US19784 30 Day Trial

_includes/explore/_explore-resources.html
Change ctfassets references to imgix where possible
Video and gifs cannot be used through imgix
=> DE7867 Ctfassets

_assets/stylesheets/_utilities.scss
Removes the duplicate selector in crds-net utilities.scss per the following comment... 
[https://github.com/crdschurch/crds-net/pull/1634/files#r445707952](https://github.com/crdschurch/crds-net/pull/1634/files#r445707952)
=> DE7863: Duplicate Styles in crds-net

_layouts/location.html
=> Hot Fix (location pages)

_layouts/location.html
=> DE7880 Lexington Preschool

_includes/_location-card.html
Retroactively making sure `Development` branch is current with this HOTFIX on `Master` branch.
=> Location cards

redirects.csv
Add proxy to workaround 404s in /media
=> DE7886 Subscribe

_config.yml, index.html
Update Meta for homepage
copy - You were born to make a difference. Designed to partner with God to change the world for good. If that sounds like your type of adventure, Crossroads is your spiritual outfitter.
img: https://images.ctfassets.net/y3a9myzsdjan/7EFusaW9y0WFSxO9KCdumH/2edc127ce50430b3894692f7075122fb/spiritual-outfitters.jpg
=> DE7893 Update Meta

30-day-trial.html, _includes/about/_faqs.html, _includes/home/_jumbotron.html, _includes/home/_latest-news.html, _includes/home/_you-are-needed.html, about.html, index.html, spiritual-outfitters.html
**Home**
• change article headlines in good news section
• update “our best content” with new articles
• BT section headline - remove “s” in guides
• update “about crossroads” text
**30 day**
• change headline and CTA copy
**About**
• Adding padding to main jumbo
**Spiritual Outfitters**
• update copy, add video CTA to about spiritual outfitters video.
• update “same mission. new visual…” copy.
**All edits here**:
https://docs.google.com/presentation/d/1UXFwGqjEVIbK33PbtrBBPnHXRgW3V7nBA3zaYMTuDKw/edit?usp=sharing
=> Updates to Home, 30 day, About, Spiritual Outfitters

our-history.html, seven-hills.html
=> Rebrand defects master

_layouts/location.html
• add bg-overlay to main jumbo
=> update social link 

_layouts/location.html
• add “bg-overlay” to main jumbo
=> update social link

index.html
Make Gear Up Cards editable via CMS
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/401029768732?fdp=true)
Make Gear Up section a content block
[Preview](https://deploy-preview-1668--int-crds-net.netlify.app/)
=> US19801 Gear up CMS

_includes/home/_you-are-needed.html
Make the Make a Difference Cards editable via the CMS
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/401029783608?fdp=true)
Make content for this section a content block
[Preview](https://deploy-preview-1669--int-crds-net.netlify.app/)
=> US19804 Make a Difference CMS

_includes/home/_jumbotron.html
Make Jumbotron content editable via the CMS
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/401029789240?fdp=true)
Make Jumbotron content a content block
[Preview](https://deploy-preview-1670--int-crds-net.netlify.app/)
=> US19805 Jumbotron Content CMS

_includes/home/_our-best-content.html, index.html
Enable content updates for Our Best Content (featured media) section on logged out home via CMS. Use the featured media content type
[Preview](https://5f04ac4bfaedeb0008fad478--int-crds-net.netlify.app/)
=> US19799 Best Content CMS

index.html
Make Cards content editable via the CMS
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/401030441612?fdp=true)
Make Homepage cards a content block
[Preview](https://deploy-preview-1672--int-crds-net.netlify.app/)
=> US19806 Homepage cards CMS

_includes/home/_kids-club-jumbotron.html
Make Kids Club content editable via the CMS
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/401030473596?fdp=true)
Make Kids Club jumbotron content into a content block
[Preview](https://deploy-preview-1674--int-crds-net.netlify.app/)
=> US19807 Kids Club Jumbotron CMS

index.html
Make Bottom CTA content editable via the CMS
[Rally Story](https://rally1.rallydev.com/#/detail/userstory/401030476740?fdp=true)
Make Bottom CTA content into a content block
[Preview](https://deploy-preview-1675--int-crds-net.netlify.app/)
=> US19808 Sign up CTA CMS

_includes/_locations-grid.html
No service times or social links for Anywhere like the other locations.
Added service times and social links. Hard-baked. Not managed in Contentful
INT & Local
=> Adding Anywhere time and social links

_includes/home/_kids-club-jumbotron.html
Adds missing Liquify filter for kids club jumbotron
=> Fixes kids club liquify

index.html
Updates meta data description on homepage to "Whatever your thoughts on church or your beliefs about God, you're welcome here." 
[Rally ](https://rally1.rallydev.com/#/66096747656ud/custom/24109743995?detail=%2Fdefect%2F400427191064&fdp=true)
=> Updates meta data on homepage

compassion-bolivia.html, compassion-nicaragua.html
=> Compassion fix

_layouts/location.html
=> add env variable

_layouts/location.html
=> Dayton btn update

brian-tome.html
=> Bt link form fix

index.html
=> update ways to watch image

netlify.toml, package-lock.json, package.json
This PR bumps the redirects plugin to its latest version.
=> DE7889 Invalid Redirects

brian-tome.html
=> Bt ig update

_assets/stylesheets/pages/_digital-tool-belt.scss, _assets/stylesheets/pages/_modules.scss, digital-tool-belt.html
=> Digital toolbet tabs

_assets/javascripts/config.js
Delete old reference simple fred in js config
=> Hot Fix: remove ref to simple fred in config

redirects.csv
=> Dry run cutover3

_includes/_location-card.html, _includes/_locations-grid.html, redirects.csv
This PR removes the hard-coded anywhere card and adds a 301 redirect for /anywhere
=> US20052 Locations

redirects.csv
Reverts crdschurch/crds-net#1769
=> Revert "Dry run cutover3"

_layouts/onsite-group-detail.html, _layouts/onsite-group-location.html, _plugins/generators/onsite_groups_generator.rb, lib/crds/onsite_groups.rb, onsite-groups.html
This PR updates references to the name of the 'Anywhere' location in /groups/onsite to 'online'.
=> US20052 OSG Groups

lib/crds/onsite_groups.rb
This PR changes the name of the online/anywhere group reflected in /groups/onsite
=> US20052 OSG Online

onsite-groups.html
Reverse order of group categories.
=> US20052 Onsite Groups

_includes/spark/_allgotrips.html
=> spark msg week 5

redirects.csv
Want to help make it easier to fix any redirect issues with form maker
=> Make new redirects 302

redirects.csv
=> Undivided redirect

redirects.csv
=> add undivided redirect back

cypress/config/vault_config.json
Moving all vault vars to crds-net secret
=> fixing cyrpress vault vars

redirects.csv
Removing sunset code: Leave Your Mark
Test on INT through URL: https://int.crossroads.net/leaveyourmark
=> Remove Leave Your Mark

index.html, logged-in-homepage.html
=> added crds-journey-banner to LI and LO homepage

_assets/stylesheets/components/_jumbotron.scss, _assets/stylesheets/pages/_modules.scss, _assets/stylesheets/pages/_watch.scss, watch.html
[Preview Link](https://app.netlify.com/sites/crds-net/deploys/5f77773358647c0008023db7)
=> US20222 Watch Master
